### ISSUE TITLE
Unable to find generated Parcelable class when calling Parcels.wrap on a Realm object

### ISSUE THREAD

**Issue by LaurieScheepers** [johncarl81/parceler#104]
Hi, I have a Message class that extends RealmObject. I've added the workaround mentioned here to let Parceler and Realm work together, but am still having issues.

I define the class as follows:

```
@Parcel(implementations = { Message.class }, value = Parcel.Serialization.BEAN, analyze = { Message.class })
public class Message extends RealmObject {
// Class implementation
}
```

but when calling the following (as suggested by the workaround)

```
Bundle bundle = new Bundle();
bundle.putParcelable(EXTRA_MESSAGE, Parcels.wrap(Message.class, message));
```

I get this exception:

```
org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for com.notify.data.persistent.Message, verify that your class is configured properly and that the Parcelable class com.notify.data.persistent.Message$$Parcelable is generated by Parceler.
```

Also included the following in my build.gradle:

```
buildscript {
    dependencies {
        classpath 'org.robolectric:robolectric-gradle-plugin:1.0.1'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}

apply plugin: 'com.neendenbankt.android-apt'

dependencies {
     compile 'org.parceler:parceler-api:1.0.0'
     provided 'org.parceler:parceler:1.0.0'
}

```

Is there anything I am missing? The fact that Realm doesn't work well with Parceler is causing quite a headache :(

**Comment by johncarl81** [comment]
Hmm, you may not need the implementations property unless you're using a subtype of your Message object, likewise the Message.class might be unnecssary if you're using an instance of Mesage.

I've heard of problems using propvided, can you try to change the parceler to apt scope?:

```
dependencies {
     compile 'org.parceler:parceler-api:1.0.0'
     apt 'org.parceler:parceler:1.0.0'
}
```

**Comment by LaurieScheepers** [comment]
Changing it to apt now causes the build to fail:

```
Error:Parceler: Unable to find read/write generator for type io.realm.Realm for io.realm.RealmObject.realm
Error:Parceler: Unable to find read/write generator for type io.realm.internal.Row for io.realm.RealmObject.row
```

**Comment by johncarl81** [comment]
That's strange.. it sounds like the `RealmObject` is being analyzed.  I wonder if there's a bug in the interaction between BEAN type and the analyze property.  I'll investigate.

**Comment by LaurieScheepers** [comment]
Thanks

**Comment by johncarl81** [comment]
I hate to say this, but this works for me.  Can you try a clean?

**Comment by johncarl81** [comment]
Is your `Message` class referenced in an `@ParcelClass` anywhere else in your application?

**Comment by LaurieScheepers** [comment]
Hi, yes it is. We have another RealmObject that is also a Parcel class that has the Message class as a member variable. Btw cleaning and doing a new build still gives the same error

**Comment by johncarl81** [comment]
Ah, I believe this bug was fixed here #96.  Can you try the latest from the repo: https://jitpack.io/#johncarl81/parceler/e20e22ff8f

If this works for you I'll consider issuing a 1.0.1 release.

**Comment by LaurieScheepers** [comment]
Not sure how I should change my dependencies now. Is this correct:

```
compile 'org.parceler:parceler-api:1.0.0'
//    apt 'org.parceler:parceler:1.0.0'
compile 'com.github.johncarl81:parceler:e20e22ff8f'
```
I get

```
Error:Could not find com.github.johncarl81:parceler:e20e22ff8f.
```

I included the jitpack repo as such

```
repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
```

**Comment by LaurieScheepers** [comment]
Ok, update the library is found when I include the repo in the top-level build.gradle

```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

However I get this warning when I do a Gradle sync (which also fails the build):

```
Warning:Dependency com.github.johncarl81.parceler:parceler-performance:e20e22ff8f on project app resolves to an APK archive which is not supported as a compilation dependency. File: .../com.github.johncarl81.parceler/parceler-app/e20e22ff8f/cff1c4fa329b7ebbf97a948dcb750414d6874995/parceler-app-e20e22ff8f.apk
```

Not sure what the issue is. I tried adding @jar for the dependency, but that gives other Gradle errors.

I'm still relatively new to Gradle, so any help would be appreciated, and I'm sure this post will help other people as well :)

**Comment by LaurieScheepers** [comment]
Good news, everything is sorted out now.

Summary:

With v1.0.0 the build fails when there is a RealmObject Parcel class that contains another RealmObject Parcel class as a member variable. This caused the error

```
"Error:Parceler: Unable to find read/write generator for type io.realm.Realm for io.realm.RealmObject.realm "
```

Updating to the fixed version (after changing the top-level build file instead of the project one) fixes this issue.

I had more problems after that because it turned out the one class that was referenced from our Message class didn't follow JavaBeans standards :( The issue:

In the constructor (as an example of the error):

```
public Message(String messageContent) {
        this.content = messageContent;
} 
```

and
```
public MessageContent getMessageContent() {
        return this.content;
}
```

Instead of this.messageContent

I can confirm that [#96](https://github.com/johncarl81/parceler/issues/96) fixes the original issue that I had as I reverted to the 1.0.0 version after fixing our code and still got the same error as above. 

Looking forward to a new release, and thanks for the help :)

**Comment by johncarl81** [comment]
Great, thanks for the feedback @LaurieScheepers.  I'll issue a release shortly.

**Comment by LaurieScheepers** [comment]
Great, and thanks for the quick response to the issue!

**Comment by johncarl81** [comment]
1.0.1 is in the queue and should be on central soon.

**Comment by LaurieScheepers** [comment]
New release works. Thanks

**Comment by johncarl81** [comment]
Beautiful, thanks for the confirmation.
