### ISSUE TITLE
allow different Serialization types

### ISSUE THREAD

**Issue by tom91136** [johncarl81/parceler#105]
Currently, we have support for JavaBean style getter and setters:
```java
@Parcel(Serialization.BEAN)
//...the class....
    private final Foo foo;
    Foo getFoo() {return foo;}
    void setFoo(Foo foo){this.foo = foo;}
```

What if I got something like:
```java
private final Foo foo;
Foo foo() {return foo;}
void foo(Foo foo){this.foo = foo;}
```
In this case all the getters and setters will match the field's name respectively and does not follow the conventional JavaBean pattern of get/set<FieldName>()
I propose to allow users to customize the serialization prefix(or pattern) so that if the class has lots of properties, we don't have to annotate every getter/setter.

Maybe something like this:
```java
public @interface Parcel {
    //....
    Class<? extends MethodPredicate> matcherClass default MethodPredicate.BeanPredicate;
    //....
}
```

```java
public interface MethodPredicate {

    String testGetter(Method method); // returns null if method is not a property (or maybe something better?)
    String testSetter(Method method); 

    public static class BeanPredicate{
        // you get the idea...
    }
}
```

**Comment by johncarl81** [comment]
I think this is a cool idea.  Here's the relevant code in the processor:
https://github.com/johncarl81/parceler/blob/master/parceler/src/main/java/org/parceler/internal/ParcelableAnalysis.java#L129-L140

I believe the interface would be more of a `PropertyPredicate` which would return the names of the given properties of each method / field:

```java
public interface PropertyPredicate {
    String getReadMethodProperty(ASTMethod method);
    String getWriteMethodProperty(ASTMethod method);
    String getFieldProperty(ASTField field);
}
```

Is it enough for this class to specify the baseline-default properties of the class?

The thing we would need to be careful of is how this plays into Constructor and Static Factory property writing and the fine turning (`@Transient`, `@ParcelProperty`) of the type mapping.

Thoughts?

**Comment by tom91136** [comment]
Yep, `PropertyPredicate` looks good.

As for the complicated stuff, this is what I came up with:
 * Methods/fields marked with `@Transient` are ignored and will not go through the predicate at all
 * Explicitly annotated properties such as ones marked with `@ParcelProperty` should take precedence over the assigned predicate, meaning that the property does not go through the predicate at all if annotated. (I think this has always been the case thought, just making sure )

There might be incompatibilities with the current spec though because I haven't tried all the features of Parceler yet. This is just a suggestion :)

**Comment by tom91136** [comment]
Any news on this?

**Comment by johncarl81** [comment]
I really haven't focused on this, but I had a few thoughts.

I'm hesitant to open up the most complex part of the app with a plugin; the class analysis.  I'm not sure there are a ton of cases that we'd need to handle that aren't already covered by the existing (albeit verbose) annotation configuration.

What do you think about adding a new serialization type though?  I wonder if we could make a method seialization configuration that would follow the technique you've mentioned.  Something like matching the accessor / mutators by name and parameter / return type.  WDYT?

**Comment by tom91136** [comment]
Yeah, a new serialization type for my usecase would work too since I believe it's becoming common(for example, [this ](http://square.github.io/okhttp/javadoc/com/squareup/okhttp/Request.html)one. (Not that I'm gonna try to serialize that)). This will work for now, but I still think that the flexibility provided by the plugin thing will give us better extensibility.

One specific advantage of having a plugin system would be that users can integrate Parceler very quickly regardless of which coding style they choose for their data objects. I would imagine people who love immutable objects would love to just do:

    @Parcel(propertyPredicate=ImmutableObjectPredicate.class)
    public class Foo{
    
    	// no annotation :)
    	public final String bar;
    	// lots and lots of other fields...
    	
    	@ParcelConstructor // we might not even need this, just the first @Parcel(...) would be enough
    	public Foo(String bar /*......more */){
    		this.bar = bar;
    	}
    
    }


It's your call, it's your library after all. If I really need this feature I would probably fork it and do it there.

**Comment by johncarl81** [comment]
I designed Parceler to handle immutable objects OOTB with minimal configuration.  The default FIELD configuration should work for your example:

```java
@Parcel
public class Foo{
    // no annotation :)
    public final String bar;

    @ParcelConstructor
    public Foo(String bar){
        this.bar = bar;
    }
}
```

**Comment by johncarl81** [comment]
Here's the new seralization type im thinking about:

Currently the `BEAN` type serializes using the java bean standard.  Only public getters and setters (methods that sart with get / set) are analyzed by default.  In comparison, a new method style could look at all public methods, and use the entire method name.  This would work then:

```java
@Parcel(NEW_METHOD_TYPE) public class Foo {
    //...
    public String value(){...};
    public void value(String value){...};
}
```

This would play well into AutoValue support (http://parceler.org/#static_factory_support) removing the need to annotate non-bean getters:

```java
@AutoValue
@Parcel(NEW_METHOD_TYPE)
public abstract class AutoValueParcel {

    public abstract String value();

    @ParcelFactory
    public static AutoValueParcel create(String value) {
        return new AutoValue_AutoValueParcel(value);
    }
}
```

Thoughts?

**Comment by tom91136** [comment]
Sorry I wasn't thinking when typing the immutable object example. 

As for the new serialization type, I think it would work great. Just a few questions:

1. Just to confirm, annotations such as `@Transient` will take precedence over the serialization method, correct?
2. Will this handle the case where `@ParcelConstuctor` is present while having no `setters`?


For 2, I'm talking about something like this:


       @Parcel(NEW_METHOD_TYPE) public class Foo{

        private final String bar;
       
        @ParcelConstructor 
        public Foo(String bar){
            this.bar = bar;
        }
    	
    	public String bar(){
    		return bar;
    	}
    
    }

**Comment by johncarl81** [comment]
1.  Yes, as will `@ParcelProperty` etc.
2.  Yes

Yup, that's the exact serialization technique I'm thinking of as well.  I don't know what these are called, maybe Value objects?

**Comment by tom91136** [comment]
Yeah, [Lombok](https://projectlombok.org/features/Value.html) called it `@Value`

**Comment by johncarl81** [comment]
So, maybe `@Parcel(VALUE)` then?

**Comment by tom91136** [comment]
:+1:  (I believe the plugin idea is shelved :) )

**Comment by johncarl81** [comment]
@tom91136, I have a relatively complete implementation here: 68e53eedb2a29767347b5476cb3efe71db4bb7c0  If you give it a try, let me know how it works for you.

**Comment by tom91136** [comment]
Is there a snapshot release for this? I can build it my side if you want.

**Comment by johncarl81** [comment]
You can use jitpack thorugh Gradle or Maven to easily pull in the lastest:

https://jitpack.io/#johncarl81/parceler/3a4f12f400

**Comment by tom91136** [comment]
Testing now.  Jitpack looks awesome, thanks for letting me know :)

**Comment by johncarl81** [comment]
Yeah, @jitpack is pretty awesome :smile: !  Makes it easy for libraries to try out unreleased code.

**Comment by tom91136** [comment]
Hold on, the dependency seems to point to an apk for some reason... 

Here's how the dependencies look like in the build file:

    // provided 'org.parceler:parceler:1.0.1'
    // compile 'org.parceler:parceler-api:1.0.1'

    compile 'com.github.johncarl81:parceler-api:3a4f12f400' // this resolves to nothing :(
    provided 'com.github.johncarl81:parceler:3a4f12f400' // points to parceler-app

Am I doing something wrong here?

**Comment by johncarl81** [comment]
I think you need to reference the submodules:
```
compile 'com.github.johncarl81.parceler:parceler-api:3a4f12f400'
provided 'com.github.johncarl81.parceler:parceler:3a4f12f400'
```

**Comment by tom91136** [comment]
Got it, my bad

**Comment by tom91136** [comment]
Test result on my side looks good, I'll open another issue if I find any bugs. Thanks!

**Comment by tom91136** [comment]
First of all, sorry for bringing this up again, I know this issue has been closed but I just wanted to put some of my thoughts on the original plugin idea.
I was implementing a very similar thing myself and I find this plugin thing I mentioned in the OP extremely hard to accomplish. If a user defined a test to filter out methods and do some name transformation in their code base (basically, the plugin), the annotation processor will see the defined class but it will not be able to execute any of the code since all it sees is a `DeclaredType`. In order to do anything with the class, I would have to obtain the source code for that class and compile it in the processor, which is not nice to do. 

The only viable workaround that I have in mind is If I make the user define the entire plugin class in an annotation field (a string field with code basically), then the processor will see the source code and I would be able to compile it. But this introduces another layer of complexity and the behaviour of the compiled code becomes very hard to reason about since it might be using imports outside of the JDK (well, in the invalid import case, the code will probably not compile anyway).

To demonstrate

    @PropertyPredicate(
        read = "return method.blah() && method.boo()", 
        write = "String s = method.str(); return s.length() > 100 && s.charAt(1) == '_';", 
        field = "/*some more code*/" 
    )

We then append the fragments above into a skeleton class and then compile:


    String code = "public class PropertyPredicate {
        String getReadMethodProperty(ASTMethod method) { " + read + " }
        String getWriteMethodProperty(ASTMethod method) { " + write + " }
        String getFieldProperty(ASTField field) { " + field + " }
    }";
	
	
	/* compile the string above into an actual class using the Java compiler API*/
	
	PropertyPredicate pp = classLoader.findClass("PropertyPredicate").newInstance();
	// and then we got the actual PropertyPredicate in out processor

So yeah, I didn't realize how complicated this actually is. Just thought I would bring it up because I'm in the process of writing my own processor and find this issue pretty interesting.Maybe you can suggest some other way of doing this?

**Comment by johncarl81** [comment]
@tom91136, I've been thinking about this and have a few thoughts.  Let me put together an example application to demonstrate the different options with the pros / cons.
