### ISSUE TITLE
Supporting specialised list types

### ISSUE THREAD

**Issue by cmelchior** [johncarl81/parceler#107]
Hi

I was trying to implement this library with Realm (https://github.com/realm/realm-java), and ran into a limitation of what collections could be parcelled, e.g. a Realm class could look something like this:

```java
public class Foo extends RealmObject {
  private RealmList<Bar> bars;
  
  public void setBars(RealmList<Bar> bars) {
    this.bars = bars;
  } 

  public RealmList<Bar> getBars() {
    return bars;
  }
}
```

From reading the documentation it it seems that only the standard Java/Android collections are supported. Is that correct or is there some configuration I am missing?

If that is indeed a limitation, is there any technical reason for it? I would assume it would be fairly easy to detect the type of list used and just recreate it when unwrapping the Parcel? 

It would obviously require that this library could construct a instance of the specialised list, but e.g. GSON works this way.

**Comment by johncarl81** [comment]
I don't see any reason why you couldn't write a custom `ParcelConveter` to support the `RealmList` type:
http://parceler.org/#custom_serialization

To make this easier check out the bundled converter decorators in the api module:
https://github.com/johncarl81/parceler/tree/master/parceler-api/src/main/java/org/parceler/converter

**Comment by cmelchior** [comment]
Thanks for the pointer. I totally missed the ParcelConverter, but that should do the trick.

**Comment by johncarl81** [comment]
Great!  Could you provide the `ParcelConverter` you come up with in this thread in case people are looking for a similar solution?

**Comment by cmelchior** [comment]
Sure

**Comment by cmelchior** [comment]
Hi, I have been banging my head agains the following issue.

If you take the example from the website on custom serialisation and convert it to using a custom list implementation that extends ```AbstractList``` then the annotation processor crashes with the following error: 

```
Parceler: Unable to find read/write generator for type io.realm.examples.intro.model.MyList<io.realm.examples.intro.model.Item> for io.realm.examples.intro.model.Item#itemList
```

If you instead of extending ```AbstractList``` e.g extends ```ArrayList``` then everything works. Am I missing some configuration or is this a bug?

```
@Parcel(value = Parcel.Serialization.BEAN)
public class Item {

    @ParcelPropertyConverter(ItemListParcelConverter.class)
    private MyList<Item> itemList;

    public MyList<Item> getItemList() {
        return itemList;
    }

    public void setItemList(MyList<Item> itemList) {
        this.itemList = itemList;
    }
}

// extend ArrayList<T> instead and everything works
`public class MyList<T> extends AbstractList<T> {

    @Override
    public T get(int location) {
        return null;
    }

    @Override
    public int size() {
        return 0;
    }
}


public class ItemListParcelConverter implements ParcelConverter<MyList<Item>> {

    @Override
    public void toParcel(MyList<Item> input, android.os.Parcel parcel) {
        if (input == null) {
            parcel.writeInt(-1);
        }
        else {
            parcel.writeInt(input.size());
            for (Item item : input) {
                parcel.writeParcelable(Parcels.wrap(item), 0);
            }
        }
    }

    @Override
    public MyList<Item> fromParcel(android.os.Parcel parcel) {
        int size = parcel.readInt();
        if (size < 0) return null;
        MyList<Item> items = new MyList<Item>();
        for (int i = 0; i < size; ++i) {
            items.add((Item) Parcels.unwrap(parcel.readParcelable(Item.class.getClassLoader())));
        }
        return items;
    }
}
```

**Comment by johncarl81** [comment]
Oh, with the BEAN serialization technique you need to annotate the getter or setter:
```java
@Parcel(value = Parcel.Serialization.BEAN)
public class Item {

    private MyList<Item> itemList;

    @ParcelPropertyConverter(ItemListParcelConverter.class)
    public MyList<Item> getItemList() {
        return itemList;
    }

    public void setItemList(MyList<Item> itemList) {
        this.itemList = itemList;
    }
}
```

Also, you may want to just use the `CollectionParcelConverter` to handle problems like nullability and putting items into your list.  All you have to do is specify the type and how items are get/set into your object:

```java
public class MyListParcelConverter extends CollectionParcelConverter<Item> {
    
    @Override
    public Item itemFromParcel(Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable(MyListParcelConverter.class.getClassLoader()));
    }

    @Override
    public void itemToParcel(Item input, Parcel parcel) {
        parcel.writeParcelable(Parcels.wrap(input), 0);
    }

    @Override
    public MyList<Item> createCollection() {
        return new MyList<Item>();
    }
}
```

**Comment by johncarl81** [comment]
Any movement on this one @cmelchior?

**Comment by cmelchior** [comment]
Hi @johncarl81 
Sorry for the late reply. I am currently on vacation so this might move a bit slow.
Moving ```@ParcelPropertyConverter(ItemListParcelConverter.class)```to the getter or setter doesn't resolve this. The annotation processor still fails with the same error message until ```MyList``` extends ```ArrayList``` instead of ```AbstractList```

**Comment by johncarl81** [comment]
Shoot, I just tried both strategies again and neither errored for me (`MyListParcelConverter` or `ItemListParcelConverter`):
```java
@Parcel(value = Parcel.Serialization.BEAN)
public class Item {

    private MyList<Item> itemList;

    @ParcelPropertyConverter(MyListParcelConverter.class)
    public MyList<Item> getItemList() {
        return itemList;
    }

    public void setItemList(MyList<Item> itemList) {
        this.itemList = itemList;
    }
}
```


I did, however, see an error when annotating the field directly:
```
Item.java:[28,17] Parceler: Unable to find read/write generator for type org.parceler.MyList<org.parceler.Item> for org.parceler.Item#itemList
```

**Comment by cmelchior** [comment]
I have created a project here demonstrating the behaviour I am seeing: https://github.com/cmelchior/parcelerbug

When running

```
./gradlew clean assemble
```

it fails with

```
/Users/cm/parcelerbug/app/src/main/java/com/parceler/parcelerbug/Item.java:16: error: Parceler: Unable to find read/write generator for type com.parceler.parcelerbug.MyList<com.parceler.parcelerbug.Item> for com.parceler.parcelerbug.Item#itemList
    public void setItemList(MyList<Item> itemList) {
                ^
1 error
```

**Comment by johncarl81** [comment]
Awesome, thanks @cmelchior.  It really helps to see a working example.  I'll review today and get back to you asap.

**Comment by johncarl81** [comment]
Ok, in version 1.0.1, for the converter to be picked up you need to also annotate the method with `@ParcelProperty`:
```java
@Parcel(value = Parcel.Serialization.BEAN)
public class Item {

    private MyList<Item> itemList;

    @ParcelProperty("itemList")
    @ParcelPropertyConverter(ItemListParcelConverter.class)
    public MyList<Item> getItemList() {
        return itemList;
    }

    public void setItemList(MyList<Item> itemList) {
        this.itemList = itemList;
    }
}
```

In the upcoming 1.0.2 release we did away with the `@ParcelProperty` requirement.  From this investigation I've also added some tests around this and fixed a related bug:  321af5ec9437f110448e4667c56ce1efcefad52e

**Comment by cmelchior** [comment]
Cheers, that worked.

The complete solution for a Realm project using a RealmList combined with Parceler 1.0.1 is the following:

```
@Parcel(implementations = { FooRealmProxy.class }, value = Parcel.Serialization.BEAN, analyze = { Foo.class })
public class Foo extends RealmObject {
  private RealmList<Bar> bars;

  @ParcelProperty("bars")
  @ParcelPropertyConverter(BarListParcelConverter.class)
  public void setBars(RealmList<Bar> bars) {
    this.bars = bars;
  } 

  public RealmList<Bar> getBars() {
    return bars;
  }
}

@Parcel(implementations = { BarRealmProxy.class }, value = Parcel.Serialization.BEAN, analyze = { Bar.class })
public class Bar extends RealmObject {
  private String baz;

  public void setBaz(String baz) {
    this.baz = baz;
  } 

  public String getBaz() {
    return baz;
  }
}

// Abstract class for working with RealmLists
public abstract class RealmListParcelConverter<T extends RealmObject> extends CollectionParcelConverter<T, RealmList<T>> {
    @Override
    public RealmList<T> createCollection() {
        return new RealmList<T>();
    }
}

// Specific class for a RealmList<Bar> property
public class BarListParcelConverter extends RealmListParcelConverter<Bar> {

    @Override
    public void itemToParcel(Bar input, Parcel parcel) {
        parcel.writeParcelable(Parcels.wrap(input), 0);
    }

    @Override
    public Bar itemFromParcel(Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable(Bar.class.getClassLoader()));
    }
}
```

**Comment by johncarl81** [comment]
Sweet.  To reiterate, in the upcoming 1.0.2 `@ParcelProperty("bars")` would not be necessary.
