### ISSUE TITLE
Specify just a few members to be used for parcel

### ISSUE THREAD

**Issue by mlostekk** [johncarl81/parceler#108]
Hello,

first of all great idea! Could make things way easier for me. But just one question.

I have a class that has ~30 members, of which I just need 5 saved/loaded. 

How do I specify this without using 25 times `@Transient`? Somehow I didn't completely get your documentation!

**Comment by johncarl81** [comment]
Parceler follows the configuration by exception pattern.  This means: yes you need to annotate the fields you don't want serialized with `@Transient` or add the `transient` modifier.  This behaves like standard Java serialization.

**Comment by mlostekk** [comment]
Okay, and thanks for the quick response!
