### ISSUE TITLE
Parcels.wrap(List<enum>) errors, but works if wrapped in Class

### ISSUE THREAD

**Issue by twig** [johncarl81/parceler#110]
This took me a while to figure out, but it seems there's a specific case where Enums can/can't work which isn't referenced in the documentation (readme / homepage).

Example Enum:

    public enum ItemType {
        Wand,
        // ...
        Claws,
        Polearms;
    
        public String description = "";

        // For Parceler, if used at all.
        private ItemType() {
            this("");
        }
    
        private ItemType(String description) {
            this.description = description;
        }
    }

For example, this will raise an exception:

    List<ItemType> items = new ArrayList<>();
    items.add(ItemType.Hammers);
    items.add(ItemType.Wand);

    Intent intent = new Intent(getApplicationContext(), ChooseItemsActivity.class);
    intent.putExtra("preselected", Parcels.wrap(items));
    startActivityForResult(intent, ACTIVITY_CHOOSE_ITEMS); // Exception raised here

Stack trace:

    org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for twig.nguyen.d2_runewords.enums.ItemType, verify that your class is configured properly and that the Parcelable class twig.nguyen.d2_runewords.enums.ItemType$$Parcelable is generated by Parceler.
            at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:201)
            at org.parceler.Parcels.wrap(Parcels.java:85)
            at org.parceler.Parcels.wrap(Parcels.java:69)
            at org.parceler.NonParcelRepository$ListParcelable$1.itemToParcel(NonParcelRepository.java:280)
            at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:38)
            at org.parceler.converter.CollectionParcelConverter.toParcel(CollectionParcelConverter.java:27)
            at org.parceler.NonParcelRepository$ConverterParcelable.writeToParcel(NonParcelRepository.java:1222)
            at org.parceler.NonParcelRepository$ListParcelable.writeToParcel(NonParcelRepository.java:269)
            at android.os.Parcel.writeParcelable(Parcel.java:1285)
            at android.os.Parcel.writeValue(Parcel.java:1204)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
            at android.os.Bundle.writeToParcel(Bundle.java:1692)
            at android.os.Parcel.writeBundle(Parcel.java:636)
            at android.content.Intent.writeToParcel(Intent.java:7013)

However, after adding this wrapper class...

    @Parcel
    public class ParcelableEnumList<T extends Enum> {
        public List<T> data;
    
        public ParcelableEnumList(List<T> data) {
            this();
            this.data = data;
        }
    
        public ParcelableEnumList() {}
    }

The following code works just fine.

    Intent intent = new Intent(getApplicationContext(), ChooseItemsActivity.class);
    intent.putExtra("preselected", Parcels.wrap(new ParcelableEnumList(items)));
    startActivityForResult(intent, ACTIVITY_CHOOSE_ITEMS);

I'm not quite sure if this is a bug, because it's partially working so I'd just like to clarify if this is undocumented instruction or unintended use case.

**Comment by twig** [comment]
Forgot to mention, I'm using the following in Android Studio.

    compile "org.parceler:parceler-api:1.0.1"
    provided "org.parceler:parceler:1.0.1" // Replaced 'apt' with 'provided'

**Comment by johncarl81** [comment]
Thanks for reporting this @twig.  This is largely caused because Parceler treats `enum`s as `Serializable` (yes, it falls back to `Serializable` if that is the only type available).  The quick and dirty fix for your case is to annotate `ItemType` with `@Parcel`.  (FYI, the empty constructor isn't necessary for `Serializable`)

The proper fix is to implement an enum specific [ReadWriteGenerator](https://github.com/johncarl81/parceler/blob/master/parceler/src/main/java/org/parceler/internal/generator/ReadWriteGenerator.java).  I think we should just read and write an integer for the enum's ordinal value to the parcel.

Thoughts?

**Comment by twig** [comment]
Hmm, I think I would prefer the enum's name instead of the ordinal in case the number is inconsistent between versions of libraries.

Plus, `Enum.valueOf(Class enumClass, String name)` takes a name rather than ordinal.

**Comment by johncarl81** [comment]
I do prefer to use the enum's name in technologies like Hibernate, where the value potentially lives longer than the code does.

In this case, however, I'm having trouble imagining a scenario that would require the enum's name over the ordinal value.  Maybe if we were bridging between applications or classloaders?

We'll also have to consider enum's mutable state (you declared multiple state in your example by not making it final: `description`).

**Comment by twig** [comment]
Hmm good point about the mutable state, I did not consider that. Using @Parcel would fix that use case.

My main reasoning for preferring name over ordinal is it's already done for you via `Enum.valueOf(EnumClass, String)`. As far as I know, with ordinal you'd have to get `Enum.values()[ordinal]`

Personally not too fussed either way, it's all under the hood for a short lived parcel.

**Comment by johncarl81** [comment]
Looks like the Spec on Java Serialization does not require the serialization of enum fields:

http://docs.oracle.com/javase/8/docs/platform/serialization/spec/serial-arch.html#a6469

This makes the job a bit easier as we would just need to serialize which enum.  I think I'll follow the Spec's (and @twig's) technique of serializing the name of the enum constant.

**Comment by Jogan** [comment]
@johncarl81 not sure if this is related but I just ran into a similar issue when using `Parcels.wrap` on a map that contains an enum. I received the same exception @twig posted. Adding the parceler annotations to the enum resolves the above issue but then I receive ParcelerRuntimeException: `Exception during method injection: NoSuchMethodException <init> []` for the enum class when launching an activity

**Comment by johncarl81** [comment]
Can you give me some more details @Jogan?  Was it an `EnumMap` by chance?  Did you annotate your enum with `@Parcel`?

**Comment by Jogan** [comment]
@johncarl81 Sorry I should have provided a little more detail. 

Its a Map<K,V> where K is the enum and V is a pojo (which is annotated with Parcel).  

When the enum is also annotated with @Parcel calling `wrap`, `unwrap` works fine.  However I then receive:
 ```java
Caused by: org.parceler.ParcelerRuntimeException: Exception during method injection: NoSuchMethodException
            at org.parceler.InjectionUtil.callConstructor
```
 when I have "Dont Keep Activities" enabled in the developer settings and navigate back to a previous activity. The stacktrace shows its related to my enum class.

**Comment by johncarl81** [comment]
Yikes, looks like Parceler is trying to instantiate your enum.  I'll have this feature implemented asap.

**Comment by twig** [comment]
Thanks for looking into it @johncarl81, much appreciated!

**Comment by ireneduke** [comment]
@johncarl81 I've got this issue as well. Any ETA on a fix?

**Comment by johncarl81** [comment]
Hopefully by next week... as always PRs are welcome if someone else wants to take this one!

**Comment by twig** [comment]
I'm comfortable with writing Java/Android libraries but I've got no experience with writing annotation libraries. If you have a helpful starters guide somewhere I'd give it a shot.

**Comment by johncarl81** [comment]
Would you guys like to verify?:
https://jitpack.io/#johncarl81/parceler/48715ffa43
You'll need to use the submodules:
```
compile 'com.github.johncarl81.parceler:parceler-api:48715ffa43'
provided 'com.github.johncarl81.parceler:parceler:48715ffa43'
```

**Comment by twig** [comment]
Added the jitpack.io repository (as instructed in link) and the submodules but it couldn't find the submodules needed to compile it.

    Error:A problem occurred configuring project
    > Could not resolve all dependencies for configuration

   > Could not find com.github.johncarl81.parceler:parceler-api:48715ffa43.
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/johncarl81/parceler/parceler-api/48715ffa43/parceler-api-48715ffa43.pom
         https://jcenter.bintray.com/com/github/johncarl81/parceler/parceler-api/48715ffa43/parceler-api-48715ffa43.jar
         https://jitpack.io/com/github/johncarl81/parceler/parceler-api/48715ffa43/parceler-api-48715ffa43.pom
         https://jitpack.io/com/github/johncarl81/parceler/parceler-api/48715ffa43/parceler-api-48715ffa43.jar
         file:/G:/Android/sdk/extras/android/m2repository/com/github/johncarl81/parceler/parceler-api/48715ffa43/parceler-api-48715ffa43.pom
         file:/G:/Android/sdk/extras/android/m2repository/com/github/johncarl81/parceler/parceler-api/48715ffa43/parceler-api-48715ffa43.jar
         file:/G:/Android/sdk/extras/google/m2repository/com/github/johncarl81/parceler/parceler-api/48715ffa43/parceler-api-48715ffa43.pom
         file:/G:/Android/sdk/extras/google/m2repository/com/github/johncarl81/parceler/parceler-api/48715ffa43/parceler-api-48715ffa43.jar

   > Could not find com.github.johncarl81.parceler:parceler:48715ffa43.
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/johncarl81/parceler/parceler/48715ffa43/parceler-48715ffa43.pom
         https://jcenter.bintray.com/com/github/johncarl81/parceler/parceler/48715ffa43/parceler-48715ffa43.jar
         https://jitpack.io/com/github/johncarl81/parceler/parceler/48715ffa43/parceler-48715ffa43.pom
         https://jitpack.io/com/github/johncarl81/parceler/parceler/48715ffa43/parceler-48715ffa43.jar
         file:/G:/Android/sdk/extras/android/m2repository/com/github/johncarl81/parceler/parceler/48715ffa43/parceler-48715ffa43.pom
         file:/G:/Android/sdk/extras/android/m2repository/com/github/johncarl81/parceler/parceler/48715ffa43/parceler-48715ffa43.jar
         file:/G:/Android/sdk/extras/google/m2repository/com/github/johncarl81/parceler/parceler/48715ffa43/parceler-48715ffa43.pom
         file:/G:/Android/sdk/extras/google/m2repository/com/github/johncarl81/parceler/parceler/48715ffa43/parceler-48715ffa43.jar

**Comment by johncarl81** [comment]
Try the shortened version:
```
compile 'com.github.johncarl81.parceler:parceler-api:48715ff'
provided 'com.github.johncarl81.parceler:parceler:48715ff'
```

**Comment by johncarl81** [comment]
hrmmm... not sure why jitpack is failing... would you care to build the SNAPSHOT directly?

**Comment by Jogan** [comment]
@johncarl81 also unable to find the submodules.

**Comment by johncarl81** [comment]
Shoot, this was working a short time ago.

**Comment by Jogan** [comment]
@johncarl81 any updates? let me know if you want me to try anything

**Comment by johncarl81** [comment]
I'm not sure whats going on with jitpack, but you could build and try it out yourself on the enums branch.

**Comment by Jogan** [comment]
@johncarl81 will do. ill keep you posted

**Comment by twig** [comment]
Hmm still having issues trying to use JitPack. Got any instructions on how to build/use locally?

**Comment by johncarl81** [comment]
Run the following:
```
git clone -b enums git@github.com:johncarl81/parceler.git
cd parceler
mvn clean install
```

Then use the 1.0.2-SNAPSHOT version if your project.

**Comment by twig** [comment]
Just tested it, works beautifully!

**Comment by johncarl81** [comment]
Great, merged this and I should be releasing 1.0.2 shortly.

**Comment by Jogan** [comment]
:+1:

**Comment by twig** [comment]
Thanks John!

**Comment by johncarl81** [comment]
[1.0.2 released](https://twitter.com/attransfuse/status/623293642870927360)
