### ISSUE TITLE
Partial Compilation

### ISSUE THREAD

**Issue by johncarl81** [johncarl81/parceler#111]
With the upcoming Jack and Jill compiler (and recent Eclipse support #30) partial compilation may become more of an issue.  We need to look into how Jack and Jill will handle annotation processing ([if at all](http://tools.android.com/tech-docs/jackandjill)) and provide better support for Eclipse.

Parceler currently uses a transactional system to be able to retry failed work.  This allows Parceler to play nicely with other annotation processors and better handle the `ErrorType`.  This, on its own, would handle partial compilation just fine.  The problem is with chaining transactions.  One or multiple transaction's output could the be the input to another transaction.  This is how the `Parceler$$Parcels` lookup class is generated for the `Parcels` utility.  With partial compilation, a finished transaction may have to be rerun to reprocess a compiled class.  This means any downstream transactions would either need to be rerun or be incomplete.

This brings up a number of questions:
 * Can we overwrite existing source files?
 * Could (Should) we store the state of the previous transaction graph on disk to deserialize it when rerunning work
 * How can we differentiate between full compilation and partial compilation for refreshing the transaction graph?

**Comment by WonderCsabo** [comment]
This is even more relevant due to Gradle and Android incremental compilation support.

**Comment by johncarl81** [comment]
I believe we fully support partial compilation after this PR: #185
