### ISSUE TITLE
Attempt to recreate a file for type org.parceler.Parceler$$Parcels

### ISSUE THREAD

**Issue by lukaspili** [johncarl81/parceler#112]
I'm writing an annotation processor that generates some classes that are annotated with `@Parcel`. No problem so far. In a project that uses this annotation processor, I can also create manually some classes that are annotated with `@Parcel`.

If only the generated classes are annotated with `@Parcel`, it works. And the same if only manually created classes are annotated. But I get the following compilation error when both generated and manually created classes are annotated: `Attempt to recreate a file for type org.parceler.Parceler$$Parcels`

From the README and the issue #89 I understand that the `Parceler$$Parcels` class may be generated several times in case of `@Parcel` classes from several modules / libraries. However in my case, the generated and manually created classes are in the same module.

It works when all my annotated classes declares `@Parcel(parcelsIndex = false)`. 

If this behaviour is expected, could you clarify a bit what are the difference when not using the parceler mapping class? Especially in terms of performance.

Thanks

**Comment by johncarl81** [comment]
Great question.

In general, Parceler gains its speed from avoiding reflection.  Parceler performs all analysis and code generation at compile time to make your wrapped Parcelables as fast as possible.  This concept is extended to the `Parcels` utility class by writing out the `Parceler$$Parcels` mapping class.

Taking a look at the `Parceler$$Parcels` class, it is simply a hash map relating two types, the annotated `@Parcel` class and the factory to create the wrapper class `ParcelableFactory`:

```java
public class Parceler$$Parcels implements Repository<org.parceler.Parcels.ParcelableFactory> {

    private final Map<Class, org.parceler.Parcels.ParcelableFactory> map$$0 = new HashMap<Class, org.parceler.Parcels.ParcelableFactory>();

    public Parceler$$Parcels() {
        map$$0 .put(ManuallyRegistered.class, new Parceler$$Parcels.ManuallyRegistered$$Parcelable$$0());
        map$$0 .put(ExternalParcel.class, new Parceler$$Parcels.ExternalParcel$$Parcelable$$0());
        map$$0 .put(Example.class, new Parceler$$Parcels.Example$$Parcelable$$0());
        map$$0 .put(Manual.class, new Parceler$$Parcels.Manual$$Parcelable$$0());
        map$$0 .put(ExampleParcel.class, new Parceler$$Parcels.ExampleParcel$$Parcelable$$0());
        map$$0 .put(ExampleEnumList.class, new Parceler$$Parcels.ExampleEnumList$$Parcelable$$0());
        map$$0 .put(SubParcel.class, new Parceler$$Parcels.SubParcel$$Parcelable$$0());
    }
   //...
}
```

The `Parcels` utility class [uses reflection](https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/Parcels.java#L237) to look up this class.  After this one reflection call, every call that is made to `Parcels.wrap()` is static code.  This reduces any slowdown from this lookup to near zero.

As a fallback, Parceler does use reflection if a call to wrap is made with a class that doesn't exist in the map.  If it finds one of the generated `Parcelable` classes, then it caches the [class](https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/Parcels.java#L196) and [constructor](https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/Parcels.java#L165) making subsequent calls as fast as possible.

This fallback is used in the case where `parcelsIndex = false`.  In this case a `Parcelable` is written out and compiled, but not added to the `Parceler$$Parcels` class.  If no classes are set to be written out to the `Parceler$$Parcels` class then the class is simply not generated.  This is why setting this parameter to false avoids the `Attempt to recreate...` exception during compile time.

**Comment by johncarl81** [comment]
If you're interested, I wrote a quick and dirty performance benchmark here: https://github.com/johncarl81/parceler/tree/master/examples/performance

**Comment by lukaspili** [comment]
Thanks for the details.
However I still don't understand why all the classes should have `parcelsIndex = false`?
Shouldn't it be only generated classes, or only manually written classes?

As for working with multiple parcels mapping classes, I'm thinking about a scenario where `@Parcel` could specify the name of its mapping class. Like for instance `@Parcel(indexedIn = "ProcessorParcelerMapping")` and `@Parcel(indexedIn = "MyAppParcelerMapping")`. 
Thus, the Parceler utility class would only require to lookup for those 2 mapping classes, rather than each `@Parcel` annotated classes.

On the other hand, it feels a bit like over optimisation. What do you think?

**Comment by johncarl81** [comment]
Im not sure what you mean... only one module's classes should have parcelsIndex = true, everything else should have parcelsIndex = false to avoid the `Attemp to recreate...` exception.

I think, if anything, the move would be to eliminate the `Parceler$$Parcels` mapping class and use a cached reflection lookup for each call to wrap().

**Comment by johncarl81** [comment]
@lukaspili, are you ok to close?
