### ISSUE TITLE
1.0.2 update for Enums doesn't check for null

### ISSUE THREAD

**Issue by twig** [johncarl81/parceler#116]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String twig.nguyen.webportal.data.WebportalDay.name()' on a null object reference

**Comment by johncarl81** [comment]
Shoot... I thought I handled that.  That's what I get for not including an integration test.  ^ This should do the trick.

**Comment by twig** [comment]
Thanks for the quick fix!

Checked out the diff, that preprocessor magic is definitely harder than it looks lol

**Comment by johncarl81** [comment]
Most of that is [JCodeModel](https://codemodel.java.net/).  It's a little tough a first because you're writing code that writes code.  Definitely requires a certain mindset.
