### ISSUE TITLE
Location of generated classes? [Android Studio]

### ISSUE THREAD

**Issue by dkozel** [johncarl81/parceler#118]
I have been using Parceler for about two months now with good success. I don't believe that I've changed anything applicable to Parceler, but have just started encountering this issue:

> org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for com.example.model.Connection, verify that your class is configured properly and that the Parcelable class com.nameloop.nameloop.model.Connection$$Parcelable is generated by Parceler.

```
import com.google.gson.annotations.Expose;
import org.parceler.Parcel;

@Parcel
public class Connection extends Entity {

	@Expose
	public boolean hasOverrides;

	@Expose
	public String contactType;

	@Expose
	public ContactData contactData;
}
```

I do have the appropriate ProGuard lines to prevent the generated class from being eliminated and don't use obfuscation. I think that the class is configured properly, but cannot find the generated class. Any advice? Thanks.

**Comment by johncarl81** [comment]
Did you find a solution @dkozel ?

**Comment by dkozel** [comment]
I git bisected the problem and it started occurring when I included FragmentArgs and Icicle in the project. Interestingly I hadn't even started using them yet so it must be a conflict somewhere in the code generation.

**Comment by dkozel** [comment]
I knew that the libraries don't play well together without some extra work, but didn't think that it would conflict so directly. I've been comparing Auto Parcel, Parceler, and ParcelablePlease. I think ParcelablePlease's approach is less elegant, but pragmatic in that it causes the model class to directly implement `parcelable`.

**Comment by johncarl81** [comment]
Strange.  Parceler is designed to play well with other annotation libraries, so I'm not sure what your problem could be.  Is there some sort of stacktrace or something else concrete you can offer to diagnose the issue?

As for the different approaches, it's certainly up to you to decide which approach is best.  AutoParcel's value objects also implement `Parcelable` and the Parceler wrapper classes implement `Parcelable` as well.

**Comment by dkozel** [comment]
I use the same models with Gson and Parceler. My understanding is that AutoParcel doesn't play well with other annotations. https://github.com/frankiesardo/auto-parcel/issues/6

This article talks about the same type of issues that I've been pondering. http://hannesdorfmann.com/android/ParcelablePlease/

I'd be happy to work with you at some point to debug what's happening. I have the commit singled out and can easily pull it up again.

**Comment by johncarl81** [comment]
I'd be happy to debug... the best thing would be a common project that I could see demonstrating the problem.  Could you share something like this over github or maybe an emailed zip file?

**Comment by dkozel** [comment]
The plot thickens. I just noticed that Parceler has an explicit bundler for classes using parceler...
https://github.com/sockeqwe/fragmentargs/tree/master/bundler-parceler/src/main/java/com/hannesdorfmann/fragmentargs/bundler

I'll produce a minimal project showing the issue and investigating the use of that bundler when I get some time. I still owe you a documentation addition from a previous issue. :)
