### ISSUE TITLE
Convert to byte array?

### ISSUE THREAD

**Issue by johnsintal** [johncarl81/parceler#120]
Hi,

I was wondering if it's possible to convert the wrapped objected into a byte array, send the data over Android Wear's messaging API, receive the byte array data, and unwrap it back to its POJO form?

Thanks!

**Comment by johncarl81** [comment]
Can you point out the specific api you want to use?

**Comment by johnsintal** [comment]
Here it is. I need to serialize my payload from the phone into a byte array, send it over the wire to the werable, and deserialize it.

I am currently using Apache deserialization tools which I suspect is a lot slower than using Parcels.

https://developers.google.com/android/reference/com/google/android/gms/wearable/MessageApi.html#sendMessage(com.google.android.gms.common.api.GoogleApiClient, java.lang.String, java.lang.String, byte[])

**Comment by johncarl81** [comment]
If you want to use the `Parcel` to marshal your beans via `byte[]` you can use the [marshal()](http://developer.android.com/reference/android/os/Parcel.html#marshall%28%29) and [unmarshall()](http://developer.android.com/reference/android/os/Parcel.html#unmarshall%28byte[],%20int,%20int%29) methods.  Here's a SO post with some details: http://stackoverflow.com/questions/18000093/how-to-marshall-and-unmarshall-a-parcelable-to-a-byte-array-with-help-of-parcel

**Comment by johnsintal** [comment]
Thanks @johncarl81 , I did see that post and tried using it, but failed to figure it out.

Gow do use the `public static <T> T unmarshall(byte[] bytes, Parcelable.Creator<T> creator) ` method if I don't have access to my custom object's `Creator`?

Thanks!

**Comment by johncarl81** [comment]
You can reference the generated code, giving you access to the generated CREATOR field.  It would probably look like the following:

    ParcelableUtil.unmarshall(bytes, MyClass$$Parcelable.CREATOR)

**Comment by johnsintal** [comment]
Oh okay, that's very useful info. I will try that approach tonight. Thanks :)
