### ISSUE TITLE
Make CREATOR methods public

### ISSUE THREAD

**Issue by RomainPiel** [johncarl81/parceler#122]
First of all, thanks a lot for this library it's really helpful.
There is something that I'm missing from Parceler, it's really hard to unit test the generated parcelables. Say that you want to test that the unmarshalled version of your model is the same as the one you provided:
```java
@Test
public void testSerialization() {
    Page page = new Page(1);
    Parcelable parcelable = Parcels.wrap(page);

    Parcel parcel = Parcel.obtain();
    parcelable.writeToParcel(parcel, 0);

    parcel.setDataPosition(0);

    Page$$Parcelable createdFromParcel = Page$$Parcelable.CREATOR.createFromParcel(parcel);
    assertThat(Parcels.unwrap(createdFromParcel)).isEqualTo(parcelable);
}
```

This code is not compilable with Parceler. The problem is that `CREATOR.createFromParcel()` is not public.
I understand why we want to close down accesses as much as possible but we should be able to make these kinds of tests and usually a `CREATOR` doesn't hide its implementations.

**Comment by johncarl81** [comment]
The generated `CREATOR` field is public (per the [documentation](http://developer.android.com/reference/android/os/Parcelable.Creator.html)).  Here's the code that generates it: https://github.com/johncarl81/parceler/blob/master/parceler/src/main/java/org/parceler/internal/ParcelableGenerator.java#L144

Note:
```java
parcelableClass.field(JMod.PUBLIC ..., CREATOR_CLASS_NAME, JExpr._new(creatorClass));
```

I've "unit" tested (really I think this is an integration test) beans in Parceler using Robolectric and marshalling / unmarshalling through an `android.so.Parcel` class as well, as you are.  See [`ParcelsTestUtil`](https://github.com/johncarl81/parceler/blob/master/examples/test/src/test/java/org/parceler/ParcelsTestUtil.java) For details.

**Comment by johncarl81** [comment]
It seems the method is public but the Creator inner class is not...  This should do the trick: #123

**Comment by RomainPiel** [comment]
Ha awesome, thanks!

**Comment by johncarl81** [comment]
I'll deploy this with some other fixes shortly.
