### ISSUE TITLE
complex parceled classes in Intent used for startActivityForResult causes memory leak?

### ISSUE THREAD

**Issue by mlostekk** [johncarl81/parceler#125]
Hello There,

I am using your library and having a memory leak with a class i am parcelling and passing as argument to an Intent which is used for startActivityWithResult.

If i am not using

`this.setIntent(null)`

after getting the Intent passed from the other Activity and unwraping the stuff, I will get a memory leak.

Am I doing something wrong or is this a bug?

**Comment by johncarl81** [comment]
Can you share your `@Parcel` implementation or some more details?  Are you finding this memory leak via Leak Canary?

**Comment by mlostekk** [comment]
Nope I am not finding the leak via LeakCanary. But let me doublecheck my code first. I have a bad gutfeeling regarding some areas in the app. Will verify it and get back to you

**Comment by johncarl81** [comment]
I'm going to close this.  Feel free to reopen if you have some concrete details.

**Comment by mlostekk** [comment]
well, it was related to the fact that an Android parcel is not always really "parcelled"... and I had a big object which had references to views and context, and it was passed as a whole object, and not "parcelled" and "unparcelled"...
