### ISSUE TITLE
Type java.util.List<X> of field X is not supported

### ISSUE THREAD

**Issue by alirezaaa** [johncarl81/parceler#127]
Hi,

I'm getting following error. How can I solve this?

` Type java.util.List<X> of field X is not supported `

**Note:** All my classes extend `RealmObject`.

**Comment by johncarl81** [comment]
Lists of `@Parcel` annotated objects are absolutely supported.  Is X annotated with `@Parcel`, with the proper [Realm configuration](https://realm.io/docs/java/latest/#parceler)?

**Comment by alirezaaa** [comment]
Thanks for your answer. I found that the problem was from another thing. Sorry for reporting this.
