### ISSUE TITLE
Was it deleted by another thread?

### ISSUE THREAD

**Issue by slidenerd** [johncarl81/parceler#129]
Hello John, first of all awesome work with the Parceler library, I am trying to use it with Realm and I have ran into an issue and it has something to do with the Parceler's generated classes.

I have a JSON feed that looks like this

![snap 2015-09-19 at 14 47 48](https://cloud.githubusercontent.com/assets/5139030/9975557/72b9e854-5edd-11e5-9253-ef78e153c2ac.png)

My model classes to fetch and store data from JSON with RealmObject look like this
Admin.java
![snap 2015-09-19 at 14 50 35](https://cloud.githubusercontent.com/assets/5139030/9975595/c94bb764-5ede-11e5-8e71-2e7326b5d79a.png)

Picture.java
![snap 2015-09-19 at 14 51 30](https://cloud.githubusercontent.com/assets/5139030/9975572/f9bc22cc-5edd-11e5-979b-8b9e36f5f050.png)

PictureData.java
![snap 2015-09-19 at 14 52 33](https://cloud.githubusercontent.com/assets/5139030/9975574/154b8d84-5ede-11e5-933a-0ffd7416a059.png)

the first time my activity runs, I load it from JSON and store it in Realm, after rotation I try to get data from a Parcelable with the Parceler library but a subsequent time I am getting a crash that looks like this
![testgif](https://cloud.githubusercontent.com/assets/5139030/9975591/85ca121a-5ede-11e5-849f-c3573e3e48b2.gif)

I am not deleting anything any part of the admin data anywhere, however I get an exception stating null in my debug as shown above. Am I missing something? Thanks for your response in advance, I ll work in the meanwhile on my end to see if I can fix this

This is all the code I am using to store my JSON object that looks exactly like what you see in the 1st screenshot
public static void storeAdmin(Context context, Realm realm, JSONObject jsonObject) {
        realm.beginTransaction();
        realm.createOrUpdateObjectFromJson(Admin.class, jsonObject);
        realm.commitTransaction();
    }

and this is how I load it from Realm
![snap 2015-09-19 at 15 01 25](https://cloud.githubusercontent.com/assets/5139030/9975608/5b6bf17c-5edf-11e5-9989-2edf2c7a48d2.png)

I do see the data after exporting the file to RealmBrowser
![testgif](https://cloud.githubusercontent.com/assets/5139030/9975629/194d4452-5ee0-11e5-9e7d-5ae37c2dfe32.gif)

UPDATE 1
The problem seems to be with the Picture class and its data, I commented out the whole part of having a picture, and there were no issues whatsoever

UPDATE 2
I think I have narrowed down the problem

Picture object is invalid when loading from Parceler, am I missing something?
![snap 2015-09-19 at 21 02 28](https://cloud.githubusercontent.com/assets/5139030/9976920/d5b4c3f0-5f11-11e5-9403-b0befbd5617a.png)

This is how I save items before rotation
![Uploading Snap 2015-09-19 at 21.07.21.png…]()

**Comment by johncarl81** [comment]
Maybe one of the Realm guys can help out here...  I'd guess that the `PictureData` object embedded in the `Picture` class is deserialized without a `RealmProxy`.  Is there a way to wrap an object with a `RealmProxy`?

This is similar to what is required by `RealmList`: https://gist.github.com/cmelchior/72c35fcb55cec33a71e1

**Comment by johncarl81** [comment]
FYI @cmelchior

**Comment by slidenerd** [comment]
Thanks,for the input @johncarl81  I ll try to write a parcel converter and see if it would work , today kinda tired :) after a long day of debugging, if things are solved, i ll post the fix and close this issue

**Comment by slidenerd** [comment]
![snap 2015-09-20 at 15 29 00](https://cloud.githubusercontent.com/assets/5139030/9980183/5e06ba84-5fac-11e5-91e3-d272aebbd1cb.png)
I fixed the crash by writing this code, it seems that Realm doesnt read nested objects while reading them and yes, you were right , its a Realm issue, I made my own ParcelConverter just to test stuff, thanks for the assistance, closing the issue now :)
