### ISSUE TITLE
Transient keyword

### ISSUE THREAD

**Issue by ansman** [johncarl81/parceler#131]
I'm using the `transient` keyword with my objects because that's how gson works but to my surprise it worked with Parceler too. Is this officially supported or is it by accident?

I'm just wondering if I should still use the `@Transient` annotation or if I can rely on the keyword alone.

**Comment by johncarl81** [comment]
Yep, it's supported https://github.com/johncarl81/parceler/blob/master/parceler/src/main/java/org/parceler/internal/ParcelableAnalysis.java#L413.  I also added it to the documentation to be a little more clear.

**Comment by ansman** [comment]
Perfect, that is exactly what I wanted to hear :)
Thanks
