### ISSUE TITLE
"Callback" after unwrapped

### ISSUE THREAD

**Issue by ansman** [johncarl81/parceler#132]
I have a bunch of transient fields that I would like to ensure is up to date after the object has been unwrapped.

What would be the preferred way of doing this?

Here an example that illustrated the problem
```java
@Parcel
public class SomeObject {
    private ArrayList<Integer> numbers;
    private transient int evenCount;

    @ParcelConstructor
    SomeObject() {}

    public SomeObject(Collection<Integer> numbers) {
        this.numbers = new ArrayList<>(numbers);
        evenCount = 0;
        for (Integer number : this.numbers) {
            if (number % 2 == 0) {
                ++evenCount;
            }
        }
    }
}
```

**Comment by johncarl81** [comment]
That's not a bad idea... kindof like what SimpleXML does with the [`@Commit`](http://simple.sourceforge.net/download/stream/doc/javadoc/org/simpleframework/xml/core/Complete.html) and [`@Persist`](http://simple.sourceforge.net/download/stream/doc/javadoc/org/simpleframework/xml/core/Persist.html) callbacks: http://simple.sourceforge.net/download/stream/doc/tutorial/tutorial.php

**Comment by johncarl81** [comment]
What do you think @ansman: https://github.com/johncarl81/parceler/pull/149

**Comment by ansman** [comment]
Awesome!
