### ISSUE TITLE
Using features of @Parcel with @ParcelClass

### ISSUE THREAD

**Issue by ultraon** [johncarl81/parceler#133]
Hello. I very like your library, it's very helpful. My Project has some modules, and i want use Parcels lib for POJO objects in different modules (libraries & application). For now i use @ParcelClasses approach.
Could you please tell me, how can i use different params for @Parcel annotation for @ParcelClass approach?

**Comment by johncarl81** [comment]
You can specify `@Parcel` with the `@ParcelClass`:

```java
@ParcelClass(value=LibraryParcel.class, annotation=@Parcel(BEAN))
```

**Comment by ultraon** [comment]
Great, thank you very much! Wish you luck!

**Comment by ultraon** [comment]
Also could you please tell me, what is the difference between Serialization.VALUE vs Serialization.BEAN?

**Comment by johncarl81** [comment]
If [the javadocs](https://oss.sonatype.org/service/local/repositories/releases/archive/org/parceler/parceler-api/1.0.3/parceler-api-1.0.3-javadoc.jar/!/org/parceler/Parcel.Serialization.html#VALUEl) aren't clear, `VALUE` is very similar to `BEAN`.  `BEAN` serializes using the Java Bean standard, where it recognizes public getter/setter pairs as properties.  `VALUE` recognizes simply recognizes paired methods:

`BEAN`:
```java
@Parcel(BEAN)
public class Example {
    public void setValue(String value){}
    public String getValue(){}
}
```
`VALUE`:
```java
@Parcel(BEAN)
public class Example {
    public void value(String value){}
    public String value(){}
}
```

**Comment by ultraon** [comment]
Understand you, thanks. In your snippet there is misspell in 'VALUE' section, i think it should be '@Parcel(VALUE)'. Am I right?

**Comment by johncarl81** [comment]
Oops, yes you're correct.  Updated comment.
