### ISSUE TITLE
Register parcel converter at runtime

### ISSUE THREAD

**Issue by ansman** [johncarl81/parceler#134]
Is there a reason parcel converters cannot be registered at runtime?
It's quite tedious to have to annotate every field that is affected, I would rather do it once in the setup phase of my application.

**Comment by johncarl81** [comment]
I assume you mean "in bulk"... you could register a converter to either a bean annotated with `@Parcel` or an external library bean via `@ParcelClass`.  Parceler will use that converter whenever that class is used:

```java
@Parcel(converter = SomeConverter.class)
public class Example{}

@ParcelClass(value = Example, annotation = @Parcel(converter = SomeConverter.class))
public class SomeOtherClass{}
```

**Comment by ansman** [comment]
So I'm trying to create a create a converter for a joda time class.

So something like this would work?
```java
@ParcelClass(value=DateTime, annotation=@Parcel(converter=DateTimeParcelConverter.class))
public class MyApplication extends Application {
    ...
}
```

**Comment by johncarl81** [comment]
More of less that should do it... let me know if it doesn't work of course.

**Comment by ansman** [comment]
Worked like a charm, though I put the annotation on the parcel converter call itself

**Comment by johncarl81** [comment]
Anywhere works... I like the succinctness of putting it on the converter.  I should add this tip to the docs.
