### ISSUE TITLE
Support for SimpleArrayMap and ArrayMap

### ISSUE THREAD

**Issue by ansman** [johncarl81/parceler#135]
https://developer.android.com/reference/android/support/v4/util/SimpleArrayMap.html
https://developer.android.com/reference/android/support/v4/util/ArrayMap.html

These types are really useful when working with a memory heavy app.

**Comment by johncarl81** [comment]
These should be relatively simple to add ([here](https://github.com/johncarl81/parceler/blob/master/parceler/src/main/java/org/parceler/internal/ParcelerModule.java#L248) and [here](https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/NonParcelRepository.java#L42-L43)), would you like to make a PR?

**Comment by ansman** [comment]
Absolutely.

BTW, if I read the code correctly if I have this: `Map<Foo, Bar> foo = new ArrayMap<>()` it will deserialized as a `HashMap`, is there a way around this currently?
The only way I can think of is writing some value before the map which tells it which type it should use.

**Comment by ansman** [comment]
Also, I'm guessing we should use the support version of ArrayMap since it was introduced in API 19, is there anything I need to think about?

**Comment by johncarl81** [comment]
If we can, I'd prefer to not introduce the support library as a dependency.  This may make things tricky as we wouldn't be able to reference the classes mentioned directly.  What you can do, however, is use string constants to represent the classes both to match the class and to generate code around the class.

Thinking about this more, are you wanting an easy way to register these types as collections in Parceler?  I believe the `@ParcelClass` approach we discussed in #134 would work here as well.

**Comment by ansman** [comment]
You mean just doing `Parcel.wrap()` for each key and value? I guess that would work

**Comment by johncarl81** [comment]
Reviewing this again, I'm happy with the existing solution to declare the `@ParcelClass` manually.  Will close soon unless this doesn't solve the problem.

**Comment by consp1racy** [comment]
I use this and it works fine. https://github.com/consp1racy/android-commons/blob/master/android/src/main/java/net/xpece/android/util/SimpleArrayMapConverter.java

**Comment by johncarl81** [comment]
:+1: @consp1racy
