### ISSUE TITLE
Parceler with RealmList throwing ParcelerRuntimeException!

### ISSUE THREAD

**Issue by skptl** [johncarl81/parceler#136]
I am getting the following ParcelerRuntimeException, when using *Parcels.wrap(models)*, where models is a RealmList<Model>.

**org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for io.realm.RealmList, verify that your class is configured properly and that the Parcelable class io.realm.RealmList$$Parcelable is generated by Parceler**.

When RealmList<Model> is used inside other models with @ParcelPropertyConverter(ModelListParcelConverter.class), everything works.

    @Parcel(implementations = {ModelRealmProxy.class}, value = Parcel.Serialization.BEAN, analyze = {Model.class})
    public class Model extends RealmObject { 
    ...
    }

    public class ModelListParcelConverter extends RealmListParcelConverter<Model> {
        @Override
        public void itemToParcel(Model input, Parcel parcel) {
            parcel.writeParcelable(Parcels.wrap(input), 0);
        }

        @Override
        public Model itemFromParcel(Parcel parcel) {
            return Parcels.unwrap(parcel.readParcelable(Model.class.getClassLoader()));
        }
    }

    public abstract class RealmListParcelConverter<T extends RealmObject> extends CollectionParcelConverter<T, RealmList<T>> {
        @Override
        public RealmList<T> createCollection() {
            return new RealmList<T>();
        }
    }

**Comment by johncarl81** [comment]
In order to handle RealmList as a Parcelable you will need to identify it to Parceler through the `@ParcelClass` annotation with your Converter:

```java
@ParcelClass(value = RealmList.class, annotation = @Parcel(converter = RealmListParcelConverter.class))
public class ExampleApplication ... {}
```

Let me know if this works for you.*

**Forgive me if this doesn't work OOTB, I didn't try it before posting*

**Comment by skptl** [comment]
Thanks @johncarl81 for the quick response.

I tried doing it the way you told me but **`@Parcel`** converter expects a **`Class<? extends ParcelConverter>`** and I have a **`RealmListParcelConverter<T extends RealmObject> extends CollectionParcelConverter<T, RealmList<T>>`**

Is there anything else that I can try?

**Comment by johncarl81** [comment]
Shoot, looks like `@Parcel`'s converter doesn't take the correct base interface.  I'll fix this.

**Comment by johncarl81** [comment]
This should do the trick: ad5f06958b0ffcd3e0ed97fd5b0c378d762669fe.  I'll probably release 1.0.4 soon with this change.

**Comment by skptl** [comment]
Thanks, that was what I was expecting to change. Any estimate on when would it be released, just a vague estimate?

**Comment by johncarl81** [comment]
I could release this evening.

**Comment by skptl** [comment]
Awesome, please leave a comment when done. I appreciate your quick action. Thanks.

**Comment by johncarl81** [comment]
Ok, 1.0.4 should be heading up to central now.

**Comment by skptl** [comment]
Thanks, John!

**Comment by johncarl81** [comment]
@skptl, did this work for you?

**Comment by skptl** [comment]
@johncarl81 It worked like a charm, thanks! I am closing the issue for now.
