### ISSUE TITLE
Allow setting an instance creator for the built in types

### ISSUE THREAD

**Issue by ansman** [johncarl81/parceler#140]
I would like to use `ArrayMap` instead of `HashMap` as default but besides creating a parcel converter for each field I don't see any way of doing this.

**Comment by johncarl81** [comment]
You could create a global configuration using the `@ParcelClass`:

```java
@ParcelClass(value = ArrayMap.class, converter = ArrayMapConverter.class)
class SomeClass{}
```

Then, every time an `ArrayMap` is found in an `@Parcel` class, `ArrayMapConverter` would be used to serialize it.

**Comment by ansman** [comment]
I don't like defining a specific implementation of a map in my classes but I guess that is one workaround

**Comment by johncarl81** [comment]
Related: #134 #135
