### ISSUE TITLE
can you tell the latest version of the following dependencies?

### ISSUE THREAD

**Issue by caixuejian** [johncarl81/parceler#141]
compile "org.parceler:parceler-api:${parcelerVersion}"
apt "org.parceler:parceler:${parcelerVersion}"

I suggest :
you can replace the following dependencies 
compile "org.parceler:parceler-api:${parcelerVersion}"
apt "org.parceler:parceler:${parcelerVersion}"
with 
compile "org.parceler:parceler-api:1.0.0"
apt "org.parceler:parceler:1.0.0

**Comment by johncarl81** [comment]
I'm cool with that... it actually matches the website (http://parceler.org/#getting_parceler).  Would you care to make a PR?

**Comment by johncarl81** [comment]
#148
