### ISSUE TITLE
Can I use this in kotlin

### ISSUE THREAD

**Issue by progfiles** [johncarl81/parceler#144]
I tried this:

```java
@Parcel(implementations = arrayOf(test::class), 
    value = Parcel.Serialization.BEAN, 
    analyze = arrayOf(test::class))
open class test{
   open val name=""
}
```

But it does not work :frowning:

**Comment by johncarl81** [comment]
I have to admit, I havent spent much time on Kotlin, but I saw this post on Stackoverflow that looks similar, maybe you can model  your class after it:

http://stackoverflow.com/a/33892435/654187

**Comment by progfiles** [comment]
Sorry but it not work to

**Comment by johncarl81** [comment]
Try asking your question on Stackoverflow as it will reach people with expertise in Kotlin: http://stackoverflow.com/questions/ask?tags=parceler+kotlin .  Feel free to link your question here if and when you post.

**Comment by dawidhyzy** [comment]
I have the same issue. I found only one post on stackoverflow: http://stackoverflow.com/questions/38910246/kotlin-realm-and-parcel

**Comment by johncarl81** [comment]
@dawidhyzy it looks like the issue you've referenced has to do with accessing the class statically at compile time.  Can you give me a concrete example that I can help you with?

**Comment by dawidhyzy** [comment]
It was my mistake. I should use kapt instead off apt.
I've created simple test if anyone have same issue: https://github.com/dawidhyzy/kotlin-sample/tree/parceler_realm

**Comment by johncarl81** [comment]
Ah, easy mistake.  If you're interested I'd like to add a Kotlin example to the project examples, would you care to expand the simple test program you have and pull it in?

**Comment by dawidhyzy** [comment]
Sorry for the long response but I was on vacation. Yes, of course, I will
do that.

wt., 4.10.2016 o 18:56 użytkownik John Ericksen <notifications@github.com>
napisał:

**Comment by ArtworkAD** [comment]
https://github.com/grandstaish/paperparcel
