### ISSUE TITLE
CREATOR field renamed by proguard in NonParcelRepository$ListParcelable

### ISSUE THREAD

**Issue by jskierbi** [johncarl81/parceler#146]
I have an issue with wrapping/unwrapping List when using proguard with exception:  
```
android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called  CREATOR on class org.parceler.NonParcelRepository$ListParcelable
```

I found out that proguard renames CREATOR fields in all inner classes of ```NonParcelRepository```

This is due to fact that by default CREATOR is kept only in classes that directly implements Parcelable interface, whereas in ```NonParcelRepository``` this is implemented indirectly via base class ```ConverterParcelable```

There are 2 possible solutions:

1. All inner parcelable classes of ```NonParcelRepository``` should implement Parcelable directly, this way no additional proguard rules are needed.
2. Additional proguard rule: 
```
-keepnames class * extends org.parceler.NonParcelRepository$ConverterParcelable {
    public static final ** CREATOR;
}
```

**Comment by johncarl81** [comment]
Good catch.  Could you share your full proguard ruleset?

**Comment by jskierbi** [comment]
Here is full ruleset:

```
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}

-keep class org.parceler.Parceler$$Parcels
-keep interface org.parceler.Parcel
-keep @org.parceler.Parcel class * { *; }
-keep class **$$Parcelable { *; }
-keepnames class * extends org.parceler.NonParcelRepository$ConverterParcelable {
    public static final ** CREATOR;
}
```

**Comment by johncarl81** [comment]
I'm updating the website and README with the following configuration:
```
-keep class **$$Parcelable { *; }
```
Please reopen if this is not enough.
