### ISSUE TITLE
Make Parcels.wrap support the built in types

### ISSUE THREAD

**Issue by ansman** [johncarl81/parceler#147]
It would be nice if this would work: `Parcels.wrap("foo")`, currently `Parcels.wrap` only looks in the user generated parcelables.

**Comment by johncarl81** [comment]
Parceler handles the following built in types directly: https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/NonParcelRepository.java#L35-L63  `String` is one of them.

`Parcelable stringParcelable = Parcels.wrap("foo")` builds a `StringParcelable`, and `String output = Parcels.unwrap(stringParcelable)` should return the given `"foo"` string.

Here's the unit test that validates the `String` case: https://github.com/johncarl81/parceler/blob/master/examples/test/src/test/java/org/parceler/NonParcelTest.java#L356-L363

**Comment by ansman** [comment]
Hmm, my bad. Not sure why but I think I had experienced crash but I guess not.
