### ISSUE TITLE
ADTs with Parceler.

### ISSUE THREAD

**Issue by pepyakin** [johncarl81/parceler#153]
I'm using [ADT](https://en.wikipedia.org/wiki/Algebraic_data_type) to model my state in Android application written in Kotlin. 
It looks like following:

``` kotlin
@Parcel(
  converter = StageParcelConverter::class,
  implementations = arrayOf(
    Stage.Landing::class,
    Stage.Identification::class,
    Stage.PinVerification::class)
  )
interface Stage {
  object Landing
  object Identification
  data class PinVerification(identificationResult: IdentificationResult)
}
```

It works well if I just wrap/unwrap instances of this type. 
But when I use fields with `Stage` type in another Parcel'ed class like:

``` java
@Parcel
final class PinVerificationOps {
  final Stage.PinVerification pinVerificationStage;

  @ParcelConsturctor
  public PinVerificationOps(Stage.PinVerification pinVerificationStage) {
    this.pinVerificationStage = pinVerificationStage; 
  }

  // Code that makes sense only in PinVerification stage.
}
```

But Parceler complains:

```
error: Parceler: Unable to find read/write generator for type Stage.PinVerification for Stage$PinVerification pinVerificationStage
    public PinVerificationOps(Stage.PinVerification pinVerificationStage)
```

It looks strange to me because I don't understand what preventing Parceler to see `Stage.PinVerification` as `Stage` and use `StageParcelConverter` for it.

**Comment by johncarl81** [comment]
Hmm, yeah, it looks like Parceler should behave as you described.  I'm no an expert on Kotlin, could you share an example application that I can tinker with?

**Comment by pepyakin** [comment]
No problem, I made a Java example for you. 
https://github.com/pepyakin/adt-parceler

**Comment by johncarl81** [comment]
Oh, sweet, let me take a look then...

**Comment by johncarl81** [comment]
Maybe this is a shortcoming of Parceler at the moment, but the `implmentations` parameter is not used during code generation to map types to a given converter.  I think we could add that.

Looking at your example, it looks like you are working against Parceler, instead could you use something like the following without the need for a converter:

```java
public interface Stage {

    @Parcel class Identification implements Stage {
        static final Identification INSTANCE = new Identification();
    }

    @Parcel class PinVerification implements Stage {
        final String derp;

        @ParcelConstructor public PinVerification(String derp) {
            this.derp = derp;
        }
    }
}
```
This would solve a few problems with your approach.

**Comment by pepyakin** [comment]
Yep, it might look like in Java, however in Kotlin there is few problems with Parceler:

* Data classes are still problem, even with Bean serialization ("No corresponding property found for constructor parameter arg0", probably kapt problem).
* [Kotlin] Objects cannot be created, because have no public constructors.

I think there are workarounds for these problems, e.g use `@ParcelFactory` for objects, but they oblige to clutter model definition. I prefer to keep definition clean and have seperate `StageParcelConverter`.

**Comment by johncarl81** [comment]
Relevant discussion on the first point: https://github.com/johncarl81/parceler/issues/143 TLDR: You may use `@ParcelProperty` to specify the constructor parameter names.
Not sure what yo mean by the second point, but Parceler can handle non-public constructors

I was thinking about alternatives to this further.  If you want to specify your converter on those classes the proper way to do so is the following:
```java
@ParcelClasses(
        @ParcelClass(value = Stage.Identification.class, @Parcel(converter = StageParcelConverter.class)),
        @ParcelClass(value = Stage.PinVerification.class, @Parcel(converter = StageParcelConverter.class))
)
public interface Stage {
    class Identification implements Stage {
        static final Identification INSTANCE = new Identification();
    }

    class PinVerification implements Stage {
        final String derp;

        public PinVerification(String derp) {
            this.derp = derp;
        }
    }
}
```

**Comment by pepyakin** [comment]
Sorry, in second point I mean not the lack of the public constructor, but the fact why there is no public constructor — kotlin object is a singleton. 

> I was thinking about alternatives to this further. If you want to specify your converter on those classes the proper way to do so is the following:

It works. However, I experimented even further and tried to keep single converter. 
```kotlin
class StageParcelConverter: ParcelConverter<Stage> {
    private fun Stage.ordinal(): Int = when (this) {
        is Stage.Identification -> 0
        is Stage.PinVerification -> 1
        else -> TODO()
    }

    override fun toParcel(input: Stage, parcel: Parcel) {
        val ordinal = input.ordinal()
        parcel.writeInt(ordinal)
        when (input) {
            is Stage.Identification -> { }
            is Stage.PinVerification -> {
                // ...
            }
        }
    }

    override fun fromParcel(parcel: Parcel): Stage? {
        val ordinal = parcel.readInt()
        return when (ordinal) {
            0 -> Stage.Identification
            1 -> {
                val derp = parcel.readString()
                Stage.PinVerification(identificationResult)
            }
            else -> TODO()
        }
    }
}
```

Parceler succeeds but produces code that is not compiling.

```java
@Generated(value = "org.parceler.ParcelAnnotationProcessor", date = "2016-01-22T20:02+0400")
@SuppressWarnings({
    "unchecked",
    "deprecation"
})
public class Stage$PinVerification$$Parcelable
    implements Parcelable, ParcelWrapper<PinVerification>
{

    private PinVerification pinVerification$$0;
    @SuppressWarnings("UnusedDeclaration")
    public final static Stage$PinVerification$$Parcelable.Creator$$0 CREATOR = new Stage$PinVerification$$Parcelable.Creator$$0();

    public Stage$PinVerification$$Parcelable(android.os.Parcel parcel$$0) {
        pinVerification$$0 = new com.wheely.app.ui.onboarding.presenter.StageParcelConverter().fromParcel(parcel$$0);
        // ^^^ compile error: Incompatible types: Found: Stage Required: PinVerification
    }
}
```

**Comment by johncarl81** [comment]
This is due to a type coercion detail around generics that I haven't implemented.  A cast should be added in this spot ([Here's the code that should perform that](https://github.com/johncarl81/transfuse/blob/master/transfuse-core/src/main/java/org/androidtransfuse/gen/invocationBuilder/TypeInvocationHelper.java#L59))
