### ISSUE TITLE
No args constructor generation with @Parcel

### ISSUE THREAD

**Issue by MarcinOrlowski** [johncarl81/parceler#155]
In [Serialization techniques](https://github.com/johncarl81/parceler#serialization-techniques) docs we read

>  If an empty constructor is present, Parceler will use that constructor unless another constructor is annotated.

But problem arises when there's other (args) constructor already present but is not annotated with `@ParcelConstructor` and there's no no args constructor. Would it be possible to make `@Parcel` automatically generate such default dummy constructor?

**Comment by johncarl81** [comment]
Unfortunately, no, that's not possible with JSR 269.
