### ISSUE TITLE
Reduce the number of methods generated

### ISSUE THREAD

**Issue by ansman** [johncarl81/parceler#157]
It seems like Parceler generates a lot of methods when having nested objects. It would be preferable if most or at least some of these could be inlined.
The reasoning is that the application I'm developing is not hitting the 65k method limit and Parceler seems to take out a significant portion of this.

**Comment by johncarl81** [comment]
Do you have a count of the number of methods Parceler generates in your use case (total count / # of annotated `@Parcel` beans)?  I've been especially cautious around this issue.  For instance, the Parceler API has around 500 methods total.

**Comment by ansman** [comment]
Ok, here's an example.

I have this class `Root` which looks like this:
```java
@Parcel
public class Root {
    public A a;
    public B b;
    public C c;
}
```

`A`, `B` and `C` all look the same:
```java
@Parcel
public class A {
    public String someString;
    public int someInt;
}
```

`Root$Parcelable` now look like this:
```java
@Generated(value = "org.parceler.ParcelAnnotationProcessor", date = "2016-02-22T10:12+0100")
@SuppressWarnings("unchecked")
public class Root$$Parcelable
    implements Parcelable, ParcelWrapper<com.bontouch.parcelermethods.Root>
{

    private com.bontouch.parcelermethods.Root root$$0;
    @SuppressWarnings("UnusedDeclaration")
    public final static Root$$Parcelable.Creator$$3 CREATOR = new Root$$Parcelable.Creator$$3();

    public Root$$Parcelable(android.os.Parcel parcel$$15) {
        com.bontouch.parcelermethods.Root root$$2;
        if (parcel$$15 .readInt() == -1) {
            root$$2 = null;
        } else {
            root$$2 = readcom_bontouch_parcelermethods_Root(parcel$$15);
        }
        root$$0 = root$$2;
    }

    public Root$$Parcelable(com.bontouch.parcelermethods.Root root$$4) {
        root$$0 = root$$4;
    }

    @Override
    public void writeToParcel(android.os.Parcel parcel$$16, int flags) {
        if (root$$0 == null) {
            parcel$$16 .writeInt(-1);
        } else {
            parcel$$16 .writeInt(1);
            writecom_bontouch_parcelermethods_Root(root$$0, parcel$$16, flags);
        }
    }

    private com.bontouch.parcelermethods.Root readcom_bontouch_parcelermethods_Root(android.os.Parcel parcel$$17) {
        com.bontouch.parcelermethods.Root root$$1;
        root$$1 = new com.bontouch.parcelermethods.Root();
        com.bontouch.parcelermethods.A a$$6;
        if (parcel$$17 .readInt() == -1) {
            a$$6 = null;
        } else {
            a$$6 = readcom_bontouch_parcelermethods_A(parcel$$17);
        }
        root$$1 .a = a$$6;
        com.bontouch.parcelermethods.B b$$6;
        if (parcel$$17 .readInt() == -1) {
            b$$6 = null;
        } else {
            b$$6 = readcom_bontouch_parcelermethods_B(parcel$$17);
        }
        root$$1 .b = b$$6;
        com.bontouch.parcelermethods.C c$$6;
        if (parcel$$17 .readInt() == -1) {
            c$$6 = null;
        } else {
            c$$6 = readcom_bontouch_parcelermethods_C(parcel$$17);
        }
        root$$1 .c = c$$6;
        return root$$1;
    }

    private com.bontouch.parcelermethods.A readcom_bontouch_parcelermethods_A(android.os.Parcel parcel$$18) {
        com.bontouch.parcelermethods.A a$$5;
        a$$5 = new com.bontouch.parcelermethods.A();
        a$$5 .someString = parcel$$18 .readString();
        a$$5 .someInt = parcel$$18 .readInt();
        return a$$5;
    }

    private com.bontouch.parcelermethods.B readcom_bontouch_parcelermethods_B(android.os.Parcel parcel$$19) {
        com.bontouch.parcelermethods.B b$$5;
        b$$5 = new com.bontouch.parcelermethods.B();
        b$$5 .someString = parcel$$19 .readString();
        b$$5 .someInt = parcel$$19 .readInt();
        return b$$5;
    }

    private com.bontouch.parcelermethods.C readcom_bontouch_parcelermethods_C(android.os.Parcel parcel$$20) {
        com.bontouch.parcelermethods.C c$$5;
        c$$5 = new com.bontouch.parcelermethods.C();
        c$$5 .someString = parcel$$20 .readString();
        c$$5 .someInt = parcel$$20 .readInt();
        return c$$5;
    }

    private void writecom_bontouch_parcelermethods_Root(com.bontouch.parcelermethods.Root root$$3, android.os.Parcel parcel$$21, int flags$$3) {
        if (root$$3 .a == null) {
            parcel$$21 .writeInt(-1);
        } else {
            parcel$$21 .writeInt(1);
            writecom_bontouch_parcelermethods_A(root$$3 .a, parcel$$21, flags$$3);
        }
        if (root$$3 .b == null) {
            parcel$$21 .writeInt(-1);
        } else {
            parcel$$21 .writeInt(1);
            writecom_bontouch_parcelermethods_B(root$$3 .b, parcel$$21, flags$$3);
        }
        if (root$$3 .c == null) {
            parcel$$21 .writeInt(-1);
        } else {
            parcel$$21 .writeInt(1);
            writecom_bontouch_parcelermethods_C(root$$3 .c, parcel$$21, flags$$3);
        }
    }

    private void writecom_bontouch_parcelermethods_A(com.bontouch.parcelermethods.A a$$7, android.os.Parcel parcel$$22, int flags$$4) {
        parcel$$22 .writeString(a$$7 .someString);
        parcel$$22 .writeInt(a$$7 .someInt);
    }

    private void writecom_bontouch_parcelermethods_B(com.bontouch.parcelermethods.B b$$7, android.os.Parcel parcel$$23, int flags$$5) {
        parcel$$23 .writeString(b$$7 .someString);
        parcel$$23 .writeInt(b$$7 .someInt);
    }

    private void writecom_bontouch_parcelermethods_C(com.bontouch.parcelermethods.C c$$7, android.os.Parcel parcel$$24, int flags$$6) {
        parcel$$24 .writeString(c$$7 .someString);
        parcel$$24 .writeInt(c$$7 .someInt);
    }

    @Override
    public int describeContents() {
        return  0;
    }

    @Override
    public com.bontouch.parcelermethods.Root getParcel() {
        return root$$0;
    }

    private final static class Creator$$3
        implements Creator<Root$$Parcelable>
    {


        @Override
        public Root$$Parcelable createFromParcel(android.os.Parcel parcel$$25) {
            return new Root$$Parcelable(parcel$$25);
        }

        @Override
        public Root$$Parcelable[] newArray(int size) {
            return new Root$$Parcelable[size] ;
        }

    }

}
```

As you can see 8 methods have been generated for one class.
These methods could be share between instances instead of being duplicated in every class.

**Comment by johncarl81** [comment]
This isn't a lot.  Even if you had a 100 `@Parcel` annotated beans in this scenario, you'd still have less than 1000 methods added by Parceler, only accounting for a little more than 1% of the Android 65k method limit.

Sharing these methods between the generated classes would mean they would either have to be public static methods, or within a second tier of classes.  Both of these approaches are much more complex and have related drawbacks.  That being said, I'm open to ideas.

**Comment by ansman** [comment]
I don't agree. My project has 196 classes annotated with `@Parcel` and at least 2330 methods are generated. When struggling against the 65k limit every method counts and if 1000 methods could be saved that could make a difference.

I understand this isn't a high priority but it would be nice if it generated less methods.

**Comment by johncarl81** [comment]
Wow, that's a ton of classes!

Best case scenario we could reduce the number of methods to a linear association to the number of annotated classes.  Let me think on this.  There may be a better strategy that also satisfies the partial compilation (potential) problem posed in #111.

**Comment by johncarl81** [comment]
@ansman, I came up with a quick and dirty implementation to consolidate the read / write methods. Could you test and compare the method reduction between the master and this branch:
https://github.com/johncarl81/parceler/tree/build_methods

**Comment by ansman** [comment]
It seems like it's not working with custom `ParcelConverter`s

**Comment by johncarl81** [comment]
@ansman, I just pushed a fix for that and a more robust solution.  Could you try again and let me know how it goes?

**Comment by ansman** [comment]
Here's the results:
  * Number of `@Parcel` classes: **194**
  * Method count with 1.0.3: **63 936**
  * Method count with build_methods (e5362beb): **62 307**
  * Methods saved: **1 629**

Nice job!

**Comment by johncarl81** [comment]
Wow, that's pretty substantial, nearly 10 methods per class!

**Comment by johncarl81** [comment]
Merged!  Thanks for pointing me in this directrion @ansman.

**Comment by ansman** [comment]
Any idea when this will be released and in which version?

**Comment by johncarl81** [comment]
Hmm, possibly this evening.  Trying to figure out if this latest batch of changes warrants a minor version update: 1.1.0?  Thoughts?

**Comment by ansman** [comment]
I guess 1.1.0 since it's a pretty big change

**Comment by tentypwtk** [comment]
Similar issue here. Parceler annotated across 23 classes. When I use method counter plugin, I see:
http://www.methodscount.com/?lib=org.parceler%3Aparceler%3A1.1.5
27597 methods. It seems to work fine on newer android version but as soon as I create an older API emulator (api 16) I hit the 65k method limit. Any idea if it's Parceler's fault or maybe some support libs?
Thanks

**Comment by johncarl81** [comment]
@tentypwtk, the parceler annotation processor you referenced should not be included in your APK,  insted it should be used under `apt` or `provided` scope.  See http://parceler.org/#getting_parceler.  The parceler-api should, however, be included in your APK and contains only 704 methods http://www.methodscount.com/?lib=org.parceler%3Aparceler-api%3A1.1.5

We are very sensitive to method count with Parceler.  Each generated class contains only 7 methods and 1 constructor.  Also there is only 1 generated class per annotated class, so the method count grows linerarly with your codebase.
