### ISSUE TITLE
Support for Parcelables in Parcels.wrap

### ISSUE THREAD

**Issue by ansman** [johncarl81/parceler#158]
I currently have a bunch of generic methods just calling `Parcels.wrap` when they want to make something parcelable.

However, if the object that I pass in is already a parcelable on its own Parceler fails to find an implementation for that object.
I understand it might be out of scope for the project but I would love it if there was a ParcelableParcelable or something that would make `Parcels.wrap` work with parcelable objects.

**Comment by johncarl81** [comment]
Right now the Parcels.wrap keys on the specific class name, not the inheritance hierarchy.  If you could provide a PR with some performance metrics (show that searching the inheritance tree for Parcelable has little effect on the runtime) then I'm more than happy to merge in this change.

**Comment by johncarl81** [comment]
I'm going to close, feel free to reopen if you have a solution or a related issue.
