### ISSUE TITLE
booleans with "is" prefix are not persisted through Parceler

### ISSUE THREAD

**Issue by crebstock** [johncarl81/parceler#162]
I created a simple project to show this.  But if you have a parceler object where you give a boolean primitive an "is" prefix to its name, it doesn't seem to be persisted by parceler.  

In the example I set both booleans to true and they are persisted.  Upon return only the boolean with out the "is" prefix is correctly restored.

I had to use the Don't Keep Activities developer setting in order to trigger the onSaveInstanceState.  I used parceler 1.0.4 in this case.

[ParcelerNameTest.zip](https://github.com/johncarl81/parceler/files/151271/ParcelerNameTest.zip)

Does this fall under the non-standard getter/setters spoken about here?  https://github.com/johncarl81/parceler/issues/105

**Comment by johncarl81** [comment]
Ah, thanks for the example, that makes it so easy to understand the issue.

Looks like your `isSelected` boolean does not have a matching getter / setter.  The property name must match, prepended with either `get` or `is` matching to a method prepended with `set`.  In your example your getter is named `setIsSelected`.  Renaming this to just `setSelected` should do the trick:

```java
@Parcel(value = Parcel.Serialization.BEAN)
public class MyObject {
    private boolean legitSelected;
    private boolean isSelected;

    public boolean isSelected() {
        return isSelected;
    }

    public void setSelected(boolean selected) {
        isSelected = selected;
    }

    public boolean isLegitSelected() {
        return legitSelected;
    }

    public void setLegitSelected(boolean legitSelected) {
        this.legitSelected = legitSelected;
    }
}
```

By the way, you don't need to define the `implementations` or `analyze parameters as those configurations represent no change to Parceler's default configuration.

**Comment by crebstock** [comment]
Its just poor naming convention on the boolean member I guess.  Interestingly enough, if you change the getter to isIsSelected() instead of just isSelected() it works again (as the getter and setter match like your example).  Either way the default getter/setter generation in Android studio will generate code that Parceler doesn't recognize (and therefore won't persist) and its not something anyone will realize until weird behavior in their app causes them to question it.

Not saying that this is a bug (now that I fully understand), but just documenting it in case people run into this issue in the future.  Thanks!

**Comment by johncarl81** [comment]
I went ahead and added a unit test to demonstrate this behavior also:  https://github.com/johncarl81/parceler/commit/37d2dc22c67720deccb1a9f9f73e9abc6933eb90

**Comment by rhonyabdullah** [comment]
Sorry @johncarl81 , i'm new to this library and this is awesome library, just want to confirm, so prepended "is" instead of "get" are still acceptable to a boolean value ?
ex: 
```
boolean inStock;
public setStock(boolean inStock) {this.inStock = inStock};
public isInStock() {return inStock};
```

If that above sample is correct, i think this little cheap explanation should be added into your doc.

**Comment by johncarl81** [comment]
Yes, this is supported following the Java bean standard.  Would you like to
update the README and website with a pull request?

**Comment by rhonyabdullah** [comment]
Soon, will do it later on my freetime and thanks.

**Comment by rhonyabdullah** [comment]
Pull request has been done on this ticket #284 Feel free to review @johncarl81
