### ISSUE TITLE
JackAndJill Compiler ignores @parcel

### ISSUE THREAD

**Issue by pradeep1806** [johncarl81/parceler#168]
Hi ,

We use parceler api in our android app  and when we will compiled the app in Android m (jackandjill) compiler .  While running the appp we get not found exceptions.Then we came to knwo , jackandjill compiler of android m does not supports annotations .
Please suggess some solutions for the same .

**Comment by johncarl81** [comment]
I wonder if its the partial compilation... can you share more details, like your build script or an example application?

**Comment by tom91136** [comment]
Sadly, Jack and Jill does not support annotation processing yet. See
https://bitbucket.org/hvisser/android-apt/issues/33/support-for-jack-and-jill

**Comment by johncarl81** [comment]
This would be a very strange move from Google.

**Comment by tom91136** [comment]
Strange move indeed,  I'm sure they'll have to  support it at some point.
Even their own libraries  such as AutoValue depend on annotation processing.
I guess we'll have to submit a feature requests and wait it out.

**Comment by pradeep1806** [comment]
So , for now the only solution for me is to remove annotations  :(

**Comment by tom91136** [comment]
See https://code.google.com/p/android/issues/detail?id=183871,  they're adding annotation processing in the next release
