### ISSUE TITLE
Inheritance, Abstract class, and Parcelables interaction

### ISSUE THREAD

**Issue by cody1024d** [johncarl81/parceler#170]
I have kind of an odd scenario; and I'm not 100% sure how to go about it.  I'm thinking maybe a custom converter will work; but even that may not work.  I'm trying to make the following function, correctly.  Currently, when I make the super class parcelable, then the generated code tries to construct an instance of it (which obviously doesn't compile because it's abstract), or I remove parcelable, in which case it doesn't compile because the field cannot be parcelled correctly.

```
public abstract class A {

}
```

```
@Parcel
public class B extends A {
    A field;
}
```

The complexity here is the reference within the subclass to an instance of the superclass.

**Comment by johncarl81** [comment]
As long as all instances you assign to `A field

**Comment by johncarl81** [comment]
As long as all instances you assign to `A field` are registered `@Parcel` classes you can use the following custom converter to do the job:

```java
public abstract class A {

    public static class AConverter implements ParcelConverter<A> {
        @Override
        public void toParcel(A input, Parcel parcel) {
            parcel.writeParcelable(Parcels.wrap(input), 0);
        }

        @Override
        public A fromParcel(Parcel parcel) {
            return Parcels.unwrap(parcel.readParcelable(A.class.getClassLoader()));
        }
    }
}

@Parcel
public class B extends A {
    @ParcelPropertyConverter(A.AConverter.class)
    A field;
}
```

You could also register this converter globally:

```java
@Parcel(converter = A.AConverter.class)
public abstract class A {...
```

**Comment by cody1024d** [comment]
Thank you @johncarl81.  I will be running through that solution tomorrow when I have some time.  I think this is the second time you've helped me with my understanding of this framework, and I do really appreciate it.  I'll close this issue as soon as I can verify the above tomorrow!

**Comment by johncarl81** [comment]
Sure thing @cody1024d, glad to help.  Let me know what the outcome is.

**Comment by cody1024d** [comment]
That worked perfectly!  Thanks again.

**Comment by cody1024d** [comment]
When I do this, now, when I go to run the project, I get the following error: 

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/parceler/Parceler$$Parcels$1.class

I'm going to debug through it myself, and see what I come up with, but wanted to attach this, to see if there was something you know of off the bat causing this.

**Comment by johncarl81** [comment]
Sounds like you have multiple modules, like a library that contains `A`?  To handle this you'll need to reference the class remotely: 
http://parceler.org/#avoiding_parcels_indexing

Which might look like the following:
```java
@Parcel
@ParcelClass(value = A.class, annotation = @Parcel(converter = A.AConverter.class))
public class B extends A {
    A field;
}
```

**Comment by johncarl81** [comment]
@cody1024d any movement on this?

**Comment by cody1024d** [comment]
I do have multiple modules, but in this case, both `A` and `B` are in the same module.  I ended up annotating the field within `B` which worked perfectly.  I just forgot to close this.  Sorry about that.
