### ISSUE TITLE
warning: Ignoring InnerClasses attribute for an anonymous inner class

### ISSUE THREAD

**Issue by tehMalan** [johncarl81/parceler#171]
Hi, 

I have a strange error/warning in my Android Studio Messages tab. It goes like this: 

`Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.parceler.apache.commons.collections.BeanMap$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
`

Do you have any idea what can I do about it?

**Comment by tehMalan** [comment]
Nevermind :) 
You can close it.

**Comment by IvoryAguado** [comment]
Hello, 

Could you tell how you sort it out I'm having that error after updating to gradle 3.0.0-beta2

Thank you.

**Comment by tehMalan** [comment]
AFAIR i dropped this lib because I had more problems that benefits :)

**Comment by IvoryAguado** [comment]
I updated all my libs to the latest, now is working again
