### ISSUE TITLE
Array of enums

### ISSUE THREAD

**Issue by dlemures** [johncarl81/parceler#172]
I have an issue regarding arrays of enums:

If I have the following class, where B is an Enum:
```java
@Parcel
class A {
    public B[] elems; // B is an enum
    ....
}
```

The code generated is for the class is:
```java
public class A$$Parcelable implements ... {
    ....
     private A readA(android.os.Parcel parcel$$2) {
         A a$$1;
         a$$1 = new A();
         java.lang.String b$$0 = parcel$$2 .readString();
         b$$1.elems = ((B[]) ((b$$0 == null) ? null : Enum.valueOf(B[].class, b$$0)));
         ...
     }

     private void writeA(A a$$3, android.os.Parcel parcel$$4, int flags$$0) {
         B[] b$$1 = a$$3.b;
         parcel$$4.writeString(((b$$1 == null) ? null : b$$1.name()));
         ...
     }
}
```

So arrays of enums are processed as enums.

**Comment by johncarl81** [comment]
Hmm, I thought this case was covered.  Let me investigate.

**Comment by johncarl81** [comment]
Made a quick fix PR,  which will wait for the next release.  In the mean time, could you use a `List<B>` instead?

**Comment by dlemures** [comment]
Sure. Thx

**Comment by dlemures** [comment]
@johncarl81 when will be the next release?

**Comment by johncarl81** [comment]
Very soon, trying to finalize some other big changes.  This update to fix the enums is also somewhat of a band-aid, I'd like to try and fix it in a better way.  Do you need it for a release or something?

**Comment by dlemures** [comment]
No don't worry, no rush. It is just to know when to expect it. Thx :)

**Comment by johncarl81** [comment]
If you have some free cycles I'd appreciate a review (try the SNAPSHOT out on your project) on the other PRs.

**Comment by dlemures** [comment]
Sure, i'll check it later today

**Comment by dlemures** [comment]
It works perfect.

In my case the enum implements parcelable (just for a short time, it will be moved to Parceler), so now it is treated as an array of parcelables.

**Comment by johncarl81** [comment]
Merged!
