### ISSUE TITLE
Is there any way to ignore specified members?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [johncarl81/parceler#174]
I have the following class

```java
@org.parceler.Parcel
public class TaskModel {

    String taskId;
    String taskColor;
    String title;
    String userId;
    String startTime;
    String endTime;
    String taskDay;

    WeekViewEvent weekViewEvent;
}

```
And I want to ignore the `weekViewEvent` member of the class. 
Actually, it is coming from a library and I cannot annotate it with `@org.parceler.Parcel`. 

What is the Best way to handle such situation?

**Comment by dlemures** [comment]
You can use `transient`:

> For attributes that should not be serialized with Parceler, the attribute field, getter or setter may be annotated by @Transient. In addition, fields marked with the transient keyword will also not be serialized.

**Comment by Shajeel-Afzal** [comment]
Thank you @dlemures, i am closing this issue.
