### ISSUE TITLE
Use all args constructer with @ParcelConstructor

### ISSUE THREAD

**Issue by nassendelft** [johncarl81/parceler#177]
Hi,

I'm using Lombok easy my pain creating POJO's. I also prefer immutable classes. Unfortunately this won't play nicely with Parceler. :(

When using Lombok's @Value, a full arg constructor is created which i can't annotate (well, [not entirely true](https://projectlombok.org/features/experimental/onX.html) but i rather not do that.)

If possible i would rather just add this information in the class annotation. something like @Parcel(constructor = ALL_ARGS)

**Comment by johncarl81** [comment]
Could you just specify Lombok to annotate the generated constructor with `@ParcelConstructor`:

```java
@AllArgsConstructor(onConstructor=@__(@ParcelConstructor))
```

**Comment by johncarl81** [comment]
Oh, that's an experimental feature.

**Comment by johncarl81** [comment]
I am interested in better interoperability, but you might also consider using the Hrisey project if you're a fan of the Lombok https://github.com/mg6maciej/hrisey

**Comment by nassendelft** [comment]
yeah the @AllArgsConstructor(onConstructor=@__(@ParcelConstructor)) is what i linked to.
Also, it doesn't work :(

i haven't heard of hrisey before, i'll look into that, thanks
