### ISSUE TITLE
Ability to use ParcelPropertyConverter annotation with ParcelClass annotation

### ISSUE THREAD

**Issue by ultraon** [johncarl81/parceler#178]
Hello, thanks for you library, very great job!!!
Could you please tell me, how can i use "@ParcelPropertyConverter" while using approach "@ParcelClass" for declaration parcel classes. My model classes are in the different library, and i can't to mark parcel annotations directly to models.
Example which i'm waiting for:
```
@ParcelClasses({
        @ParcelClass(value = ExternalModel.class, annotations = {@ParcelPropertyConverter(value = ExternalModelFieldConverter.class, field = "listOfFields")}) //listOfFields is a member (List<...>) in the ExternalModel class, also we can put multiple property converters
})
public class ParcelsDeclaration {}
```

**Comment by johncarl81** [comment]
Hmm, are you looking to specify a converter for `ExternalModel` or a non-global converter for the properties on `ExternalModel`?

**Comment by ultraon** [comment]
I'm looking for specifying converter for some internal field with type List and generic of abstraction (interface or abstract class). This field is a member of some external library class.

**Comment by johncarl81** [comment]
You could tell Parceler the converter for that type globally:
```java
@ParcelClasses({
        @ParcelClass(value = SomeType.class, annotation = @Parcel(converter = SomeTypeConveter.class)),
        @ParcelClass(value = AnotherType.class, annotation = @Parcel(converter = AnotherTypeConveter.class)),
})
public class ParcelsDeclaration {}
```

**Comment by johncarl81** [comment]
Thinking about it more, you could register the generic type directly or include a converter if necessary.  Parceler knows how to handle `List`s and would also handle your generic type if registered:
```java
class Exernal {
    List<SomethingElse> stuff;
}

@ParcelClasses({
    @ParcelClass(External.class),
    @ParcelClass(value = SomethingElse.class, annotation=@Parcel(converter = PossibleConverter.class))
})
```

**Comment by ultraon** [comment]
Thanks, it even works with List<SomeInterface> property!
