### ISSUE TITLE
Parcelled fields are becoming null while unwrapping object

### ISSUE THREAD

**Issue by girdharpatel** [johncarl81/parceler#179]
Hi, 
I have following fields in my model object which I want to parcel. I am using **Getter/setter serialization**. As you can see, all the 3 fields actually refers to venue latitude. I have to keep all 3 as I get these 3 types of field in my server response. Now is it possible to set all the 3 fields when any setter is called so that caller don't have to worry abt like which getter to call?

I have tried setting all the 3 fields whenever any setter is called but when I unwrap the parcel object, I get all the 3 fields as NULL.

private String VenueLat;
private String Lat;
private String VenueLatitude;

 public String getVenueLat() {
        return VenueLat;
    }

    public void setVenueLat(String venueLat) {
        VenueLat = venueLat;
    }

    public String getLat() {
        return Lat;
    }

    public void setLat(String lat) {
        Lat = lat;
    }

    public String getVenueLatitude() {
        return VenueLatitude;
    }

    public void setVenueLatitude(String venueLatitude) {
        VenueLatitude = venueLatitude;
    }

**Comment by johncarl81** [comment]
Strange, could you update your example to include your `@Parcel` configuration?

**Comment by girdharpatel** [comment]
Sorry was my mistake, I am able to do achieve this though have 1 question. I had tried seting value of only "**VenueLat**"  field in all the 3 setters and returning the value of that only from all the 3 getters but that is not working? Why is that?

**Comment by johncarl81** [comment]
Not sure, can you post your code?

**Comment by girdharpatel** [comment]
Sorry for late reply. I got the answer. The value was set in the model class through GSON de-serialization. I had my logic to set value in "**VenueLat**" field in all the 3 setters but GSON doesn't use setter method during de-serialization but rather uses fields and hence the issue.

So actually the issue was not there with Parceller.
