### ISSUE TITLE
support wrapping and unwrapping of list and array types

### ISSUE THREAD

**Issue by vinc3m1** [johncarl81/parceler#18]
Would be nice to overload the `wrap()` method to support the following:
`public static <T> Parcelable[] wrap(T[] input)`
`public static <T> ArrayList<Parcelable> wrap(List<T> input)`
`public static <T> SparseArray<Parcelable> wrap(SparseArray<T> input)`

This way the API can be used directly on collections of Parcelables e.g.:
`bundle.putParceableArrayList(Parcels.wrap(myArrayListOfObjects));`

**Comment by voghDev** [comment]
Just googled and found this issue. I'm glad there is a solution. I'll just post sample code to help any other that might find this post:

wrapping a List of Entities 

     ArrayList<Entity> objects;
     intent.putExtra("objects", Parcels.wrap(objects));

unwrapping a List of entities 

    ArrayList<Entity> objects;
    objects = getIntent().getParcelableExtra("objects");

Note that class `Entity` must be annotated with @Parcel

    @Parcel
    public class Entity {
        // ...
    }

**Comment by jorgereina1986** [comment]
@voghDev aren't you suppose to use ```Parecels.unwrap``` in order to unwrap the list of objects?

**Comment by voghDev** [comment]
true @jorgereina1986, probably forgot to add the `Parcels.unwrap()` call, thanks for pointint it :-)
