### ISSUE TITLE
release JARs include Guava class -- conflict during build

### ISSUE THREAD

**Issue by del-flexe** [johncarl81/parceler#182]
It appears that release JARs include Guava classes rather than depending on the official Guava JAR:

```
Execution failed for task ':app:transformClassesWithJarMergingForDevelopmentDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/thirdparty/publicsuffix/PublicSuffixPatterns.class
```

This class is found only in Guava JARs on the classpath as well as in Parceler when running a quick script to scan the jarfiles used from the Gradle cache:

```
/Users/****/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9/guava-19.0.jar: com/google/thirdparty/publicsuffix/PublicSuffixPatterns.class
/Users/****/.gradle/caches/modules-2/files-2.1/org.parceler/parceler/1.1.0/40934bd7985e586a82ccb9023a21e92c46497189/parceler-1.1.0.jar: com/google/thirdparty/publicsuffix/PublicSuffixPatterns.class
...
```

Ideally there would be separate JARs - one that is more uberjar-ish (like the current one) and another that excludes 3p dependencies in case someone already uses that dependency so it can be managed through the supported dependency-management system of the build.

**Comment by johncarl81** [comment]
Are you including Parceler in your project's compiled source?  I'd recommend using either `apt` or `provided` scope on the Parceler dependency and only including the api as compiled:

```
compile 'org.parceler:parceler-api:1.1.1'
apt 'org.parceler:parceler:1.1.1'
```

**Comment by del-flexe** [comment]
yep - didn't make it to that part of the instructions after reading usage.

Thanks for the pointer ... might also be worth considering moving the "how to get it" to the top?

**Comment by lpotherat** [comment]
Hi there, 
Juste found this topic, it would be nice to include this config into documentation.
=> Here are the updated lines 

    implementation "org.parceler:parceler-api:$parceler_version"
    compileOnly  "org.parceler:parceler:$parceler_version"
    annotationProcessor "org.parceler:parceler:$parceler_version"

Thanks !

**Comment by johncarl81** [comment]
Why would you need the parceler annotation in both scopes?

**Comment by lpotherat** [comment]
Hmmm, I'm novice at configuring gradle so I put those three lines without really knowing what I was doing :sweat_smile:

So, what do you mean by "both scopes" ?
