### ISSUE TITLE
ParcelerRuntimeException with Collections.singletonList

### ISSUE THREAD

**Issue by jisung** [johncarl81/parceler#183]
Parcels.wrap() raises the following Exception with a List created from Collections.singletonList(). Could you support these List types in the future release?

```
org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for java.util.Collections$SingletonList, verify that your class is configured properly and that the Parcelable class java.util.Collections$SingletonList$$Parcelable is generated by Parceler.
at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:169)
at org.parceler.Parcels.wrap(Parcels.java:84)
at org.parceler.Parcels.wrap(Parcels.java:68)
at jisung.github.com.parcelertest.ApplicationTest.testSingletonList(ApplicationTest.java:37)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1959)
```
it was my testing code:
``` 
public void testSingletonList() throws Exception {
    List<String> source = Collections.singletonList("Hello");
    Parcelable p = Parcels.wrap(source);
    List<String> unwrapped = Parcels.unwrap(p);
    assertEquals(source, unwrapped);
}
```

**Comment by johncarl81** [comment]
We actually have a [unit test highlighting a similar case](https://github.com/johncarl81/parceler/blob/06d23d5000644222d7f73c418d056b047b530b2f/examples/test/src/test/java/org/parceler/NonParcelTest.java#L80).  You'll need to specify the type for Parceler to wrap:
```java
public void testSingletonList() throws Exception {
    List<String> source = Collections.singletonList("Hello");
    Parcelable p = Parcels.wrap(List.class, source);
    List<String> unwrapped = Parcels.unwrap(p);
    assertEquals(source, unwrapped);
}
```

By the way, the above code does not actually marshal the object through a Parcel, it simply wraps it and unwraps it.  Take a look at the referenced unit test and `ParcelsTestUtil` for an example of how to fully test his functionality.

**Comment by jisung** [comment]
You're right, thank you.

I'm a bit confused about the mapped types for List, 

> List, ArrayList and LinkedList of any of the mapped types*

In order to call Parcels.wrap(), so the only ArrayList and LinkedList are supported directly without explicit input type argument not for the all the List implementations?

**Comment by johncarl81** [comment]
That is correct.  There are a quite large number of implementations of List out there and it would be impossible to support them all.

**Comment by jisung** [comment]
Okay thanks for the clarification. Will close this issue.
