### ISSUE TITLE
Unit test problem with new build tools

### ISSUE THREAD

**Issue by Tanapruk** [johncarl81/parceler#187]
When I use `classpath 'com.android.tools.build:gradle:2.1.0'`  and run unit test, there is an error:
`Error:Execution failed for task ':module:compileDevelopDebugUnitTestJavaWithJavac'.
> Unable to find source java class: '/Users/trusttanapruk/Documents/Nextzy/AISAppBuilder/eService/eService/aISeService/build/intermediates/classes/develop/debug/com/ais/mimo/eservice/network/payment/model/PaymentBillResult$PaymentDetail$$Parcelable.java' because it does not belong to any of the source dirs: '[/Users/trusttanapruk/Documents/Nextzy/AISAppBuilder/eService/eService/aISeService/src/test/java, /Users/trusttanapruk/Documents/Nextzy/AISAppBuilder/eService/eService/aISeService/src/testDevelop/java, /Users/trusttanapruk/Documents/Nextzy/AISAppBuilder/eService/eService/aISeService/src/testDebug/java, /Users/trusttanapruk/Documents/Nextzy/AISAppBuilder/eService/eService/aISeService/src/testDevelopDebug/java]'`

The workaround is to rebuild/clean build. But after some code changing the error came back.

The best solution so far is to revert build tool to  `classpath 'com.android.tools.build:gradle:2.1.0'` and the error doesn't show anymore.
My setting is
`    compile 'org.parceler:parceler-api:1.1.2'
    provided 'org.parceler:parceler:1.1.2'`

**Comment by johncarl81** [comment]
have you tried using android-apt?

**Comment by Tanapruk** [comment]
I changed from `provided ` to `apt` and `apply plugin: 'com.neenbedankt.android-apt'`and the error is gone.

Thank you.
