### ISSUE TITLE
Useless library

### ISSUE THREAD

**Issue by ismaeltoe** [johncarl81/parceler#188]
Android Studio now allows generate automatically that "ton of boilerplate" to implement Parcelable. If I were you, I will make this library deprecated and recommend users use the Android Studio feature. I think now it will be more painful than useful (regardless of some compatibility issues, etc.).

**Comment by johncarl81** [comment]
I'll try to take this comment in a positive way...

This sort of IDE feature does not replace the need for libraries like Parceler.  Code added to the codebase by the IDE may be a quick way to get the job done, but over time as objects and requirements change that IDE generated code requires maintenance.  In contrast, code managed by Parceler would adapt and change over time, freeing up that maintenance need.  In addition, Parceler handles more than just the simple one-class case, it is able to serialize via the Parcelable standard a graph of objects and collections.

If you're having trouble with Parceler, please post something specific so someone can resolve the issue and help others in the community.

**Comment by ismaeltoe** [comment]
> I'll try to take this comment in a positive way...

Sorry, I want you to know I didn't mean to hurt you.
