### ISSUE TITLE
cryptic error with inherited classes?

### ISSUE THREAD

**Issue by kenyee** [johncarl81/parceler#19]
Could you make this error a bit more explanatory? :-)

```
   Execution failed for task ':app:compileDebugJava'.
   > org.androidtransfuse.TransfuseAnalysisException: @Parcel code generation did not complete successfully.
```

I got it trying to use it with an abstract class hierarchy...something like:

```
@Parcel
abstract class A {
  int field1;
  int field2;
}
@Parcel
class B extends A {
  String fields
  //etc.
}
```

And marked class `B` as `@Parcel` only initially since I wouldn't try parceling class `A`.  I tried adding `@Parce`l to class `A` w/o luck.

It'd help if it printed out how far it got parceling so we could get a bit more of a clue as to what field or class it's having a hard time with :-P

It's probably also a good idea to add a hierarchy class as an example on the site too..

**Comment by shilu-stha** [comment]
I am getting this error. Please help fix it asap.

warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.parceler.apache.commons.collections.BeanMap$10) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
:app:dexMemberDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:283)
	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
Error:Execution failed for task ':app:dexMemberDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/jdk1.8.0_45/bin/java'' finished with non-zero exit value 2

**Comment by vinc3m1** [comment]
@shilu-stha you're running into the dex method limit. Unrelated to this library.
