### ISSUE TITLE
Unable to find generated Parcelable class for Realm

### ISSUE THREAD

**Issue by skptl** [johncarl81/parceler#193]
Hi @johncarl81 

After a recent update to v1.1.2, I have started getting org.parceler.ParcelerRuntimeException:
I use parceler along with Realm.

```java
@Parcel(implementations = { StampRealmProxy.class },
	value = Parcel.Serialization.BEAN,
	analyze = { Stamp.class })
public class Stamp extends RealmObject {
	@PrimaryKey
	public String _id;
	public boolean enabled;
	public boolean purchasable;
	public String name, appUrl;
	/** Getters and setters */
}
```

Stacktrace:
```java
org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable 
			class for io.realm.StampRealmProxy,
			verify that your class is configured properly 
			and that the Parcelable class io.realm.StampRealmProxy$$Parcelable is generated by Parceler.

                       at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:153)
                       at org.parceler.Parcels.wrap(Parcels.java:72)
                       at org.parceler.Parcels.wrap(Parcels.java:56)
```

Thanks,
Shilpan

**Comment by johncarl81** [comment]
Hi @skptl,

We're removing the class that mapped the implementations to the given class (I should have marked the implemenations parameter as `@Depreciated` and updated the docs)... could you use the following pattern instead:
```java
Parcels.wrap(Stamp.class, realmStampInstance)
```

**Comment by johncarl81** [comment]
Now that I tihnk about it, we might be able to preserve this feature by generating a secondary `Parcelable` class.

**Comment by skptl** [comment]
Hi @johncarl81 

Thanks for the quick response, I just tried ```Parcels.wrap(Stamp.class, realmStampInstance)``` and it worked and saw that you suggested the same thing.

This even breaks when using with AndroidAnnotations, so I think untill you have it fixed at all places you should preserve this feature.

Following is generated with AAs:
```java
/**
   * 
   * @param stamp
   *     the value for this extra
   * @return
   *     the IntentBuilder to chain calls
   */
   public StampActivity_.IntentBuilder_ stamp(Stamp stamp) {
        return super.extra(STAMP_EXTRA, Parcels.wrap(stamp));
   }
```

Thanks.

**Comment by johncarl81** [comment]
Ah, got it.  I'll get a fix out there this evening under 1.1.4.

**Comment by skptl** [comment]
@johncarl81 I will confirm once the fix is out. Thanks.

**Comment by johncarl81** [comment]
Awsome, would you be willing to test the SNAPSHOT pre-release?

**Comment by johncarl81** [comment]
Could you try out #194 @skptl?

**Comment by skptl** [comment]
@johncarl81 my apologies, but I am not sure how would I try that. It would be helpful if you can let me know how can I try that.

**Comment by johncarl81** [comment]
I'll assume you're using gradle.  Check it out, build it locally:
```
git clone git@github.com:johncarl81/parceler.git
cd parceler
git checkout -b reintroduce_impls origin/reintroduce_impls
mvn clean install
```
Then add you local maven repo to your gradle script:
```
repositories {
    mavenLocal()
    ...
}
```
And the snapshot dependency:
```
dependencies {
    compile 'org.parceler:parceler-api:1.1.4-SNAPSHOT'
    apt 'org.parceler:parceler:1.1.4-SNAPSHOT'
}
```

If you don't have maven installed I could probably deploy it for you, or you could use [Jitpack](https://jitpack.io/)

**Comment by johncarl81** [comment]
Releasing 1.1.4 currently to maven central.

**Comment by skptl** [comment]
Hi @johncarl81 ,

I was updating RealmObjects in my code to implement interfaces instead of extending objects.

I use Parceler with AndroidAnnotations, the problem that I have is sometimes Parceler fails to find RealProxy class. The weird part is it doesn't fail all the times with all objects.

`Unable to find generated Parcelable class for io.realm.StampRealmProxy`

I will be great if you could help me.

Thanks.

**Comment by johncarl81** [comment]
Is this a failure at runtime or compiletime @skptl ?

**Comment by mhdtouban** [comment]
at compile time.. please fix this as am not able to use parcel with realm and kotlin 
see also #306
