### ISSUE TITLE
Proguard issue when parceling null objects.

### ISSUE THREAD

**Issue by mkisiel** [johncarl81/parceler#195]
While trying to unparcel Bundle null value wrapped by Parceler the following exception is being thrown:

> android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class org.parceler.Parcels$NullParcelable

I was using proguard rules provided in the readme and in https://github.com/johncarl81/parceler/issues/146.

The following lines need to be included in proguard rules:

> -keepnames class org.parceler.Parcels$NullParcelable {
>     public static final ** CREATOR;
> }

**Comment by johncarl81** [comment]
We actually did away with the `NullParcelable` in a recent release, can you try upgrading?

**Comment by mkisiel** [comment]
Sure, I will try this on the latest version and give you feedback.

**Comment by johncarl81** [comment]
With the latest (1.1.4) you should also only need the following proguard config:
```
# Parcel library
-keep class **$$Parcelable { *; }
```

**Comment by mkisiel** [comment]
Thanks, parcelling nulls works with the latest version.

**Comment by johncarl81** [comment]
:+1:
