### ISSUE TITLE
Unable to find generated Parcelable class...

### ISSUE THREAD

**Issue by heitorcolangelo** [johncarl81/parceler#198]
Hi! I'm getting a error using Parcels.wrap in my class:

```java
@Parcel(Parcel.Serialization.BEAN)
public class UserVO {
    @Expose private String socialId;
    @Expose private String firstName;
    @Expose private String lastName;
    @Expose private String email;
    @Expose private String password;
    @Expose private Gender gender;
    @Expose private String phoneNumber;
    @Expose private boolean terms;
    @Expose private boolean notification;
    @Expose private DateType birthday;
    @Expose private String cpf;
    getters and setters...
}
```
And when I try to:
```java
Parcels.wrap(userVO)
```
I got this error
**Unable to find generated Parcelable class for com.package.name.UserVO, verify that your class is configured properly and that the Parcelable class com.package.name.UserVO$$Parcelable is generated by Parceler.**

I also had tried this:
```java
Parcels.wrap(UserVO.class, userVO)
```
But got the same result. By now, to complete my task I'm using the generated class:
```java
new UserVO$$Parcelable(userVO)
```
Does anyone already had this issue and can help me? Thank you!

**Comment by johncarl81** [comment]
How have you declared Parceler in your build?

**Comment by johncarl81** [comment]
Well, that looks appropriate... and it looks like `UserVO$$Parcelable` is generated, correct?

**Comment by johncarl81** [comment]
and is `@Expose` a Gson annotation?

**Comment by heitorcolangelo** [comment]
Yes, `UserVO$$Parcelable` is generated, that's why i'm using it.
`@Expose ` is a Gson annotation.
If you need more info to help you find what's wrong let me know.
I'm also still trying to find out what's wrong.
Thanks!

**Comment by johncarl81** [comment]
If you want to debug, here's the line of code that looks up the given generated `Parcelable` class by name:
https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/Parcels.java#L143

I'd verify that this line of code is being called and the expected generated class is being returned.

**Comment by johncarl81** [comment]
@heitorcolangelo, have you been able to investigate?

**Comment by heitorcolangelo** [comment]
Hey John!
The error happens in this method in the Parcels class:
```java
public ParcelableFactory findClass(Class clazz){
            try {
                Class parcelWrapperClass = Class.forName(buildParcelableImplName(clazz));
                return new ParcelableFactoryReflectionProxy(clazz, parcelWrapperClass);
            } catch (ClassNotFoundException e) {
                return null;
            }
        }
```

when 
```java
Class parcelWrapperClass = Class.forName(buildParcelableImplName(clazz));
```

it throws a ClassNotFoundException
But it's really strange, this is the only class that it's causing this error, all the others are ok.

**Comment by johncarl81** [comment]
Can you isolate the name of the class and compare it against the generated class name?

**Comment by heitorcolangelo** [comment]
Sorry, what do you mean by isolate the name of the class?
Can you give me a example?
Thanks!

**Comment by johncarl81** [comment]
What does `buildParcelableImplName(clazz)` return?  Is that the fully qualified name of the generated class?

**Comment by johncarl81** [comment]
@heitorcolangelo, can you share an example?

**Comment by heitorcolangelo** [comment]
That is what this method returns:
```java
com.package.name.UserVO$$Parcelable
```

I think it's not difficult to reproduce. Just create a class like the one above and try to use Parcels.wrap in a object of that class. You can remove the Gender and DataType fields, the error happens even without these fields.
Sorry for the delay on reply, I'll try to make it faster.

**Comment by johncarl81** [comment]
Ok, I put together a quick demo here:  https://github.com/johncarl81/parcelerTest

Looks like it works just fine.  I had to change the package name to not include `package`, as it's a reserved word.  Can you make this fail?  Am I missing anything?

**Comment by heitorcolangelo** [comment]
I wasn't able to make this example fails, but the error persist on my original application.
The only difference is that UserVO class is in another module. I'm not considering that this could be causing the error because I have other classes in this separated module, and they work just fine. This is the only case.
Feel free to close this issue if you want.
Thanks for your support.

**Comment by johncarl81** [comment]
That is an important detail.  Do you have the Parceler annotation processor running on that module?

**Comment by heitorcolangelo** [comment]
Yes I do.

**Comment by johncarl81** [comment]
Hmm, I tried splitting apart the example I put together and still couldn't make it fail.  Are you using a regular java library or an android module?

**Comment by heitorcolangelo** [comment]
I think that proguard is obfuscating the class, I'll take a look on
proguard configuration and see if it is the case.

Em seg, 30 de mai de 2016 16:06, John Ericksen <notifications@github.com>
escreveu:

**Comment by NeoDigi** [comment]
I have a similar problem.
Everything works fine on debug, but when I build on release (hence, running proguard) I get the same error.
I did put : -keep class **$$Parcelable { *; } in my proguard file.

It's worth nothing that I'm using Realm but I think that I configured it correctly too.

**Comment by johncarl81** [comment]
Ah, proguard would be a likely culprit here.  Does `-keep class **$$Parcelable { *; }` not cover enough?

**Comment by NeoDigi** [comment]
Apparently not...
And I definitely think that's a proguard error because it works just fine in debug.
even putting:
-keep interface org.parceler.Parcel
-keep @org.parceler.Parcel class * { *; }
-keep class **$$Parcelable { *; }
-keep class org.parceler.Parceler$$Parcels

doesn't work

**Comment by johncarl81** [comment]
FYI we abandoned `org.parceler.Parceler$$Parcels`... but that doesn't solve your problem.

Can you keep the class specifically by fully qualified class name?

**Comment by johncarl81** [comment]
@NeoDigi, @heitorcolangelo any progress on this?

**Comment by NeoDigi** [comment]
@johncarl81 No, no progress, just to let you know, I have a realmObject with several other realmObject in it, and in those I have some realmList<RealmObject>.
I have this added to all my realObject:
@Parcel(implementations = { MyModelRealmProxy.class },
        value = Parcel.Serialization.BEAN,
        analyze = { MyModel.class }) 

I use to gist for my realmList: https://gist.github.com/Rexee/3ec92b759b3a944d4ad4b28666b2479c

It may be worth noting that in some of my models I have:
@Retention(RetentionPolicy.SOURCE)
    @StringDef({ PENDING, RESOLVED })
    private @interface MyModelStatusDef {
    }

**Comment by heitorcolangelo** [comment]
@johncarl81 No progress, sorry.
I'm not able to focus on this issue at the moment. Anyway, thanks for your support!

**Comment by johncarl81** [comment]
@NeoDigi, does your application work if you reference the generated parcelable directly:
```java
new Country$$Parcelable(country);
```

**Comment by Arinzeokeke** [comment]
hey, Im having the same problem except that I'm not even getting a reference in `new Movie$$Parcelable(movie)`. Heres my dependencies `dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.loopj.android:android-async-http:1.4.6'
    compile 'com.google.code.gson:gson:2.6.2'
    compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'org.parceler:parceler-api:1.1.5'
    apt 'org.parceler:parceler-api:1.1.5'
}`. What am I missing?

**Comment by Arinzeokeke** [comment]
@johncarl81 I just changed it to that. It still doesnt recognize Movie$$Parcelable. Ive even removed all the @Serializable annotations in my member variables if thats the cause. Still, the same issue.

Here are my build files.
[https://gist.github.com/Arinzeokeke/3f29af4192639baf132e55353bd395ac](url)
[https://gist.github.com/Arinzeokeke/54b300af271e319a4b8cdd307706dfa9](url)

And my model
 [https://gist.github.com/Arinzeokeke/47507abe7cdb9b24bb131d0eb82bdc09](url)

**Comment by johncarl81** [comment]
I dont have access to those gists @Arinzeokeke

**Comment by Arinzeokeke** [comment]
@johncarl81  My bad. I've fixed the links. You should see them now

**Comment by johncarl81** [comment]
I see you're using proguard, can you check if the Parcelable classes are generated?

**Comment by Arinzeokeke** [comment]
How do I check in with proguard if its generated? Im still new to android. Anyway,
I ended up implementing the parcelable manually.

**Comment by johncarl81** [comment]
they should be generated under `build/generated/source/` I believe.

**Comment by johncarl81** [comment]
@Arinzeokeke, @NeoDigi could you check your proguard `mappings.txt` and `usage.txt` for these missing generated Parcelables?  These should be found in the `/build/outputs/mapping/release/` directory.

**Comment by Arinzeokeke** [comment]
@johncarl81 Weird. Without no change to my build files whatsoever, Today, I tried using the parcels wrapper on another object and it worked, so, out of curiosity,  I commented out the parcelable implementation code I wrote on the movie class yesterday and used the parcels  wrapper on it and it worked too.

**Comment by Arinzeokeke** [comment]
BTW,  thanks man for taking out time for this.

**Comment by johncarl81** [comment]
@Arinzeokeke, hmm, strange, I can't say I know what's happening.  Let me know if you find anything concrete.  And you're welcome, doesn't take too much time out of my day ;-)

**Comment by johncarl81** [comment]
I'm going to chalk this one up to proguard.  Please reopen or comment if this is still an issue.

**Comment by NeoDigi** [comment]
@johncarl81 Sorry I was away for a while.
So to answer you, this is still an ongoing problem.
I can reference my class by using new Country$$Parcelable(country); 
my class is correctly generated is the build/generated/source and it's not rename.
Now in the stacktrace it says it can't find my model$$Parcelable but in the stacktrace my model is rename so instead of saying can't find countries$$Parcelable it says can't find r$$Parcelable

**Comment by johncarl81** [comment]
@NeoDigi, can you review your `mappings.txt` and `usage.txt` files generated by proguard to see if it is removing the generated classes?  Other than that I think I need to see this in action, can you produce a quick example application demonstrating the problem?

**Comment by NeoDigi** [comment]
I'll try to make an example when I get home, can you tell me what I'm looking for in mappings.txt and usage.txt exactly ?

**Comment by johncarl81** [comment]
Look for any mention of classes ending with `$$Parcelable`.  If they are removed by Proguard then they should be logged as such in the usage.txt file: https://developer.android.com/studio/build/shrink-code.html.

**Comment by mmangliers** [comment]
Just want to chime in that I'm having a similar issue, proguard is breaking my parcels. Generated classes aren't listed in usage.txt. Here's a snippet from my mappings:

`com.mark.mhgenguide.model.ItemFull -> com.mark.mhgenguide.model.ae:
    int mRarity -> l
    int mValue -> m
    java.lang.String mDescription -> n
    void <init>() -> <init>
    void setRarity(int) -> d
    void setValue(int) -> e
    int getRarity() -> k
    int getValue() -> l
    java.lang.String getDescription() -> m
    void setDescription(java.lang.String) -> b
com.mark.mhgenguide.model.ItemFull$$Parcelable -> com.mark.mhgenguide.model.ItemFull$$Parcelable:
    com.mark.mhgenguide.model.ItemFull itemFull$$0 -> itemFull$$0
    com.mark.mhgenguide.model.ItemFull$$Parcelable$Creator$$8 CREATOR -> CREATOR
    void <init>(com.mark.mhgenguide.model.ItemFull) -> <init>
    void writeToParcel(android.os.Parcel,int) -> writeToParcel
    void write(com.mark.mhgenguide.model.ItemFull,android.os.Parcel,int,org.parceler.IdentityCollection) -> write
    int describeContents() -> describeContents
    com.mark.mhgenguide.model.ItemFull getParcel() -> getParcel
    com.mark.mhgenguide.model.ItemFull read(android.os.Parcel,org.parceler.IdentityCollection) -> read
    java.lang.Object getParcel() -> getParcel
    void <clinit>() -> <clinit>
com.mark.mhgenguide.model.ItemFull$$Parcelable$Creator$$8 -> com.mark.mhgenguide.model.af:
    void <init>() -> <init>
    com.mark.mhgenguide.model.ItemFull$$Parcelable createFromParcel(android.os.Parcel) -> a
    com.mark.mhgenguide.model.ItemFull$$Parcelable[] newArray(int) -> a
    java.lang.Object[] newArray(int) -> newArray
    java.lang.Object createFromParcel(android.os.Parcel) -> createFromParcel`

I'm guessing the issue is the base class being renamed, but I haven't been able to figure out how to prevent all the annotated classes from being obfuscated?

**Comment by johncarl81** [comment]
What exception are you getting Mark?

**Comment by NeoDigi** [comment]
There you go: https://github.com/NeoDigi/ParcelerBug
works fine on debug, crash on release, the code is weird it's because i took another project and just took what was necessary to reproduce the bug.

**Comment by mmangliers** [comment]
Getting: Unable to find generated Parcelable class for com.mark.mhgenguide.model.ae, verify that your class is configured properly and that the Parcelable class com.mark.mhgenguide.model.ae$$Parcelable is generated by Parceler.

The original class is being generated by parceler, but not with the obfuscated name.

**Comment by johncarl81** [comment]
Ah, I didn't think of that.. if the original class is obfuscated by
proguard then the class name will not match.  Can you add the following
proguard rule and test again?:

-keep @org.parceler.Parcel class * { *; }

**Comment by johncarl81** [comment]
Oh, good.  @mmangliers could you try with just the following rules? The rest reference depreciated code or unnecessary additions:

```
-keep @org.parceler.Parcel class * { *; }
-keep class *$$Parcelable { *; }
```

**Comment by mmangliers** [comment]
The following line appears to be necessary for my code to run properly:

`-keep interface org.parceler.Parcel`

This plus the two you listed is enough to get everything working, but without this line I still get the error.

**Comment by johncarl81** [comment]
Ah, ok, great.  @NeoDigi could you try this rule set as well and let me know if it solves your issue too?

**Comment by johncarl81** [comment]
@mmangliers, would you like to open a PR with the relevant changes to the README and the [website](https://github.com/johncarl81/parceler-site)?

**Comment by NeoDigi** [comment]
Added:
-keep interface org.parceler.Parcel
-keep @org.parceler.Parcel class * { *; }
-keep class *$$Parcelable { *; }
Still have:

`FATAL EXCEPTION: main
                                                   Process: be.neodigi.parcelertest, PID: 12543
                                                   java.lang.RuntimeException: Could not dispatch event: class be.neodigi.parcelertest.data.model.b to handler [EventHandler public void be.neodigi.parcelertest.ui.MainActivity.onCountryClick(be.neodigi.parcelertest.data.model.b)]: Unable to find generated Parcelable class for be.neodigi.parcelertest.data.model.Country, verify that your class is configured properly and that the Parcelable class be.neodigi.parcelertest.data.model.Country$$Parcelable is generated by Parceler.
                                                       at com.b.a.b.a(SourceFile:460)
                                                       at com.b.a.b.b(SourceFile:387)
                                                       at com.b.a.b.a(SourceFile:368)
                                                       at com.b.a.b.c(SourceFile:337)
                                                       at be.neodigi.parcelertest.ui.c.onClick(SourceFile:70)
                                                       at android.view.View.performClick(View.java:5106)
                                                       at android.view.View$PerformClick.run(View.java:20329)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5912)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
                                                    Caused by: org.parceler.bv: Unable to find generated Parcelable class for be.neodigi.parcelertest.data.model.Country, verify that your class is configured properly and that the Parcelable class be.neodigi.parcelertest.data.model.Country$$Parcelable is generated by Parceler.
                                                       at org.parceler.by.a(SourceFile:153)
                                                       at org.parceler.bw.a(SourceFile:72)
                                                       at org.parceler.bw.a(SourceFile:56)
                                                       at be.neodigi.parcelertest.ui.NextActivity.a(SourceFile:21)
                                                       at be.neodigi.parcelertest.ui.MainActivity.onCountryClick(SourceFile:84)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.b.a.g.a(SourceFile:89)
                                                       at com.b.a.b.b(SourceFile:385)
                                                       at com.b.a.b.a(SourceFile:368) 
                                                       at com.b.a.b.c(SourceFile:337) 
                                                       at be.neodigi.parcelertest.ui.c.onClick(SourceFile:70) 
                                                       at android.view.View.performClick(View.java:5106) 
                                                       at android.view.View$PerformClick.run(View.java:20329) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5912) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200) `

**Comment by johncarl81** [comment]
@NeoDigi I was able to reproduce your error, thanks again for putting together that example project.  It seems there was a missing `*` character in the proguard rules file.  I've created a PR against your example project to demonstrate: https://github.com/NeoDigi/ParcelerBug/pull/1

Please let me know if this fixes the issue for you.  Thanks.

**Comment by johncarl81** [comment]
Updates to match these rules:
https://github.com/johncarl81/parceler/pull/219
https://github.com/johncarl81/parceler-site/pull/6

**Comment by NeoDigi** [comment]
@johncarl81  that fixed it on the project that I linked yes! awesome!
I'll try on my real project at work tomorrow but I guess that'll work just as fine, I'll update this when I can try!
thanks a lot anyway

**Comment by johncarl81** [comment]
@heitorcolangelo, if you revisit your project be sure to check out this updated proguard rule set.

**Comment by heitorcolangelo** [comment]
Hey John!
Thanks, I'll check this tomorrow and update here with the result!

**Comment by johncarl81** [comment]
Awesome!  I'll mark this as closed and merge the PR.  Thanks for sticking with this.

**Comment by mhdtouban** [comment]
@johncarl81 I am getting the same error but with kotlin.
I have this class
```@Parcel(value = Parcel.Serialization.BEAN, analyze = [(AddressItem::class)])
@RealmClass      // required if using JDK 1.6 (unrelated to Parceler issue)
open class AddressItem : RealmObject() {
    @SerializedName("id")
    var id: Int = 0 //54
    @SerializedName("user_id")
    var userId: Int = 0 //12
    @SerializedName("name")
    var name: String = "" //HOME
    @SerializedName("street")
    var street: String = "" //street abc
    @SerializedName("apartment_number")
    var apartmentNumber: String = "" //2
    @SerializedName("area")
    var area: String = "" //california
    @SerializedName("city")
    var city: String = ""//san fransisco
    @SerializedName("long")
    var long: String = "" //35.501777
    @SerializedName("lat")
    var lat: String = "" //33.893791
    @SerializedName("delivery_notes")
    var deliveryNotes: String = ""
}
```
       ```
 activity?.launchActivity<AddressActivity> {

            val bundle = Bundle()
            bundle.putParcelable("item", Parcels.wrap<AddressItem>(item))

        }
      val item = Parcels.unwrap<AddressItem>(intent.getParcelableExtra<Parcelable>("item"))

```
 org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for com.butlr.data.model.AddressItem, verify that your class is configured properly and that the Parcelable class com.butlr.data.model.AddressItem$$Parcelable is generated by Parceler.

How do I know if parcelable class is generated by Parceler ?

**Comment by niroj08** [comment]
Back in this issue after a long gap :)

@Parcel(implementations = {xyz_xyz_model_InstituteRealmProxy.class},
        value = Parcel.Serialization.BEAN,
        analyze = {Institute.class})
public class Institute extends RealmObject {

    private RealmList<Course> services;

    public RealmList<Course> getServices() {
        return services;
    }

    @ParcelPropertyConverter(RealmListParcelConverter.class)
    public void setServices(RealmList<Course> services) {
        this.services = services;
    }
}

working with latest dependencies
 //parceler
    implementation 'org.parceler:parceler-api:1.1.13'
    annotationProcessor 'org.parceler:parceler:1.1.13'

classpath "io.realm:realm-gradle-plugin:7.0.0"

And I have exactly the similar issue as @NeoDigi 

Unable to find generated Parcelable class for h.b.z0, verify that your class is configured properly and that the Parcelable class h.b.z0$$Parcelable is generated by Parceler.


My code worked fine in debug but not with release and for sure its a proguard issue.
# Parceler library
-keep interface org.parceler.Parcel
-keep @org.parceler.Parcel class * { *; }
-keep class **$$Parcelable { *; }

Could it be other proguard lines messing with each other?
Looking for some solutions.
