### ISSUE TITLE
Parceler 1.1.5 / MavenCentral / bad record MAC

### ISSUE THREAD

**Issue by johnjohndoe** [johncarl81/parceler#202]
When I want to automatically download the artifact for Parceler 1.1.5 from MavenCentral Gradle stops with the following error:

```
* What went wrong:
A problem occurred configuring project ':MyProject'.
> Could not resolve all dependencies for configuration ':MyProject:apt'.
   > Could not download parceler.jar (org.parceler:parceler:1.1.5)
      > Could not get resource 'https://repo1.maven.org/maven2/org/parceler/parceler/1.1.5/parceler-1.1.5.jar'.
         > bad record MAC
```

Can you confirm this error?

### Temporary workaround
I put `jcenter` before `mavenCentral` in my _build.gradle_ - then it works.

**Comment by johncarl81** [comment]
Hmm, any idea what this could be?  Building my projects after clearing the gradle cache downloaded without error.

**Comment by johnjohndoe** [comment]
I can no longer reproduce it. It might have been a temporary server error. Thanks anyway :dog:
