### ISSUE TITLE
Jcenter

### ISSUE THREAD

**Issue by anna-b** [johncarl81/parceler#204]
The last available version of the Parceler on jcenter is 1.0.1 https://jcenter.bintray.com/org/parceler/parceler/

**Comment by johncarl81** [comment]
Parceler is distributed via maven central: http://search.maven.org/#artifactdetails%7Corg.parceler%7Cparceler%7C1.1.5%7Cjar

**Comment by johncarl81** [comment]
hmm, I wonder if there is a way to sync with jcenter...

**Comment by johncarl81** [comment]
Ah, it seems that when you take ownership of your repository in jcenter it stops automatically syncing from maven central.  Therefore, I gave up ownership of the parceler repositories and it re-synced with maven central.  You'll find the latest in jcenter now.

**Comment by anna-b** [comment]
Thank you very much for help! Everything works perfect now :)
