### ISSUE TITLE
Guava and javax_ classes are bundled in the jar

### ISSUE THREAD

**Issue by savvasdalkitsis** [johncarl81/parceler#205]
The produced artifact contains com.google.common.* and javax_ classes which can conflict with dependencies in the projects this library is used on. 

Specifically on Android, building fails during the dex step cause the guava classes are being included twice if the android app is getting guava from somewhere else as well

**Comment by johncarl81** [comment]
Don't include the Parceler annotation processor in your project.  Use `apt`, `provided` or (if you're using Jack) `annotationProcessor`.
