### ISSUE TITLE
Annotation Processor doesn't put error messages in the console log

### ISSUE THREAD

**Issue by ultraon** [johncarl81/parceler#206]
Hello, few months ago i noticed if we have some incorrect configuration for classes which use Parcel library the Annotation Processor doesn't put any error messages in to the console log while project compilation any more.
Could you please give me the hint how can i know if the issue with Parcel configuration. I use a lot of libraries which use Annotation Processor, and without error messages in log i can't to fix errors fast. Thank you very much!

**Comment by johncarl81** [comment]
@ultraon, I've put a lot of work into making sure error cases are handled.  That being said, there may be things I've missed.  If you have an example of an error condition I'd love to incorporate it into the tests and fix the issue with a proper error message.  See an error case in the analysis tests: https://github.com/johncarl81/parceler/blob/master/parceler/src/test/java/org/parceler/internal/ParcelableAnalysisTest.java#L559-L570
