### ISSUE TITLE
Google maps unable to handle list that was put by Parceler

### ISSUE THREAD

**Issue by AAverin** [johncarl81/parceler#207]
I get that this is probably another one of numberous google maps bugs, but still, maybe there is a known workaround?

I have a list of Parceler objects
I put them to my outstate as `putParcelable(SAVESTATE_PHOTOS, Parcels.wrap(items))`

After I rotate a device I get a crash. Looks like MapView tried restoring itself and stumbled on my list crashing:
```
Class not found when unmarshalling: org.parceler.NonParcelRepository$ListParcelable
      java.lang.ClassNotFoundException: org.parceler.NonParcelRepository$ListParcelable
          at java.lang.Class.classForName(Native Method)
          at java.lang.Class.forName(Class.java:324)
          at android.os.Parcel.readParcelableCreator(Parcel.java:2383)
          at android.os.Parcel.readParcelable(Parcel.java:2337)
          at android.os.Parcel.readValue(Parcel.java:2243)
          at android.os.Parcel.readArrayMapInternal(Parcel.java:2592)
          at android.os.BaseBundle.unparcel(BaseBundle.java:221)
          at android.os.Bundle.getBundle(Bundle.java:763)
          at com.google.android.gms.maps.internal.df.a(SourceFile:74)
          at com.google.maps.api.android.lib6.e.ev.a(Unknown Source)
          at com.google.maps.api.android.lib6.e.af.a(Unknown Source)
          at com.google.android.gms.maps.internal.w.onTransact(SourceFile:66)
          at android.os.Binder.transact(Binder.java:387)
          at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
          at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
          at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
          at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
          at com.google.android.gms.maps.MapView$zzb.zzzW(Unknown Source)
          at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
          at com.google.android.gms.dynamic.zza.zza(Unknown Source)
          at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
          at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
```

**Comment by johncarl81** [comment]
Is proguard removing that class?

**Comment by AAverin** [comment]
I am using Parceler with Kotlin - this might affect things a little, but in general I don't yet use any proguard and grabbing data from bundle in my custom class works fine - list is parsed out and working fine. It's only MapView that fails.
I already have a try/catch along many MapView methods, so project is not failing now. But still. Is it MapView that's wrong or not?

**Comment by johncarl81** [comment]
Hmm, not sure, can you put together a quick example project that I can reproduce this issue?

**Comment by johncarl81** [comment]
@AAverin, any movement on this?

**Comment by AAverin** [comment]
@johncarl81 Issue doesn't look too critical - for now I just catch an exception in my wrapper on top of MapView - there are many catches like that with google maps anyways.

**Comment by johncarl81** [comment]
Not the best solution, but it's good if it works.  Again, I think this is a proguard issue.  Let me know if you need my assistance to dig into this deeper.

**Comment by dragantl** [comment]
Hmm, just ran into the issue myself. Saving a list of Parceler annotated classes throws the same exception.

**Comment by dragantl** [comment]
Fyi, I also just took a workaround. After I restore the saved items from the bundle, I remove the key that corresponds to the List. The issue was coming from onCreate. My guess is that maps view was iterating over the bundle keys, trying to read the data.... on the side note, why would they do that... sneaky?

**Comment by johncarl81** [comment]
@dragantl, do you have a project that I may use to reproduce this error?

**Comment by dragantl** [comment]
No but I'll try to put a one today/tomorrow and will let you know.

**Comment by dragantl** [comment]
Sorry for the late reply. https://github.com/dragantl/ParcelerMaps contains basic app with one activity (it's missing a google maps API key in AndroidManifest.xml). Once the app starts, click the plus (+) option, located on the toolbar, to add a few markers. After several markers have been added, rotate your device. The application will crash.

In my original application, I was using a map within a Fragment. However, I seem to get the same result when using an Activity. If you remove the line of code which wraps a list of markers and saves it to the bundle, the app will not crash.

**Comment by johncarl81** [comment]
Thanks @dragantl!  I'll dig into you example shortly.

**Comment by johncarl81** [comment]
Right off the bat it seems you're [using proguard](https://github.com/dragantl/ParcelerMaps/blob/master/app/build.gradle#L45) but you don't have the [Parceler rules](http://parceler.org/#configuring_proguard) in place: https://github.com/dragantl/ParcelerMaps/blob/master/app/proguard-rules.pro.  Could you add these and see if it works?

**Comment by dragantl** [comment]
Ah, whoops! Sorry, I created a brand new project. I do have the following rules in the actual project where I discovered the issue:

```
# parceler
-keep class **$$Parcelable { *; }
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
-keep class org.parceler.Parceler$$Parcels
```

However, it seems that what I have may be old as the README.md now lists the following:

```
# Parcel library
-keep interface org.parceler.Parcel
-keep @org.parceler.Parcel class * { *; }
-keep class **$$Parcelable { *; }
```

**Comment by johncarl81** [comment]
Yup, we fine tuned the proguard rules around the release of 1.1.5.  Are you still seeing the mentioned error with Google Maps?

**Comment by dragantl** [comment]
Yep, just checked it. Still get the error.

**Comment by kienvtqhi** [comment]
I got the same error with the release of 1.1.5.

**Comment by johncarl81** [comment]
Thanks again for the example @dragantl, finally got a look at things.  It seems this is a sesemtic isuee with the `MapView`, which people have dealt with in different ways: http://stackoverflow.com/questions/13900322/badparcelableexception-in-google-maps-code  I don't have a fix that is possible in Parceler, all I can advise is either remove all `Parcelables` from your `Bundle savedInstanceState` or pass in a `new Bundle()` as suggested in the SO post.  I wonder what the Google devs were thinking in this spot.
