### ISSUE TITLE
Parceler should ignore final fields or provide option to ignore globally

### ISSUE THREAD

**Issue by agrosner** [johncarl81/parceler#220]
When I define a final field as such:

```
 // To prevent collisions, we use the current class for saving state.
 private final String ARG_COUNT = getClass().getSimpleName() + ":count";

 private final String ARG_BUNDLE = getClass().getSimpleName() + ":bundle";
```

I receive warnings about `warning: Parceler: Reflection is required to modify private final field`. Is there a way to ignore `final` fields in Parceler?

Thank you

**Comment by johncarl81** [comment]
Yup, either make it `transient` or annotate it with `@Transient`

**Comment by johncarl81** [comment]
And in this case you might want to make these `static final`s which would be ignored by Parceler.
