### ISSUE TITLE
Parcel abstract base classes

### ISSUE THREAD

**Issue by sevar83** [johncarl81/parceler#227]
Hi, I've got an abstract base class which has some fields I need to parcel. But Parceler generates a construction of the abstract class and of course it's not possible. Compilation fails as expected. Is there some suggested way to parcel the fields of an abstract base class? As a temporary workaround I made my base class non-abstract, but that's not good in the long term.

**Comment by sevar83** [comment]
Hm... I've just removed the `@Parcel` annotation from the abstract class and looks like it works. But is this the *official* way?

**Comment by johncarl81** [comment]
Parceler will analyze the superclasses of your annotated class and handle serialization of all properties, unless configured not to.
