### ISSUE TITLE
Wrapping/unwrapping object with map inside it alters order of the map's elements

### ISSUE THREAD

**Issue by edualonso** [johncarl81/parceler#228]
I have to wrap an instance of `MyObject`. The `MyObject` class has a `TreeMap<Integer, String> myMap` member - the order of the elements matters. Once I unwrap the object, the map is there, but the items inside it map are all messed up, and that's not good, as I need to calculate the hash of the map, and therefore I get two different hashes before wrapping it and after unwrapping it. It also restores the map as a `HashMap` object in the unwrapped object, instead of a `TreeMap`.

**Comment by johncarl81** [comment]
If you define your `Map` type as a `TreeMap` instead, Parceler will marshal to that type.  Are you concerned about order in your `Map`?

**Comment by edualonso** [comment]
Alright, so this is happening because I defined my map using the interface `Map` and not the implementation class `TreeMap`. I do care about the order in this case, but I must say, it is a rather odd scenario too.

**Comment by johncarl81** [comment]
You could also use `SortedMap` instead of `Map` and Parceler will use a `TreeMap` for the default implementation.

**Comment by edualonso** [comment]
Excellent! Thanks for the info.
