### ISSUE TITLE
Lists generated with Arrays.asList don't work

### ISSUE THREAD

**Issue by bryant1410** [johncarl81/parceler#229]
If I try the following it doesn't work:

``` java
Parcels.wrap(Arrays.asList(1, 2, 3));
```

This is because it uses a custom `List`, which is btw named `ArrayList` and is nested in `Arrays` class. I think this should be supported by Parceler.

NB: this is a private class, so the direct solution of adding an entry to `parcelableCollectionFactories` won't work. Isn't there any way to check for the base classes?

**Comment by johncarl81** [comment]
In this case you can specify the type for Parcels to wrap:
```
Parcels.wrap(List.class, Arrays.asList(1, 2, 3));
```
Here's a similar example test: https://github.com/johncarl81/parceler/blob/master/examples/test/src/test/java/org/parceler/NonParcelTest.java#L80

**Comment by johncarl81** [comment]
Can you share the details around your Dart issue?

**Comment by bryant1410** [comment]
The issue is that I have an activity with a `List` parameter annotated with `InjectExtra`. If I pass a regular list to it, it works. If I pass a list created like `Arrays.asList(1, 2, 3)`, it throws an exception in the `wrap` method.

**Comment by johncarl81** [comment]
So, the problem here is there are quite a few cases to handle.  Not only does `Arrays.asList` return a custom `List`, but so does `Collections.unmodifiableList`, `List.subList`, and others.  Maybe we should specify the type within the wrap call in Dart?

**Comment by johncarl81** [comment]
@bryant1410, is this still an issue for you?

**Comment by bryant1410** [comment]
Yes, but I did workaround it.

**Comment by bryant1410** [comment]
I'll open an issue in Dart.

**Comment by jakubkrolewski** [comment]
I have a similar problems in my code. When I put a `Collections.emptyList()` to my class, the parcelization fails. A workaround would be using `new ArrayList(0)` instead, but it doesn't look so nice in the code and it's hard to remember that for some empty list `emptyList()` can be used but it's forbidded for the classes that use the Parceler library.

**Comment by johncarl81** [comment]
Agreed @jakubkrolewski.  Maybe we should compile a list of common List implementations above the existing set.  Care to suggest some @jakubkrolewski, @bryant1410 ?

**Comment by bryant1410** [comment]
But isn't this just a `Dart` issue? Shouldn't this be solved just by casting lists to `List`?

**Comment by johncarl81** [comment]
Not really, it is resolved by generating the following:
```java
Parcels.wrap(List.class, Arrays.asList(1, 2, 3));
```
Currently Dart generates the following:
```java
Parcels.wrap(Arrays.asList(1, 2, 3));
```

**Comment by bryant1410** [comment]
Yeah, I meant sth like that

**Comment by johncarl81** [comment]
So, we've always had this problem with the Parcels utility class.  Inheritance isn't accounted for.  Maybe we should start looking at checking for implementations instead of just equality to a given class.

**Comment by bryant1410** [comment]
But not all implementations could be always taken into account.

I was trying to think in a way that inheritance could be check without using reflection, but I got nothing.

**Comment by johncarl81** [comment]
Honestly it's using reflection (albeit at a minimum) currently: via `getClass()`: https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/Parcels.java#L56 which is relatively performant.

**Comment by bryant1410** [comment]
Oh, ok. But my question is, is there a way to efficiently check for the
whole inheritance tree?

**Comment by johncarl81** [comment]
If we're to do this it would be a mix of calls to [`isInstance()`](https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#isInstance(java.lang.Object)) and perhaps caching of the result if needed.  I propose benchmarking this before we make it official.
