### ISSUE TITLE
parceler as library and application with proguard cannot build

### ISSUE THREAD

**Issue by noiz354** [johncarl81/parceler#231]
i made an example project to show library that used parceler then i had application with proguard for obfuscation get warn and failed when build.
https://github.com/noiz354/parcelertest

Here is the detail 
[parceler_obfuscate.txt](https://github.com/johncarl81/parceler/files/429932/parceler_obfuscate.txt)

are there any workaround?

**Comment by johncarl81** [comment]
Looks like the compile scope dependency is incorrect, it should be the parceler-api dependency, no the parceler annotation processor dependency.  After changing this the build completed successfully.  I've created a PR with this change here: https://github.com/noiz354/parcelertest/pull/1

**Comment by noiz354** [comment]
Great, it works
