### ISSUE TITLE
primitive type matched with constructor breaks serialization

### ISSUE THREAD

**Issue by del-flexe** [johncarl81/parceler#234]
The Parceler framework will happily write out an `int` as a primitive type, and then attempt to read that as the `Integer` wrapper type.  The specific scenario was:

* Object annotated with `@Parcel`, using Bean serialization
* Getter returning `int`
* Constructor arg of getter property name taking `Integer`

Result:

* serialization writes a single integer into the parcel for a primitive value
* deserialization reads two integers from the parcel for the wrapper type
* deserialization continues past the problem with garbage data

Expected behavior (different from result) - one of the following:

1. Parceler detects the mismatch in types and serializes using the format expected by the constructor IF ABLE (scenarios reversed should error)

2. Parceler always refuses to match primitive types with associated wrappers before generating code

Example:

```java
@Parcel(Parcel.Serialization.BEAN)
public class Victim {
  @ParcelConstructor
  public Victim(final Integer intArg, ...) { ... }

  public int getIntArg() { return 1; }
}
```

**Comment by johncarl81** [comment]
Ah, good catch!  I'll try to resolve this asap.

**Comment by johncarl81** [comment]
@del-flexe, I decied to be a little less flexable on this one, following the suggesting Expected Behavior 2.  With the referenced PR types must match identically in order for Parceler to associate them.  Would you like to test this PR out?

**Comment by johncarl81** [comment]
On second thought, supporting autoboxed types isn't that complex.  I went ahead and added it.

**Comment by del-flexe** [comment]
This is probably pretty easily-tested ... I'll take this patch as good (I'm working around it for now).

**Comment by johncarl81** [comment]
Sounds good.  Yeah, the PR is > 50% tests so I think it is well vetted.
