### ISSUE TITLE
Issue NoClassDefFoundError On Android 4.4.4, Xiaomi 2014818

### ISSUE THREAD

**Issue by imankitaman** [johncarl81/parceler#238]
Hi I was testing my code on android 4.4.4 device and while passing list of Parceler objects from one activity to another i got this crash. 
java.lang.NoClassDefFoundError: org.parceler.Parcels$ParcelCodeRepository
at org.parceler.Parcels.<clinit>(Parcels.java:34)

I am using 
compile 'org.parceler:parceler-api:1.1.5'
provided 'org.parceler:parceler:1.1.5'

**Comment by johncarl81** [comment]
Have you set up proguard with the recommended rules?

**Comment by imankitaman** [comment]
Yes, i did but still getting this error.

Added below lines to proguard configuration file
-keep interface org.parceler.Parcel
-keep @org.parceler.Parcel class * { *; }
-keep class **$$Parcelable { *; }

**Comment by johncarl81** [comment]
looks like you also aren't using the apt plugin, can you try that?

**Comment by imankitaman** [comment]
I tried adding below line in my project but still getting the same error message.
classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
apply plugin: 'com.neenbedankt.android-apt'
changed provided to apt 'org.parceler:parceler:1.1.5'

**Comment by johncarl81** [comment]
This is really strange... can you review your proguard mapping file ( -printmapping outputfile.txt) to see if the Parcels$ParcelCodeRepository is being removed?

**Comment by imankitaman** [comment]
Thank you for your reply. My Bad, I have converted my application into MultiDex to bear with 64k dex limit. Now it is working fine.
