### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by Blaisorblade** [johncarl81/parceler#239]
Are there any benchmark results comparing Parceler with Serializable and showing the generated code is still faster?
While that's certainly achievable, this blog post suggests an example where Parceler produces a huge output (bigger than Serializable):

> Parcelable/Parceler mechanism can transfer a package of 4 045 EmptyObject instances. When the Package instance is marshalled the resulting byte[] is 517 764 bytes long.

`EmptyObject` is literally empty, so that looks like a performance bug. (The blog post links the source code, and there's more going on, but the bug is not obviously invalid to a newbie like me).

http://nemanjakovacevic.net/blog/english/2015/03/24/yet-another-post-on-serializable-vs-parcelable/

I've seen https://github.com/johncarl81/parceler/tree/master/examples/performance mentioned, but haven't found any published results (and if I did figure out how to run it myself, I wouldn't know whether I get the same results). And right now I'm just doing a quick preliminary investigation.

**Comment by johncarl81** [comment]
@Blaisorblade, I encourage you to do a performance evaluation.  I have used the project you mentioned for my own benchmarks but, you are right, I have not published any polished results.  Perhaps you can evaluate and help if you find any deficiencies?
