### ISSUE TITLE
How to solve issue: error: Item is abstract; cannot be instantiated

### ISSUE THREAD

**Issue by Kolyall** [johncarl81/parceler#240]
I tried to receive list items via Parceler `compile 'org.parceler:parceler-api:1.1.5'` my code looks like:

     protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            
            List<NavItem> navItems = new ArrayList<>();
            navItems.add(new CategoryItem("CategoryItem"));
            navItems.add(new SubCatItem("SubCatItem"));
    
            NavItemsWraper wraper = new NavItemsWraper(navItems);
            Intent data = new Intent();
            data.putExtra("data", Parcels.wrap(wraper));
    
            NavItemsWraper recievedWraper = Parcels.unwrap(data.getParcelableExtra("data"));
            recievedWraper.getNavItems();
            for (NavItem item:recievedWraper.getNavItems()){
                Log.e(TAG, "onCreate: "+item.title);
            }
        }

classes:

NavItem 

    @Parcel
    public abstract class NavItem {
        public String title;
    
        public NavItem(){
    
        }
    
        public NavItem(String subCatItem) {
            this.title=subCatItem;
        }
    }

NavItemsWrapper

    @Parcel
    public class NavItemsWraper {
        private  List<NavItem> navItems;
    
        public NavItemsWraper(){
    
        }
    
        public NavItemsWraper(List<NavItem> navItems) {
    
            this.navItems=navItems;
        }
    
        public List<NavItem> getNavItems() {
            return navItems;
        }
    }

CategoryItem

    @Parcel
    public class CategoryItem extends NavItem {
        public CategoryItem(){
    
        }
        public CategoryItem(String categoryItem) {
            super(categoryItem);
        }
    }

SubCategoryItem

    @Parcel
    public class SubCatItem extends NavItem {
        public SubCatItem() {
        }
    
        public SubCatItem(String subCatItem) {super(subCatItem);}
    }

Compile error is:

    ...\app\build\generated\source\apt\debug\com\test\objs\NavItem$$Parcelable.java
    Error:(63, 26) error: NavItem is abstract; cannot be instantiated

**Comment by johncarl81** [comment]
Simply remove the `@Parcel` from the abstract class and you should be good to go.  Only concrete classes may be used with Parceler since it will try to instantiate your class.
