### ISSUE TITLE
Redundant cast warnings in generated code

### ISSUE THREAD

**Issue by WonderCsabo** [johncarl81/parceler#242]
This is not a big deal, but Parceler generated code contains lots of redundant cast warnings. Since it seems there is effort to remove/suppress all warnings in the generated code, i thought it is worth reporting this.

Example code:
`read` method:

``` java
 caseLabelViewModel$$4 .style = ((<redacted>.common.model.CaseLabelViewModel.Style)((style$$1 == null)?null:Enum.valueOf(<redacted>.common.model.CaseLabelViewModel.Style.class, style$$1)));
```

`write` method:

``` java
 for (<redacted>.common.model.AddressViewModel addressViewModel$$0 : ((java.util.List<<redacted>.common.model.AddressViewModel> ) caseViewModel$$1 .addresses)) {
```

We are using Parceler 1.1.6.

i can send much more examples with full generated and annotated classes in private, if needed.

**Comment by johncarl81** [comment]
Thanks @WonderCsabo, I believe this is enough to go on.  Somewhat related if I remeber correctly: https://github.com/johncarl81/parceler/issues/153

**Comment by johncarl81** [comment]
It looks like there were quite a few redundant casts with collection handling.  Here's the fix: https://github.com/johncarl81/parceler/pull/245/commits/80e5f152a5910ea4f0866b1477a836ed0e605c5a

If you want to test @WonderCsabo, I pushed 1.1.7-SNAPSHOT to maven central.

**Comment by johncarl81** [comment]
I believe this is finished, reopen if this is still an issue.

**Comment by WonderCsabo** [comment]
Thank you, i will check it once we update to new Parceler version.
