### ISSUE TITLE
Custom converter on parent class ignored by child class

### ISSUE THREAD

**Issue by gaultierq** [johncarl81/parceler#246]
I'm facing some problem using a custom converter on a base class : 
```java
@RunWith(RobolectricTestRunner.class)
public class TestParceler {

    @Parcel(converter = FruitConverter.class)
    static class Fruit { @Transient int price; }

    @Parcel
    static class Apple extends Fruit {}


    @Test
    public void testFruit() {
        Fruit fruit = new Fruit();
        fruit.price = 5;
        Fruit newFruit = Parcels.unwrap(ParcelsTestUtil.wrap(fruit));
        Assert.assertTrue(fruit.price == newFruit.price);
    }

    @Test
    public void testApple() {
        Apple apple = new Apple();
        apple.price = 5;
        Apple newApple = Parcels.unwrap(ParcelsTestUtil.wrap(apple));
        Assert.assertTrue(apple.price == newApple.price);
    }
}
```
testFruit passes but testApple fails.
Is this an normal behaviour ? What am I doing wrong ?
Thanks

NB: the converter:
```java
    static class FruitConverter implements ParcelConverter<Fruit> {

        @Override
        public void toParcel(Fruit input, android.os.Parcel parcel) {
            parcel.writeInt(input.price);
        }

        @Override
        public Fruit fromParcel(android.os.Parcel parcel) {
            Fruit result = new Fruit();
            result.price = parcel.readInt();
            return result;
        }
    }
```

**Comment by johncarl81** [comment]
@gaultierq, first of all, this is an excelent way to communicating your problem.  Thank you for taking the time to write up a unit test to describe your problem.

Here's the assertion error I'm seeing when I run your tests:
```
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec <<< FAILURE!
testApple(org.parceler.TestParceler)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.parceler.TestParceler.testApple(TestParceler.java:51)
        ....
```

It seems that `testApple` is failing in the comparison of `app.private == newApple.price`.  This is due to the transient price since Apple will not use the converter at the root type level.  If you remove the `@Transient` annotation the unit tests pass.  Alternatively you can write a second converter for `Apple` if you need custom serialization behavior.

**Comment by gaultierq** [comment]
> since Apple will not use the converter at the root type level

Oh ok it make sense. 
I think it is slightly surprising though :  in my project, my base class (Fruit) is contains an Object[] field, so I decided to write a custom converter for it. I was expecting all my child classes (Apple) to use this converter.

**Comment by johncarl81** [comment]
Think about it this way: the converter is used to both serialize a given object to a Parcel and to re-instantiate it to deserialize it.  How would you instantiate just a super-class of a given type?  Technically it's impossible.

**Comment by gaultierq** [comment]
ok thank you for your answers !
