### ISSUE TITLE
error: Parceler: Unable to find read/write generator for type io.realm.RealmList<backend.model.Invitation> for backend.model.ProjectInfo#invitations

### ISSUE THREAD

**Issue by mlostekk** [johncarl81/parceler#248]
I am using Parceler for FragmentArgs with RealmObjects (and Lombok) and getting the following crash.

```Error:(73, 70) error: Parceler: Unable to find read/write generator for type io.realm.RealmList<backend.model.Invitation> for backend.model.ProjectInfo#invitations``` 

My class ProjectInfo looks like this

```java
@Parcel(implementations = {ProjectInfoRealmProxy.class}, value = Parcel.Serialization.BEAN, analyze = {ProjectInfo.class})
public class ProjectInfo extends RealmObject
{
    @Getter @Setter @PrimaryKey long projectId;

    @ParcelPropertyConverter(RealmListParcelConverter.class) @Getter @Setter @Ignore RealmList<Invitation> invitations;
    @ParcelPropertyConverter(RealmListParcelConverter.class) @Getter @Setter         RealmList<Submission> submissions;
}
```

The Classes Submission and Invitation are both quite simple data structures that also extend `RealmObject`

The class `RealmListParcelConverter` looks like this:

```java
public class RealmListParcelConverter implements TypeRangeParcelConverter<RealmList<? extends RealmObject>, RealmList<? extends RealmObject>>
{
    private static final int NULL = -1;

    @Override
    public void toParcel(RealmList<? extends RealmObject> input, Parcel parcel)
    {
        parcel.writeInt(input == null ? NULL : input.size());
        if(input != null)
        {
            for(RealmObject item : input)
            {
                parcel.writeParcelable(Parcels.wrap(item), 0);
            }
        }
    }

    @Override
    public RealmList fromParcel(Parcel parcel)
    {
        int       size = parcel.readInt();
        RealmList list = new RealmList();
        for(int i = 0; i < size; i++)
        {
            Parcelable parcelable = parcel.readParcelable(getClass().getClassLoader());
            list.add((RealmObject) Parcels.unwrap(parcelable));
        }
        return list;
    }
}
```

**What am i doing wrong?**

**Comment by johncarl81** [comment]
From what I've seen Lombok doesn't play well with other annotation processors (like Parceler).  If you want to use Lombok and a Parcelable generator I'd recommend looking at [Hrisey](https://github.com/mg6maciej/hrisey).

See http://stackoverflow.com/questions/37543057/parceler-and-lombok-not-working-together

**Comment by johncarl81** [comment]
Also asked on Stackoverflow: http://stackoverflow.com/questions/40760781/parceler-unable-to-find-read-write-generator-for-type-realmlistbackend-model-i

**Comment by mlostekk** [comment]
Yep. this is the question i asked there. 

Actually i get the same error when using plain setters and getters. Its always when i use a RealmList with a RealmObject inside. Any further suggestions how to use Parceler with RealmLists?

**Comment by mlostekk** [comment]
Well, it seems that its working when i use

    @Parcel(implementations = {ProjectInfoRealmProxy.class})

instead of

    @Parcel(implementations = {ProjectInfoRealmProxy.class}, value = Parcel.Serialization.BEAN, analyze = {ProjectInfo.class})
