### ISSUE TITLE
Parceler packaging the pom files from embedded libraries

### ISSUE THREAD

**Issue by andrewlord1990** [johncarl81/parceler#250]
Currently, Parceler is including the pom files from libraries it embeds such as Guava.

This leads to issues on Android when you try to build, if you use that library yourself. Such as:

```
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.google.guava/guava/pom.properties
        File1: /Users/user/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9/guava-19.0.jar
        File2: /Users/user/.gradle/caches/modules-2/files-2.1/org.parceler/parceler/1.1.5/d6f8c6fcdbebda5a33fd3fe3aabf13bef67a9127/parceler-1.1.5.jar
```

When the library is packaged, it shouldn't include the pom files for the libraries itself, as said on the Android issue bug tracker post. https://code.google.com/p/android/issues/detail?id=194980#hc6

This fix to your project for the time being is:

```
packagingOptions {
	exclude 'META-INF/maven/com.google.guava/guava/pom.properties'
	exclude 'META-INF/maven/com.google.guava/guava/pom.xml'
}
```

But it would be good for this to not be required eventually. Thanks.

**Comment by johncarl81** [comment]
This is because we shade the dependencies of Parceler.  The main Parceler annotation processor should be defined in apt, annotationProcessor, or provided scope to avoid including these libraries in your apk.

**Comment by andrewlord1990** [comment]
I have done this, this error still exists. The only way to stop it is with the packagingOptions I listed above. The Parceler library is still including the Guava POM.

**Comment by andrewlord1990** [comment]
Found the cause. The 2 parceler dependencies were the wrong way around, so API was using apt scope and the main dependency was regular scope, instead of other way around.
