### ISSUE TITLE
Lint fail due to package used within Parceler

### ISSUE THREAD

**Issue by andrewlord1990** [johncarl81/parceler#251]
When I run lint on my project, which contains Parceler, it fails with the following Lint error:

Invalid package reference in library; not included in Android: javax.tools. Referenced from org.parceler.transfuse.gen.FilerResourceWriter

**Comment by johncarl81** [comment]
What scope are you using with the Parceler dependecy?

**Comment by andrewlord1990** [comment]
apt

**Comment by andrewlord1990** [comment]
Ohhhhh. Just noticed the dependencies are the wrong way around. So the API one is apt and the other is regular scope.
This exlains this error and the other error I reported about Guava POM file.
Sorry for this, will close both issues.

**Comment by johncarl81** [comment]
No problem @andrewlord1990, I had a feeling that was the case.  Glad it's working for you!
