### ISSUE TITLE
inefficient initial map size allocated when deserializing maps

### ISSUE THREAD

**Issue by del-flexe** [johncarl81/parceler#257]
Generated code for deserializing maps specifies a constructor argument to `HashMap` corresponding to the number of entries in the map:

```java
int int$$0 = parcel$$3 .readInt();  // <--- this is the eventual map size
HashMap<MyKey, MyValue> map$$1;
if (int$$0 < 0) {
    map$$1 = null;
} else {
   map$$1 = new HashMap<MyKey, MyValue>(int$$0);
   ...
}
```

Javadocs for the _java.util.HashMap_ type say that the above call creates a HashMap with the specified initial capacity and a default load factor of 0.75 (or 75%).  This means that the way maps are initialize **guarantees** re-hashing the items upon deserialization, specifically at the point when >= 75% of the entries are deserialized.

Expected behavior: the map can be deserialized without any re-hashing by better choice of initial capacity and load factor

**Comment by johncarl81** [comment]
This should do the trick: #263
