### ISSUE TITLE
How To: Interfaces and Concrete Implementations

### ISSUE THREAD

**Issue by rpattabi** [johncarl81/parceler#259]
In my little research I am not able to find how to make the following work with Parceler.

```
interface Token {
  String getName();
  List<Token> getChildren();
}

class AToken implements Token {
  // ...
}

class BToken implements Token {
  // ...
}

class Sequence {
  List<Token> tokens;
}
```

Now, how can I make `Sequence` Parcelable? It has list of `token`s. These tokens could be mix of `AToken` or `BToken`. I am not sure how to make Parceler pick the right token class according to Token type.

**Comment by johncarl81** [comment]
Parceler will not handle subclasses by default.  You can, however, use a converter to accomplish this task: http://parceler.org/#custom_serialization
