### ISSUE TITLE
Ordering of serialization?

### ISSUE THREAD

**Issue by guidedways** [johncarl81/parceler#260]
Is there a way to make sure the wrapping and unwrapping is done in a particular order? For example when wrapping, I'd like some properties to be wrapped first. Then when unwrapping, I'd like their order to be reversed.

I know a custom converter can be written, but then that defeats the purpose of using Parceler to begin with. An annotation that describes the serialization and deserialization order would be fantastic.

**Comment by johncarl81** [comment]
You simply can't read from the Parcel in a different order than which you wrote.  What need would this serve?

**Comment by guidedways** [comment]
Yes, true :) So I suppose is there at least a way to order the 'write' so that it can be read in the same manner? Essentially when writing, I have some properties which rely on the value of other properties. The 'setters' don't just set the value, they do more with it at times. Something like '@JsonPropertyOrder' supported by Jackson is what I'm looking for.

**Comment by johncarl81** [comment]
You could use either a `@ParcelContructor` or `@ParcelFactory` to control the order of properties set.
