### ISSUE TITLE
Kotlin data classes do not display error messages correctly

### ISSUE THREAD

**Issue by ZakTaccardi** [johncarl81/parceler#262]
```
Error:Parceler: No @ParcelConstructor annotated constructor and no default empty bean constructor found.
Error:Parceler: Types do not match for property arg0
```

I don't know the name of the class that this error is for ^^

**Comment by johncarl81** [comment]
Errors in Parceler should be reporting as line / element specific.  Here's some examples:

Gradle:

```
ExampleParcel.java:24: error: Parceler: No @ParcelConstructor annotated constructor and no default empty bean constructor found.
public class ExampleParcel {
       ^
```

Maven:

```
ExampleParcel.java:[25,8] Parceler: No @ParcelConstructor annotated constructor and no default empty bean constructor found.
```

If this is insufficient a PR here is extreemly easy.

**Comment by ZakTaccardi** [comment]
I'm not sure why I'm not getting class names then

**Comment by johncarl81** [comment]
Is your parceler annotation processor scoped to kapt?

**Comment by ZakTaccardi** [comment]
I'd assume so. Grabbing lunch now, will check when I get back. I think it
was scoped to kapt1 - I'll have to try kapt2

**Comment by ZakTaccardi** [comment]
I attached a project that shows the error.

```
@Parcel data class LeftRight(
        val left: String,
        val right: BigDecimal //big decimal is not parcelable by default, so this should throw an error
)
```

```
./gradlew clean assemble
```

Actual output:

```
Parceler: No @ParcelConstructor annotated constructor and no default empty bean constructor found.
```

Expected out:
```
LeftRight.kt:9: error: Parceler: No @ParcelConstructor annotated constructor and no default empty bean constructor found.

```
[kotlin_parceler_data_class.zip](https://github.com/johncarl81/parceler/files/736107/kotlin_parceler_data_class.zip)

**Comment by grandstaish** [comment]
This is a kapt issue. Here's the relevant YT for kapt3: https://youtrack.jetbrains.com/issueMobile/KT-15524

**Comment by johncarl81** [comment]
Thanks for the link @grandstaish.

**Comment by johncarl81** [comment]
Good to close @ZakTaccardi?
