### ISSUE TITLE
Unable to find generated class

### ISSUE THREAD

**Issue by RiteshChandnani** [johncarl81/parceler#266]
Hi there,

I have a model class named - Candidate.
I also have applied `@Parcel` annotation.
The class - `Candidate$$Parcelable` is also generated.

But when I try to convert array of candidates to parcelable it throws this exception - 

`org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for [Lcom.interviewair.interviewairforemployer.data.models.Candidate;, verify that your class is configured properly and that the Parcelable class [Lcom.interviewair.interviewairforemployer.data.models.Candidate;$$Parcelable is generated by Parceler.`

I am not getting why ";" is being added after classname.

Code:
`Candidate[] candidates;
Parcels.wrap(candidates);
`

**Comment by johncarl81** [comment]
Arrays are not handled by the Parcels.warp utility.  Instead, you could use a List of `@Parcel` annotated beans.

**Comment by RiteshChandnani** [comment]
Ok. Thanks @johncarl81 :+1:
