### ISSUE TITLE
Android-apt is obsolete

### ISSUE THREAD

**Issue by ditek** [johncarl81/parceler#267]
Please update the "Getting Parceler using Gradle" section to use annotationProcessor instead of android-apt. See https://bitbucket.org/hvisser/android-apt/wiki/Migration
I use Gradle 2.2.3 and as soon as I applied the android-apt plugin my app stopped working. This happened after just adding "apply plugin: 'com.neenbedankt.android-apt'" (haven't even used Parceler at that point).

Thanks.

**Comment by johncarl81** [comment]
I updated this a while ago:
https://github.com/johncarl81/parceler/commit/fac4ae173a106a81ee0e6d43821acbefd8df52ca
https://github.com/johncarl81/parceler#getting-parceler
https://github.com/johncarl81/parceler-site/commit/a643d759a2ac95d3b20150ded19383cbb2c09b3b

But it looks like the travis build of the website didn't take:
http://parceler.org#getting_parceler

**Comment by johncarl81** [comment]
... and its fixed now.  Thanks for reporting!
