### ISSUE TITLE
Make 3rd party models parcelables

### ISSUE THREAD

**Issue by AAverin** [johncarl81/parceler#268]
Hey.
I got a bit confused by the documentation, can you help me out please?
I have a jar library with some models that are shared between Java Spring and Android projects.
On Android I need to make them parcelable.

Can I use `@ParcelClasses` somehow to do it?

**Comment by johncarl81** [comment]
Yes, `@ParcelClass` will allow you to identify a bean for which Parceler to generate a Parcelable wrapper.  There is admittedly less configuration available since you can't annotate the bean, but out of the box it should follow the Java Serialization standard.

**Comment by AAverin** [comment]
Hmm. For some reason just using @ParcelClass I'm my Application class with models coming from a jar didn't work. I'll try once again tomorrow. 
Is it enough to use annotation once in Application class or i have to annotate every class where models are used?

**Comment by johncarl81** [comment]
It should be enough to use it once.

**Comment by AAverin** [comment]
What about when I have library added as a source, can I still use @ParcelClass?

**Comment by AAverin** [comment]
So far I get this when I use ParcelClass on models coming from a jar library
`Error:Parceler: Unable to find read/write generator for type ....natives.elsie.model.article.Video for ...data.articles.model.VideoData.articleVideo`

**Comment by AAverin** [comment]
Issue is resolved – I forgot to include all the inner models as ParcelClasses
