### ISSUE TITLE
@ParcelClass doesn't work for class in separate module with annotated constructor parameter

### ISSUE THREAD

**Issue by lwasylkowski** [johncarl81/parceler#273]
If I create two modules (`app` and `library`) and try to process models in `library` module from `app` using `ParcelClass` annotation, then everything works up until my model has a parameter annotated with any annotation. Then Parceler fails with 
```
error: Parceler: No corresponding property found for constructor parameter arg0
error: Parceler: No corresponding property found for constructor parameter arg1
error: Parceler: No corresponding property found for constructor parameter arg2
...
```

**Comment by johncarl81** [comment]
Ah, you'll most likely need to annotate the constructor parameters with `@ParcelProperty`.  Java discards the names of constructor and method arguments after compilation, unfortunately.

**Comment by lwasylkowski** [comment]
That's what I do now. But why does the version without annotation work, then?

**Comment by johncarl81** [comment]
Is this still an issue for you @lwasylkowski ?

**Comment by lwasylkowski** [comment]
Yes, as soon as class in the other module has any annotation, every constructor parameter requires `ParcelProperty` annotation as well.

I've been told it's javac issue, but I can't tell why the annotation changes anything

**Comment by johncarl81** [comment]
Hmm, I'm trying to reproduce this without success.  What version of Parceler are you using?  Can you provide a minimal example project of this failing?

**Comment by lwasylkowski** [comment]
Sure. https://github.com/lwasylkowski/parceler_report_237 Try adding and removing the annotation for ctor parameter in `OtherModuleClassWithString` and building `app` module. The weird naming is because initially I thought this is Kotlin issue, and Parceler would complain when there was String parameter for a class. Turns out it's just that Kotlin was adding nullability annotations which triggered this issue.

**Comment by johncarl81** [comment]
Ok, this is weird... if you remove the `@Depreciated` annotation, then parceler is able to pair the constructor inputs to the getter properties.

**Comment by lwasylkowski** [comment]
That's exactly the issue. https://youtrack.jetbrains.com/issue/KT-16792 There's also some discussion here, Yan suggests it's a `javac` bug

**Comment by johncarl81** [comment]
Looks like the related kotlin issue is resolved.  If not feel free to reopen.
