### ISSUE TITLE
Kotlin Data Class Requires Reflection for non-private field

### ISSUE THREAD

**Issue by samwoodall** [johncarl81/parceler#275]
Example Code
`@Parcel
data class TestParcel(val deleteMe: String? = null)`

Warning when running tests 
`Parceler: Reflection is required to modify private final field: String deleteMe, consider using non-private and non-final.`

`private final java.lang.String deleteMe = null;`

After searching through others issues using @Parcel(Parcel.Serialization.BEAN) seems to remove the warning but passing the TestParcel from an android activity to another as an intent extra results in null at the receiving activity.

**Comment by johncarl81** [comment]
You can use `@ParcelConstructor` on the constructor to tell Parceler to use it to "write".

**Comment by samwoodall** [comment]
Thank you very much, this seemed to fix the issues that I was having although now the default constructors can't be used. I can use 
`@Parcel(value = Parcel.Serialization.BEAN)
data class TestParcel @ParcelConstructor constructor(val deleteMe?: String) {
    constructor() : this(null)
}` 
Although not `@Parcel(value = Parcel.Serialization.BEAN)
data class TestParcel @ParcelConstructor constructor(val deleteMe?: String = null) `
