### ISSUE TITLE
Using @ParcelClass is generating Parcelable class under the wrong package

### ISSUE THREAD

**Issue by ahasbini** [johncarl81/parceler#278]
I'm using the @ParcelClass annotation to wrap the Stack class since it implements the Collections interface. Here's my implementation:

```
import android.os.Parcel;

import com.example.app.utils.Logger;

import org.parceler.ParcelClass;
import org.parceler.Parcels;
import org.parceler.converter.CollectionParcelConverter;

import java.util.Stack;

/**
 * Parceler converter for generic {@link Stack}
 * Created by Ahmad Hasbini on 06/04/2017.
 */

@ParcelClass(value = Stack.class,
        annotation = @org.parceler.Parcel(converter = StackParcelConverter.class))
public class StackParcelConverter<T> extends CollectionParcelConverter<T, Stack<T>> {

    private static final String TAG = StackParcelConverter.class.getSimpleName();

    @Override
    public void itemToParcel(T input, Parcel parcel) {
        parcel.writeString(input.getClass().getName());
        parcel.writeParcelable(Parcels.wrap(input), 0);
    }

    @Override
    public T itemFromParcel(Parcel parcel) {
        try {
            return Parcels.unwrap(
                    parcel.readParcelable(
                            Class.forName(parcel.readString())
                                    .getClassLoader()));
        } catch (ClassNotFoundException e) {
            Logger.LogW(TAG, "itemFromParcel: error occurred while reading parcel", e);
        }
        return null;
    }

    @Override
    public Stack<T> createCollection() {
        return new Stack<>();
    }

    @Override
    //NOTE: had to override the method, without it the compilation was generating an incompatible type error.
    public Stack<T> fromParcel(Parcel parcel) {
        return super.fromParcel(parcel);
    }
}
```

I'm getting the following exception while running the application:
```
org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for java.util.Stack, verify that your class is configured properly and that the Parcelable class java.util.Stack$$Parcelable is generated by Parceler.
                                                                    at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:153)
```

I have checked the generated files and found that ```Stack$$Parcelable``` is generated but within the ```java_.util``` package (there's an underscore within the package name but Parceler is looking for ```java.util``` without the underscore).

Here's my ```build.gradle``` config:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.app"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 2
        versionName "1.0.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true

        javaCompileOptions {
            annotationProcessorOptions {
                argument('dart.henson.package', 'com.example.app')
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])



    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.f2prateek.dart:dart:2.0.1'
    compile 'com.f2prateek.dart:henson:2.0.1'
    compile 'org.parceler:parceler-api:1.1.6'
    compile 'com.jakewharton:butterknife:8.5.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.google.code.gson:gson:2.8.0'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    annotationProcessor 'org.parceler:parceler:1.1.6'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
    provided 'com.f2prateek.dart:dart-processor:2.0.1'
    provided 'com.f2prateek.dart:henson-processor:2.0.1'
}
```

**Comment by johncarl81** [comment]
Nice approach with the converter!

Adding the underscore was on purpose.  This was to avoid a `SecurityException` when generating classes.

I've tried your converter locally and it works just fine.  Are you defining the `@ParcelClass` annotation in the same project where it is used?

Btw, you should just need to reference the Stack's classloader instead of using reflection in your `itemFromParcel` method:
```java
    public T itemFromParcel(android.os.Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable(Stack.class.getClassLoader()));
    }
```

Good point on the `fromParcel` override.  The generics behind these converteres have some issues and need some attention.

**Comment by ahasbini** [comment]
> Are you defining the @ParcelClass annotation in the same project where it is used?

It's within the same project but within different packages of the project. Also I'm not sure how to use it further or apply it. I've placed the annotation as in the implementation that I've made, above the ```StackParcelConverter<T>``` declaration:
```
@ParcelClass(value = Stack.class,
        annotation = @org.parceler.Parcel(converter = StackParcelConverter.class))
```
Doesn't that automatically register the converter for all ```Stack``` variables? You know like the ```GsonBuilder.registerTypeAdapter()```, pass in the serializer/deserializer converter and the custom class as parameters and it'll automatically use the converter when its serializing/deserializing a variable of the custom class type.

Meaning what I have done is simply in another class I had a ```Stack``` variable and applied ```Parcels.wrap()``` on it. Should I annotate that variable with a certain annotation?

```
public class SomeActivity {

    @Parcel
    enum States {
        ...
    }

    private Stack<States> stateStack = new Stack<>();

    private void someMethod() {
        ...
        Parcels.wrap(stateStack);
        ...
    }
}
```
In case this helps, here is how the classes are placed underneath the root package folder:
```
-com.example.app
    |-activities
    |   |-SomeActivity
    |
    |-utils
        |-parsers
               |-StackParcelConverter
```
Also thanks for your comments and help, appreciate it and will give classloader a try.

**Comment by johncarl81** [comment]
Ah, ok, that makes more sense.  I guess we don't respect the package mapping within the Parcels utility class.  For the time being you can use the generated Parcelable directly:
```java
new Stack$$Parcelable(stack)
```
So, the obvious fix is to add some logic into the reflection lookup in Parcels... or natively handle Stack.

**Comment by ahasbini** [comment]
@johncarl81 thanks for the help it worked as you stated, using the generated Parcelable directly. Although I would've preferred to use the ```wrap()``` and ```unwrap()``` but it'll do for now :P

Here's a sample code for people who are facing the same issue:

Wrapping into ```Bundle``` in ```Activity,onSaveInstanceState()```:
```
    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putParcelable("stack", new Stack$$Parcelable(statesStack));
    }
```

Unwrapping from ```Bundle```:
```
    private void restoreFromSavedState(Bundle savedInstanceState) {
        //For some reason a NPE warning was showing when using method getParcel
        if (savedInstanceState.getParcelable("stack") != null) {
            stateStack = ((Stack$$Parcelable) savedInstanceState.getParcelable("stack")).getParcel();
        }
    }
```

I've looked into your previous comment regarding the ```getClassLoader```:

> Btw, you should just need to reference the Stack's classloader instead of using reflection in your itemFromParcel method:
```
    public T itemFromParcel(android.os.Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable(Stack.class.getClassLoader()));
    }
```

Doesn't ```getCloassLoader()``` here return ```Stack``` class type instead of the generic class type ```T``` in ```Stack<T>```?

**Comment by johncarl81** [comment]
I'm with you @ahasbini, I don't like referencing generated code if I don't have to.

Ah, my mistake, I hope there would be a way to avoid the reflection call though to look up the associated classloader.  Maybe reference the `ParcelConverter`classloader?

**Comment by ahasbini** [comment]
@johncarl81, your suggestion worked but it sort of surprised me and got me to think and dig more into it.

First, I had to manually use the ```StackParcelConverter<T>``` to test the suggestion as within the previous implementation ```Parcels.unwrap()``` was not used and instead unwrapping was done as in my previous comment. Here's the test code that I've used, took me a while to figure out as I had no experience dealing with ```Parcel``` objects directly:
```
Logger.LogI(TAG, "onClick: testing");
Logger.LogI(TAG, "onClick: statesStack: " + statesStack);
android.os.Parcel parcel = android.os.Parcel.obtain();
Logger.LogI(TAG, "onClick: parcel.dataSize(): " + parcel.dataSize() + ", parcel.dataPosition(): " + parcel.dataPosition());
StackParcelConverter<States> statesStackParcelConverter = new StackParcelConverter<>();
statesStackParcelConverter.toParcel(statesStack, parcel);
parcel.setDataPosition(0);
Logger.LogI(TAG, "onClick: parcel.dataSize(): " + parcel.dataSize() + ", parcel.dataPosition(): " + parcel.dataPosition());
Stack<States> tempStatesStack = statesStackParcelConverter.fromParcel(parcel);
Logger.LogI(TAG, "onClick: tempStatesStack: " + tempStatesStack);
Logger.LogI(TAG, "onClick: parcel.dataSize(): " + parcel.dataSize() + ", parcel.dataPosition(): " + parcel.dataPosition());
parcel.recycle();
Logger.LogI(TAG, "onClick: finished");
```

I've placed the above code inside ```OnClickListener``` of a ```Button```.

And here's the final implementation of ```StackParcelConverter<T>``` using the ```getClassLoader``` instead:
```
package com.example.app.utils.parsers;

import android.os.Parcel;

import com.example.app.utils.Logger;

import org.parceler.ParcelClass;
import org.parceler.Parcels;
import org.parceler.converter.CollectionParcelConverter;

import java.util.Collection;
import java.util.Stack;

/**
 * Parceler converter for generic {@link Stack}
 * Created by Ahmad Hasbini on 06/04/2017.
 */

@ParcelClass(value = Stack.class,
        annotation = @org.parceler.Parcel(converter = StackParcelConverter.class))
// TODO: 09/04/2017 Ahmad Hasbini: test the class using the class loader to get the generic type instead of using reflection
public class StackParcelConverter<T> extends CollectionParcelConverter<T, Stack<T>> {

    private static final String TAG = StackParcelConverter.class.getSimpleName();

    @Override
    public void itemToParcel(T input, Parcel parcel) {
        Logger.LogI(TAG, "itemToParcel: called");
        parcel.writeParcelable(Parcels.wrap(input), 0);
    }

    @Override
    public T itemFromParcel(Parcel parcel) {
        Logger.LogI(TAG, "itemFromParcel: called");
        Logger.LogI(TAG, "itemFromParcel: getClass: " + this.getClass());
            return Parcels.unwrap(
                    parcel.readParcelable(this.getClass().getClassLoader()));
    }

    @Override
    public Stack<T> createCollection() {
        Logger.LogI(TAG, "createCollection: called");
        return new Stack<>();
    }

    @Override
    //NOTE: had to override the method, without the compilation was generating an incompatible type error.
    public Stack<T> fromParcel(Parcel parcel) {
        Logger.LogI(TAG, "fromParcel: called");
        return super.fromParcel(parcel);
    }

    @Override
    public void toParcel(Collection<T> input, Parcel parcel) {
        Logger.LogI(TAG, "toParcel: called");
        super.toParcel(input, parcel);

    }
}
```

And it worked, here's the output log:
```
04-09 12:29:49.270 I/MainActivity: onClick: testing
04-09 12:29:49.270 I/MainActivity: onClick: statesStack: [CARDS]
04-09 12:29:49.270 I/MainActivity: onClick: parcel.dataSize(): 0, parcel.dataPosition(): 0
04-09 12:29:49.271 I/StackParcelConverter: toParcel: called
04-09 12:29:49.271 I/StackParcelConverter: itemToParcel: called
04-09 12:29:49.271 I/MainActivity: onClick: parcel.dataSize(): 144, parcel.dataPosition(): 0
04-09 12:29:49.273 I/StackParcelConverter: fromParcel: called
04-09 12:29:49.273 I/StackParcelConverter: createCollection: called
04-09 12:29:49.273 I/StackParcelConverter: itemFromParcel: called
04-09 12:29:49.273 I/StackParcelConverter: itemFromParcel: getClass: class com.example.app.utils.parsers.StackParcelConverter
04-09 12:29:49.274 I/MainActivity: onClick: tempStatesStack: [CARDS]
04-09 12:29:49.274 I/MainActivity: onClick: parcel.dataSize(): 144, parcel.dataPosition(): 144
04-09 12:29:49.274 I/MainActivity: onClick: finished
```

But I have a question, I've always new from my experience that it is difficult to get the generic type class within a generic class, does this mean that ```getClassLoader()``` has means of getting it easily, and how? Doesn't it do reflection too? There is are methods in ```ClassLoader``` that seem to provide that but I'm not sure how they work.

Thanks a lot for your help and suggestions, I could consider this issue to be solved.

**Comment by johncarl81** [comment]
Oh, and to save you a bit of code, you can use `Parcels.unwrap` instead of the manual unwrapping code you used: https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/Parcels.java#L86-L92

Maybe this is an obvious statement, but `getClassLoader()` only matters if it returns a different classloader than the one used originally with the given class.  The community of `Parcelable` generators have had a variety of issues around this and (I'm not 100% sure on this) it seems to be related to multidexing your apk and how classes are loaded from separate apks.  Therefore, referencing the Classloader for "`this`" class may not work.  Possibly this requires you to store the class name and do a reflection lookup as your code originally did.  Honestly, I'd love some more analysis on this and feedback from you.

Somewhat of a side point, but related to your testing, you could use the following code along with Robolectric to test the roundtrip serialization of `Parcelables` within a unit test in regular Java: 
https://github.com/johncarl81/parceler/blob/master/examples/test/src/test/java/org/parceler/ConverterTest.java#L47
ParcelsTestUtil:
https://github.com/johncarl81/parceler/blob/master/examples/test/src/test/java/org/parceler/ParcelsTestUtil.java

**Comment by johncarl81** [comment]
And to answer your questions directly:
I've always knew from my experience that it is difficult to get the generic type class within a generic class, does this mean that getClassLoader() has means of getting it easily, and how
> I don't believe generics affect which classloader you're using unless its the classloader of the contained generic type.
Doesn't it do reflection too? There are methods in ClassLoader that seem to provide that but I'm not sure how they work.
> Not sure about this one, but probably not something you should worry about since it can't be avoided.
