### ISSUE TITLE
"Duplicate Zip Entry" caused by XXX$$PackageHelper.class

### ISSUE THREAD

**Issue by onurtok** [johncarl81/parceler#282]
When we try to `@Parcel` a class which extends also `@Parcel` annotated class in library, we have encountered awkward problem. Issue is;

We have `Car` class in our Library project, `Car` is annotated with `@Parcel`. 
We also have some other classes which extends `Car` in our Library Project. For instance `Sedan extends Car`, `Hatchback extends Car` etc, all of them annotated with `@Parcel`. Since these classes are not in the same package with `Car`, parceler also generates `Car$$PackageHelper` class to access 'protected/package protected' fields of `Car`. 

Until now, everything works perfectly. We use all of the classes in our client project dependent on Library, without any problem. 

However, we also have some classes extends `Car` in our client project  (`SUV extends Car`, `MiniVan extend Car` etc.). 

When we annotate these classes -in client project- with `@Parcel`, parceler generates related classes like `SUV$$Parcelable`, `MiniVan$$Parcelable`. But it also generates `Car$$PackageHelper`, which is already generated in Library. This caused "Duplicate zip entry" when we try to run project.

**Comment by johncarl81** [comment]
Hmm, could you generate the parcelables from only one project, like your main project?

**Comment by abangfadli** [comment]
I also encounter this issues.
We have a library module `common` which has `BaseViewModel` annotated with `@Parcel`. Then in another library module `featureA` it extends `BaseViewModel` and the same error message appears.

It only appears when building from gradle though, no problem building via AS.

**Comment by abangfadli** [comment]
Here's to repro with simple project:
Create `TheClass` in module library. Create `TheClassA` in module library, but in different package. Create `TheClassB` in `app` module. Run `assembleDebug`.

**Comment by letitfly** [comment]
I have the same problem. Any easy fix?

**Comment by letitfly** [comment]
In my case, the base class is not even annotated with @pacel

library common:
  class Base {}

library A:
 @parcel class A extends Base {}

library B:
 @parcel class B extends Base {}

**Comment by johncarl81** [comment]
You have a few low hanging fruit fixes:

1.  Use public fields or getters/setters with `BEAN` configuration.
2.  Use a different package for your libraries.
3.  Only generate Parcelables from your root Android project, not your library(ies), using `@ParcelClass`.

**Comment by abangfadli** [comment]
Could you elaborate more on the 2nd option? We do have different package for the libraries (com.theapp.android.library) and the main app (com.theapp.android)

**Comment by johncarl81** [comment]
@abangfadli, I think I misspoke on the 2nd option... using a different package makes no difference.  You should probably shoot for option 3 or compose your beans instead of extending them.
