### ISSUE TITLE
Build error on upgrade from 1.1.6 -> 1.17

### ISSUE THREAD

**Issue by justincpollard** [johncarl81/parceler#283]
Just tried upgrading from v1.1.6 to v1.1.7, but encountered a build error upon upgrading:

> Error:(196, 82) error: initialHashMapCapacity(int) is not public in MapsUtil; cannot be accessed from outside package

Let me know if other information would be of use!

**Comment by johncarl81** [comment]
Shoot, looks like it is package private... 1.1.8 incoming

**Comment by johncarl81** [comment]
https://github.com/johncarl81/parceler/commit/d2b27ccf3c28665389517d6b3ce5026e59bead86

**Comment by justincpollard** [comment]
Thanks :-)
