### ISSUE TITLE
Set serialization technique in config

### ISSUE THREAD

**Issue by kihaki** [johncarl81/parceler#285]
We are using Lombok together with Parceler. All our classes use Serialization.BEAN to make use of lombok getters and setters. 

It would be nice to avoid spelling out the serialization method in every `@Parcel` annotation.

Is there a way to set this as default serialization technique in a config to avoid writing it into every `@Parcel` annotation?

**Comment by johncarl81** [comment]
I think this sort of global configuration may be a bit misleading as the default parameter on the annotation is `FIELD`: https://oss.sonatype.org/service/local/repositories/releases/archive/org/parceler/parceler-api/1.1.8/parceler-api-1.1.8-javadoc.jar/!/index.html

I think the added complexity of having a global configuration would outweigh the savings of not having to specify the serialization parameter.

Are you having success with Lombok? My previous experience with Lombok and other annotation processors showed it was difficult to get them to play well together.

A little historical note, Parceler originally defaulted to BEAN serialization.  We changed it to FIELD to match Android's style.

**Comment by kihaki** [comment]
Thanks for the quick answer John,

In our case we use about 200 @Parcel annotated classes, that all use private fields in combination with the @Data annotation of Lombok. When using the Serialization.BEAN parameter parceler uses the generated getters and setters without any issues (really liking how well this works tbh).

Since this is our default modus operandi we have to specify the Serialization.BEAN parameter for every class though or parceler will use reflection.

I don't think it would be too confusing if there is a way to set a global serialization technique parameter. For example for lombok we can set global parameters in a lombok.config file. A similar parceler.config file could be introduced to set global parameters in the same way. This would be a huge help for combining parceler with lombok and would prevent developers from forgetting to set the correct Serialization parameter when introducing new classes.

Since we combine with lombok we never use the FIELD serialization in our project.

**Comment by johncarl81** [comment]
I'll tell you what, if you put together a PR then I'll consider the change.  You can always for the project to create your own variant!
