### ISSUE TITLE
Object cannot be converted to XXX error

### ISSUE THREAD

**Issue by neworld** [johncarl81/parceler#286]
After upgrade 1.1.6 -> 1.1.8, I am not able to compile. I am getting such errors:
```
error: incompatible types: Object cannot be converted to DiscountElement
                for (xxx.DiscountElement discountElement$$0 : InjectionUtil.getField(List.class, xxx.BundleDiscount.class, bundleDiscount$$1, "discounts")) {
```

Generated code looks like:
```
for (xxx.DiscountElement discountElement$$0 : InjectionUtil.getField(List.class, xxx.BundleDiscount.class, bundleDiscount$$1, "discounts")) {
    xxx.DiscountElement$$Parcelable.write(discountElement$$0, parcel$$1, flags$$0, identityMap$$0);
}
```

`1.1.6` generated code had casting. But, the return type should be determined automatically. To be honest, no idea why it isn't working 

- I am using kotlin with kapt3 (older kapt failing the same)
- Also, my code is in the module
- 1.1.7 also fails the same

Maybe I miss something?

**Comment by johncarl81** [comment]
Ah, thanks for reporting @neworld, I was able to reproduce.  FYI, it should work with a non-private field.

**Comment by johncarl81** [comment]
Ok, I think I have a fix here: https://github.com/johncarl81/parceler/pull/287 which I've deployed to maven central under 1.1.9-SNAPSHOT.  Care you give it a try?

**Comment by neworld** [comment]
It seems working. Thanks, @johncarl81.

**Comment by johncarl81** [comment]
Great!  Thanks for verifying @neworld.  I'll try to issue a point release of this update soon.
