### ISSUE TITLE
Different source file creation from 1.1.6 to 1.1.7 (or 1.1.8)

### ISSUE THREAD

**Issue by carmas123** [johncarl81/parceler#290]
I've a big problem when I try to upgrade from 1.1.6 to majior build version.
When I use an ArrayList<myClass> this is the result with new version that compile with error
`for (com.myapp.data.MyItemClass myItemClass$$0 : InjectionUtil.getField(java.util.ArrayList.class, com.myapp.data.MyClass.class, myClass$$1, "items")) {
`

> Error:(66, 119) error: incompatible types: Object cannot be converted to MyItemClass

before that with 1.1.6 all work fine:
`for (com.myapp.data.MyItemClass myItemClass$$0 : ((java.util.ArrayList<com.myapp.data.MyItemClass> ) InjectionUtil.getField(java.util.ArrayList.class, com.myapp.data.MyClass.class, myClass$$1, "items")))`

**Comment by carmas123** [comment]
Thanks

**Comment by winardi** [comment]
I have same problem, but after I try the 1.1.9-SNAPSHOT, the problem still persist (and I don't see InjectionUtil used there).
The code has error:
error: incompatible types: Object cannot be converted to DialogButtonItem

Here is the code generated in 1.1.6:
for (com.myapp.DialogButtonItem dialogButtonItem$$0 : ((List<com.myapp.DialogButtonItem> ) com.myapp.CustomViewDialogViewModel$$PackageHelper.accessCustomViewDialogViewModel$FG$mDialogButtonItemList(simpleDialogMessage$$1))) {
    com.myapp.DialogButtonItem$$Parcelable.write(dialogButtonItem$$0, parcel$$1, flags$$0, identityMap$$0);
}

And here is the code generated in 1.1.9-SNAPSHOT:
for (com.myapp.DialogButtonItem dialogButtonItem$$0 : com.myapp.CustomViewDialogViewModel$$PackageHelper.accessCustomViewDialogViewModel$FG$mDialogButtonItemList(simpleDialogViewModel$$1)) {
    com.myapp.DialogButtonItem$$Parcelable.write(dialogButtonItem$$0, parcel$$1, flags$$0, identityMap$$0);
}

**Comment by johncarl81** [comment]
Just released 1.1.9 with the fix.  Let me know if this is still an issue.
