### ISSUE TITLE
External configuration w/ ParcelClass and ParcelConstructor

### ISSUE THREAD

**Issue by HolySamosa** [johncarl81/parceler#295]
I'm trying to use `@ParcelClass` to configure Parceler support for some simple POJO that I cannot annotate.

Is there a way to specify the ParcelConstructor for these POJOs externally or do I need to use a converter?  If a converter is needed, does Parceler offer any support with a simple reflection conversion or would I need to write a manual converter for each object?

**Comment by johncarl81** [comment]
Technically your Java Bean POJO should have a default empty constructor following the JavaBean standard https://en.wikipedia.org/wiki/Plain_old_Java_object.  But, no, we don't have a way currently to define a constructor to use via the `@ParcelClass` annotation.

**Comment by 1fexd** [comment]
Hello,

I just found this issue via Google and was wondering if there was any way to parcelize a class which does not have an empty default constructor with the `@ParcelClass` annotation?

**Comment by johncarl81** [comment]
@gringofe, if you're not able to annotate the class directly, I'd recommend using a `ParcelConverter` to call the constructor, and getters/fields accordingly.
