### ISSUE TITLE
Manually parcel/unparcel @Parcel-annotated classes and ignoring class fields

### ISSUE THREAD

**Issue by markcerqueira** [johncarl81/parceler#296]
Hi! Thanks for writing this great library. I've got two questions:

1. Is it possible to manually parcel and unparcel classes annotated with `@Parcel`? I am writing tests to ensure objects are parcelled and unparcelled correctly so when I had my own creators I could do something like:

```
// Adapted from https://stackoverflow.com/a/14548276/265791
protected <T> T parcelAndUnparcel(@NonNull Parcelable parcelable, @NonNull Parcelable.Creator<T> creator) {
	// Obtain a Parcel object and write the parcelable object to it
	Parcel parcel = Parcel.obtain();
	parcelable.writeToParcel(parcel, 0);

	// Reset the parcel for reading
	parcel.setDataPosition(0);

	// Reconstruct object from parcel and return
	return creator.createFromParcel(parcel);
}
```

How would one go about manually parcelling and unparcelling a class annotated with `@Parcel`? 

2. Is it possible to flag fields of a class so that parceler ignores them? Something like `@SkipParceling` or `@ParcelIgnore`? 

Thanks again! 👍

**Comment by johncarl81** [comment]
Yes, this is done in some of the unit tests in the examples: [ConverterTest.java](https://github.com/johncarl81/parceler/blob/master/examples/test/src/test/java/org/parceler/ConverterTest.java#L47)

See: [ParcelsTestUtil.java](https://github.com/johncarl81/parceler/blob/master/examples/test/src/test/java/org/parceler/ParcelsTestUtil.java)

You'll need Robolectric in this case to provide an implementation for `Parcel`.

**Comment by markcerqueira** [comment]
@johncarl81 Awesome. Thank you!
