### ISSUE TITLE
Parcel a RealmObject with a RealmList variable - set ParcelPropertyConverter at ParcelConstructor?

### ISSUE THREAD

**Issue by endy-s** [johncarl81/parceler#297]
Hello!

I'm developing an application that is likely a "running tracker", and I want to use Parceler to send the tracked info at one activity for another one, and also save this using Realm. 
Since it tracks the location, I need to use a `RealmList` with another `RealmObject` just to store the latitude and longitude, and that's where my problem is.

I'm using the `@ParcelPropertyConverter` and it's actually running ok, but I want to use a constructor that allow me to set everything in one line of code, and I could not achieve how to do this.

There is my classes:

1. RunInfo - Contains all the Info tracked at one activity (and the commented constructor that I want to use)
```Java
@Parcel
public class RunInfo extends RealmObject {
    private String distance, duration, kcal, date, speed;
    @ParcelPropertyConverter(TrackListParcelConverter.class)
    private RealmList<TrackingPoints> track;

    public RunInfo() {
    }

//    @ParcelConstructor
//    public RunInfo(String distance, String duration, String kcal, String date, String speed,
//                  RealmList<TrackingPoints> track) {
//        this.distance = distance;
//        this.duration = duration;
//        this.kcal = kcal;
//        this.date = date;
//        this.speed = speed;
//        this.track = track;
//    }

    public String getDistance() {
        return distance;
    }

    public String getDuration() {
        return duration;
    }

    public String getKcal() {
        return kcal;
    }

    public String getDate() {
        return date;
    }

    public String getSpeed() {
        return speed;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public void setKcal(String kcal) {
        this.kcal = kcal;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public void setSpeed(String speed) {
        this.speed = speed;
    }

    public RealmList<TrackingPoints> getTrack() {
        return track;
    }

    public void setTrack(RealmList<TrackingPoints> track) {
        this.track = track;
    }
```

2. TrackingPoints - Used to store latitude and longitude
```Java
@Parcel
public class TrackingPoints extends RealmObject {
    private double latitude;
    private double longitude;

    public TrackingPoints() {
    }

    @ParcelConstructor
    public TrackingPoints(double latitude, double longitude) {
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public double getLatitude() {
        return this.latitude;
    }

    public double getLongitude() {
        return this.longitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
}
```

3. RealmListParcelConverter
```Java
public abstract class RealmListParcelConverter<T extends RealmObject> extends CollectionParcelConverter<T, RealmList<T>> {
    @Override
    public RealmList<T> createCollection() {
        return new RealmList<T>();
    }
}
```

4. TrackListParcelConverter
```Java
public class TrackListParcelConverter extends RealmListParcelConverter<TrackingPoints> {

    @Override
    public void itemToParcel(TrackingPoints input, android.os.Parcel parcel) {
        parcel.writeParcelable(Parcels.wrap(input), 0);
    }

    @Override
    public TrackingPoints itemFromParcel(android.os.Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable(TrackingPoints.class.getClassLoader()));
    }
}
```

There is some way to use the commented constructor at RunInfo class?

Thanks in advance!

Ps.: I could use only Realm to store in one activity and fetch at the other, but I wanted to use parceler to avoid unnecessary processing.

**Comment by johncarl81** [comment]
Is Parceler erroring when you uncomment the constructor?

**Comment by endy-s** [comment]
Yes, when I try to compile it shows me:
Error:(27, 59) error: Parceler: Unable to find read/write generator for type io.realm.RealmList<com.br.octo.board.models.TrackingPoints> for io.realm.RealmList<com.br.octo.board.models.TrackingPoints> track

**Comment by johncarl81** [comment]
Hmm, I was able to build this no problem.  What version of Parceler are you using?

**Comment by endy-s** [comment]
1.1.8:
```java
compile 'org.parceler:parceler-api:1.1.8'
annotationProcessor 'org.parceler:parceler:1.1.8' 
```

**Comment by kihaki** [comment]
https://stackoverflow.com/a/29722198/923441

There seems to be a working solution there, maybe that helps?

**Comment by endy-s** [comment]
Even with @RealmClass it returns me the same error 

`Error:(27, 59) error: Parceler: Unable to find read/write generator for type io.realm.RealmList<com.br.octo.board.models.TrackingPoints> for io.realm.RealmList<com.br.octo.board.models.TrackingPoints> track `

If I remove the 
```java
@ParcelPropertyConverter(RealmListParcelConverter.class)
``` 
from the declaration 
```java 
private RealmList<TrackingPoints> track;
```
it gives me the same error...

There is some ParcelPropertyConverter annotation for the constructor?

**Comment by johncarl81** [comment]
Ah, I think you need to define the analyze parameter to avoid serializing the RealmObject base class:
```java
@Parcel(analyze = RunInfo.class)
public class RunInfo extends RealmObject {...}

@Parcel(analyze = TrackingPoints.class)
public class TrackingPoints extends RealmObject {...}
```
Does that solve your issue @endy-s ?

**Comment by endy-s** [comment]
It has been a long time since this and I used another approach to finish the project in time (like creating an empty object and adding the info one by one).

With your comment I tried it again, and it worked... I just needed to remove the `@ParcelConstructor` above the custom constructor and it works as expected...

Thanks for the help! :)
