### ISSUE TITLE
Timestamp in @Generated annotation can cause Gradle up-to-date checks to fail

### ISSUE THREAD

**Issue by vyphan** [johncarl81/parceler#299]
Can we remove the timestamp from the @Generated annotation (or make that a configurable option)? It can cause Gradle to unnecessarily execute tasks because the generated source file changes with every build.

**Comment by johncarl81** [comment]
The date was removed a few versions ago.  Are you on the latest (1.1.9) and are you still seeing the date in the generated code?

**Comment by vyphan** [comment]
That would explain why I couldn't see where in the source code it was coming from! I was on an old version (1.1.2) -- thanks!

**Comment by johncarl81** [comment]
Here's the PR: https://github.com/johncarl81/transfuse/pull/205 and commit: https://github.com/johncarl81/transfuse/commit/785aebdfe065efbe7382b68dcacabfcf531de85f if you're interested.  It was an update in the underlying Transfuse framework.
