### ISSUE TITLE
@Transient annotation does not works on fields

### ISSUE THREAD

**Issue by pauminku** [johncarl81/parceler#300]
It seems that only works on getters and setters

**Comment by johncarl81** [comment]
If you provide an example I can help you debug it.  I'm pretty confident `@Transient` works on fields.

**Comment by pauminku** [comment]
I think I got it. @Transient annotation does not works on fields when is used in conjunction with @parcel(value = Parcel.Serialization.BEAN).
It make sense, but maybe some warning on compile time will be great.
I'm using this "value" because I'm parceling Realm objects.

Example:

    @Parcel(value = Parcel.Serialization.BEAN)
    public class ParcelTest {
        private String foo;
        @Transient
        private String bar;
    
        public String getFoo() {
            return foo;
        }
    
        public void setFoo(String foo) {
            this.foo = foo;
        }
    
        public String getBar() {
            return bar;
        }
    
        public void setBar(String bar) {
            this.bar = bar;
        }
}

generates:

    public static void write(com.wikiloc.wikilocandroid.dataprovider.dbmodel.ParcelTest parcelTest$$1, android.os.Parcel parcel$$1, int flags$$0, IdentityCollection identityMap$$0) {
        int identity$$0 = identityMap$$0 .getKey(parcelTest$$1);
        if (identity$$0 != -1) {
            parcel$$1 .writeInt(identity$$0);
        } else {
            parcel$$1 .writeInt(identityMap$$0 .put(parcelTest$$1));
            parcel$$1 .writeString(parcelTest$$1 .getBar());
            parcel$$1 .writeString(parcelTest$$1 .getFoo());
        }
    }

**Comment by johncarl81** [comment]
Ah, for `BEAN` serialization, Parceler will not analyze the fields, so, yes, in this case, you'd need to annotate the getter or setter.  If you use `FIELD` serialization `@Transient` will work on the field.

**Comment by pauminku** [comment]
Ok, consider to make some warnings in the future. Anyway, thanks for this great tool.

**Comment by johncarl81** [comment]
Yea, I've been meaning to: https://github.com/johncarl81/parceler/issues/101
