### ISSUE TITLE
XYZ$$Parcelable.class not generated for Kotlin classes

### ISSUE THREAD

**Issue by dulimarta** [johncarl81/parceler#301]
I keep getting the following error:

    org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for abc.def.MyClass, verify that your class is configured properly and that the Parcelable class abc.def.MyClass$$Parcelable is generated by Parceler.
                                                                    
when using `MyClass.kt`, but my app runs smoothly using `MyClass.java`.
    
To investigate the issue further, I created a smaller project with the following settings:

* Android Preview 3.0
* Kotlin Gradle Plugin 1.1.3-2
* Parceler 1.1.9

and two classes (Java and Kotlin)

    // org.example.Nothing.java
    @Parcel
    public class Java {
      Float x;
    }

    // org.example.NothingMore.kt
    @Parcel
    data class NothingMore(var x: Float)

Checking the build output using `find . -name \*.class | grep Nothing`, I found only the following **four** classes:

    app/build/intermediates/classes/debug/org/example/Nothing$$Parcelable$1.class
    app/build/intermediates/classes/debug/org/example/Nothing$$Parcelable.class
    app/build/intermediates/classes/debug/org/example/Nothing.class
    app/build/tmp/kotlin-classes/debug/org/example/NothingMore.class

the associated Parcelable for `NothingMore` (the Kotlin class) are not generated.
What am I missing?

**Comment by dulimarta** [comment]
Found the solution to my own problem. I was missing Kotlin annotation processor in my `build.gradle`. Adding the following plugin to my app's `build.gradle` fixed my problem:

    apply plugin: 'kotlin-kapt'

**Comment by vsl1993** [comment]
Opppoooooo

On Jul 14, 2017 8:14 PM, "Hans Dulimarta" <notifications@github.com> wrote:

Closed #301 <https://github.com/johncarl81/parceler/issues/301>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/johncarl81/parceler/issues/301#event-1164407848>, or mute
the thread
