### ISSUE TITLE
android.os.BadParcelableException: ClassNotFoundException when unmarshalling:

### ISSUE THREAD

**Issue by fvermeulen** [johncarl81/parceler#302]
What am I doing wrong?

> android.os.BadParcelableException: ClassNotFoundException when unmarshalling: **.activities.CategoryParcel$$Parcelable
                          at android.os.Parcel.readException(Parcel.java:1622)
                          at android.os.Parcel.readException(Parcel.java:1573)

I am using android studio 3.0 and kotlin in my project

```
val bundle = Bundle()
val wrapped = Parcels.wrap(CategoryParcel(1110))
bundle.putParcelable("CategoryParcel", wrapped)
val intent = Intent(context, BlueActivity::class.java)
context.startActivity(intent, bundle)
```
 CategoryParcel
```
import org.parceler.Parcel
import org.parceler.ParcelConstructor

@Parcel
class CategoryParcel @ParcelConstructor constructor(var categoryId: Int) {}
```
The app is crashing while switching to the next activity

this code is in the second activity, but it crashes because of the code in the first actitivity
```
var temp = Parcels.unwrap<CategoryParcel>(intent.getParcelableExtra("CategoryParcel"))
```

Do you see what I am doing wrong?

__
EDIT:

mhh this worked. my activity extends from an appcompatactivity
```
val wrapped = Parcels.wrap(CategoryParcel(1110))
var temp = Parcels.unwrap<CategoryParcel>(wrapped)
```

EDIT2:
got it working
```
val intent = Intent(context, BlueActivity::class.java)
intent.putExtra("bundle", bundle)
context.startActivity(intent)
```

problem was startActivity(), when I add it before to the intent and use the normal startActivity() everything is fine
```
public abstract void startActivity(Intent var1, Bundle var2);
```
thanks

**Comment by johncarl81** [comment]
What version of Parceler are you using?
