### ISSUE TITLE
Optional<T>

### ISSUE THREAD

**Issue by Artan1s** [johncarl81/parceler#305]
Is there way to add support for Optional<T> type from https://github.com/aNNiMON/Lightweight-Stream-API?
Can I write some custom converter for things like that?

I believe it should be possible in principle, cause there is collections support.

**Comment by johncarl81** [comment]
Yeah, of course it is possible.  Do you want me to implement the converters for you?

**Comment by Artan1s** [comment]
I think it would be nice to add example of implementing such a converter (for generic collection-like classes) to documentation. 
I actually strugle with where to put this converter. I see that internal collection converters are added to parcelableCollectionFactories in NonParcelRepository. But it's not clear where to put a new one outside of library. Can you point it out to me?
