### ISSUE TITLE
@Transient doesn't work with kotlin 

### ISSUE THREAD

**Issue by NeoDigi** [johncarl81/parceler#307]
Or I don't think it does.
I have a class similar to this:
```java
@Parcel(Parcel.Serialization.BEAN)
class RefService {

@Transient var latitude: Double = 0.toDouble()
        get() = config[LATITUDE]!!.toDouble()
        set(value) {
            field = value
            config.put(LATITUDE, value.toString())
        }
}
```
And I'll always get :
```
> kotlin.KotlinNullPointerException
>  at tile.RefService.getLatitude(RefService.kt:100)
> at RefService$$Parcelable.write(RefService$$Parcelable.java:64)
```

And I know it will be null, which is normal in my code, and I really don't need to parcel that part that why I want to transient it, but no matter what, parceler will try to do it

EDIT: 

Doing: 

```java
@Transient var latitude: Double = 0.toDouble()
        @Transient get() = config[LATITUDE]!!.toDouble()
        @Transient set(value) {
            field = value
            config.put(LATITUDE, value.toString())
        }
```

seems to work, so if it is indeed how it is supposed to work, you can close this issue, but I still feel like puttin the transient on the var should work by itself

**Comment by grandstaish** [comment]
Does specifying the field as the annotation target work? I.e. `@field:Transient var ...`

**Comment by NeoDigi** [comment]
No, it doesn't

**Comment by jlaunonen** [comment]
In this case, you need to annotate either the *getter* or *setter* with `org.parceler.Transient`. The `@Transient` unless explicitly otherwise defined is `kotlin.jvm.Transient`, equivalent of Java `transient` keyword, which is applicable only to fields. When using BEAN-serialization, such field-annotations are seemingly currently ignored (correct me if I'm wrong).
So, following transient BEAN-fields should work:
```kotlin
import org.parceler.Transient  // <- !

@Parcel(Parcel.Serialization.BEAN)
class AClass {

 @get:Transient
 var latitude1: Double = ...

 var latitude2: Double = ...
   @Transient
   set(value) { .... }
}
```
Of course instead of using import like above, you can declare full qualified name in the annotation.

**Comment by johncarl81** [comment]
@NeoDigi, can you provide the Java version of the offending class?  I'm wondering where the annotation is missing from.

**Comment by NeoDigi** [comment]
I'll do that next week as I'm on vacation right now.
But there is no Java version

**Comment by johncarl81** [comment]
From what I understand of kapt, it translates the given kotlin class into a Java class for annotation processing.  Isnt that correct?

**Comment by johncarl81** [comment]
Ping.
