### ISSUE TITLE
Empty $$Parcelable generated for subclasses

### ISSUE THREAD

**Issue by azyoot** [johncarl81/parceler#308]
If I have a base class:

```java
@Parcel( implementations = {SubClass.class})
public class BaseClass {
    private String baseValue = "ccc";

    @ParcelConstructor
    public BaseClass(@ParcelProperty("baseValue") String baseValue) {
        this.baseValue = baseValue;
    }

    @ParcelProperty("baseValue")
    public String getImplValue() {
        return baseValue;
    }
}
```
And a subclass:
```java
public class SubClass extends BaseClass {
    private double subValue = 4.2;

    @ParcelConstructor
    public SubClass(@ParcelProperty("baseValue") String baseValue, @ParcelProperty("subValue") double subValue) {
        super(baseValue);
        this.subValue = subValue;
    }

    @ParcelProperty("subValue")
    public double getSubValue() {
        return subValue;
    }
}
```

The generated `SubClass$$Parcelable` is a dummy class that does not have a `CREATOR`, nor does it implement the serialization logic for the `subValue`. This is the generated class:

```java
@Generated("org.parceler.ParcelAnnotationProcessor")
@SuppressWarnings({
    "unchecked",
    "deprecation"
})
public class SubClass$$Parcelable
    extends BaseClass$$Parcelable
{
  public SubClass$$Parcelable(SubClass baseClass$$0) {
        super(baseClass$$0);
    }

}
```

If I use it like `Parcels.unwrap(Parcels.wrap(subClass))` I get the original subclass instance correctly but when put it into an Intent's extra, even when specifying explicitly the `SubClass.class` to the `Parcels.wrap()` the receiver side will only deserialize it as a `BaseClass` instance, probably due to the empty `$$Parcelable` generated.

**Comment by johncarl81** [comment]
This is by design.  If you're looking for the subclass to be marshaled, you'll need to annotate it with `@Parcel` or delcare it in `@ParcelClass(SubClass.class)`.

**Comment by azyoot** [comment]
Annotating both classes with `@Parcel` causes an error during compilation as the `$$Parcelable` class already exists, but adding `@ParcelClass(SubClass.class)` to the base class did it, thanks!

**Comment by azyoot** [comment]
However, I can only add one `@ParcelClass` annotation and also I can't add multiple classes to it (as opposed to the `implementations` value of `@Parcel`)

**Comment by johncarl81** [comment]
That's why there is `@ParcelClasses`:
```java
@ParcelClasses({
    @ParcelClass(Subclass1.class),
    @ParcelClass(Subclass2.class)})
```
