### ISSUE TITLE
Unwrap is very slow

### ISSUE THREAD

**Issue by Maxxan** [johncarl81/parceler#311]
When I use Parceler, my app becomes very slow compared to native implementation of parcels in my class. It can take 3-5 seconds for a class to unwrap. Wrap function is fast though. There is a list of objects, like 50 items long, 5 strings, 1 integer and 1 Date object per item, 20 characters per string, that takes most of the time when unwrapping.
The class also contains some private static final default values, without and getters, but they should not matter, right?

(The reason that I use Parceler is due to that I use Realm database, so I've got converters for the RealmList of the items.)

What can cause the slowness and what can be done about it? What should I look for? There are public getters and setters for all member variables and the member variables are not private.

**Comment by johncarl81** [comment]
Can you share your code?

**Comment by Maxxan** [comment]
Sure, here are the important parts of the code:

```
public class VisitInfoConverter extends RealmListParcelConverter<VisitInfo> {

    @Override
    public void itemToParcel(VisitInfo input, Parcel parcel) {
        parcel.writeParcelable(Parcels.wrap(input), 0);
    }

    @Override
    public VisitInfo itemFromParcel(Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable(VisitInfo.class.getClassLoader()));
    }
}
```

```
@org.parceler.Parcel(implementations = { VisitInfoRealmProxy.class },
		value = org.parceler.Parcel.Serialization.BEAN,
		analyze = { VisitInfo.class })
public class VisitInfo extends RealmObject {
    private static final int DEFAULT_AGE = 40;
    private static final @Person.PersonType int DEFAULT_TYPE = Person.eUnknown;
    private static final @Visit.VisitType int DEFAULT_VISIT_TYPE = Visit.eUnknown;
    private static final boolean DEFAULT_STUDY = false;

	public String s1 = null;
	public Date date = null;
	public String s2 = null;
	public String s3 = null;
	public String s4 = null;
	public String s5 = null;
	public @Person.PersonType int type = DEFAULT_TYPE;
	public @Visit.VisitType  int visitType = DEFAULT_VISIT_TYPE;
	public int age = DEFAULT_AGE;
	public boolean study = DEFAULT_STUDY;

... and getter/setters for all items
```

```
@org.parceler.Parcel(implementations = { PersonRealmProxy.class },
		value = org.parceler.Parcel.Serialization.BEAN,
		analyze = { Person.class })
public class Person extends RealmObject {
	public static final int eLady = 0;
	public static final int eGentleman = 1;
	public static final int eChild = 2;
	public static final int eCouple = 3;
	public static final int eUnknown = 4;

	@IntDef({eLady, eGentleman, eChild, eCouple, eUnknown})
	public @interface PersonType {}

	public RealmList<VisitInfo> visitInfoList;

        public List<VisitInfo> getVisitInfoList() {
		return visitInfoList;
	}

	@ParcelPropertyConverter(VisitInfoConverter.class)
	public void setVisitInfoList(List<VisitInfo> visitInfoList) {
		this.visitInfoList.clear();
		this.visitInfoList.addAll(visitInfoList);
	}
```

and in the `Persons$$Parcelable.java,` this line takes very long time:
`person$$5 .setVisitInfoList(new com.my.app.converters.VisitInfoConverter().fromParcel(parcel$$3));`

**Comment by Maxxan** [comment]
.. after some further testing, then I think that Realm is the problem, not Parceler. So I close this issue. :)

**Comment by johncarl81** [comment]
Good to hear... what was the problem with Realm?

**Comment by Maxxan** [comment]
The problem was that I had some realm.execute() in the setter to write the value to realm database, and that took a long time. Now I make an if statement, checking if the object was managed by realm, and if it wasn't, then I just set the value directly. That made it much faster.
