### ISSUE TITLE
Errors using SDK 26 and Kotlin

### ISSUE THREAD

**Issue by CapnSpellcheck** [johncarl81/parceler#315]
Hi,

I am trying to use `compileSdk 26` for required features. After I switch over, I get errors:

> e: /Users/julian/AndroidStudioProjects/Twinkle/app/build/tmp/kapt3/stubs/debug/letstwinkle/com/twinkle/model/MatchPlayModel.java:21: error: annotation @ParcelPropertyConverter is missing a default value for the element 'value'
> e: 
> 
> e:     @org.parceler.ParcelPropertyConverter()

Note that my source is Kotlin, the .java is apparently a stub file.

Has anyone found a fix?

**Comment by johncarl81** [comment]
Can you share the kotlin source and java stub?
