### ISSUE TITLE
Code Generation Failed

### ISSUE THREAD

**Issue by iwansyahp** [johncarl81/parceler#316]
Hi, I get this message when rebuilding my Android project

Error:Execution failed for task ':app:compileDevBackendDebugJavaWithJavac'.
> org.parceler.transfuse.util.TransfuseRuntimeException: Unable to perform code generation

Could you help me?

**Comment by johncarl81** [comment]
What version are you using?

**Comment by iwansyahp** [comment]
I have found solution to this problem. I made same method name of binding interface in Module.
