### ISSUE TITLE
Zip Exception

### ISSUE THREAD

**Issue by rhonyabdullah** [johncarl81/parceler#318]
```java
Error:Execution failed for task ':app:transformClassesWithJarMergingForStagingDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/parceler/Parceler$$Parcels$1.class
```
I think my issue related with [issues 225](https://github.com/johncarl81/parceler/issues/225) and [issues 282](https://github.com/johncarl81/parceler/issues/282) but after looking at booth issues i'm not getting any answer.

The problem is, i have `app` and `network` module, both of module is using parceler and each module having pojo which is annotated with `@Parcel`. Every time i try to run using **release** mode the error occured. So, how can resolve this issue ?
@johncarl81

**Comment by johncarl81** [comment]
Are you running the annotation processor on both modules?

**Comment by rhonyabdullah** [comment]
Yes.

**Comment by johncarl81** [comment]
Can you run it just on the android project root?

**Comment by rhonyabdullah** [comment]
Yes i can, sorry for my very late response.

**Comment by johncarl81** [comment]
ok.

**Comment by rhonyabdullah** [comment]
So the problem still not resolved as before. But just can be avoided.
