### ISSUE TITLE
RealmList<Integer> and Parceler crash

### ISSUE THREAD

**Issue by Maxxan** [johncarl81/parceler#319]
I've got a problem with RealmList<Integer> and RealmList<String> and Parceler. I have a converter for those lists like:
```
public class IntegerConverter extends ObjectRealmListParcelConverter<Integer> {
    @Override
    public void itemToParcel(Integer input, Parcel parcel) {
        parcel.writeParcelable(Parcels.wrap(input), 0);
    }
    @Override
    public Integer itemFromParcel(Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable(Integer.class.getClassLoader()));
    }
} 

public abstract class ObjectRealmListParcelConverter<T extends Object> extends CollectionParcelConverter<T, RealmList<T>> {
    @Override
    public RealmList<T> createCollection() {
        return new RealmList<T>();
    }
}
```
but that crashes with Integer has a null class loader. The same with String.  The error: `android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.parceler.NonParcelRepository$IntegerParcelable`. How to solve that?

**Comment by johncarl81** [comment]
Hmm, probably because you're using the Integer classloader.  Perhaps try another like `IntegerConverter.class.getClassLoader()`?

**Comment by Maxxan** [comment]
Ah, that worked better! I thought I should use the class loader for the type of things I convert. For example all other converters look like:
```
public class StreetConverter extend RealmListParcelConverter<Street> {
...
public Street itemFromParcel(Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable(Street.class.getClassLoader()));
    }
...
```
so I thought it should be the same for Integer/String as well. Or do you mean that these converters for Street should be like
```
public Street itemFromParcel(Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable( StreetConverter.class.getClassLoader()));
    }
```
instead?

**Comment by johncarl81** [comment]
I believe you should use the former.
