### ISSUE TITLE
Different Parcel.Serialization from Base class

### ISSUE THREAD

**Issue by yeuristic** [johncarl81/parceler#321]
Suppose I use a library A. this library has a class called `BaseClass` that use Parceler and it's Parcel Serialization method is `Parcel.Serialization.FIELD`. I create a new class (`MyClass` extends `BaseClass`) that extends `BaseClass`. I want to use `Parcel.Serialization.BEAN` in `MyClass` but it's failed because there is no setter/getter in `BaseClass`. And if I create the setter/getter in `MyClass` it's not really solve the problem because if there's new property in BaseClass I should always create new setter/getter for it.
My question is, is it possible Parceler has different parcel treatments for `MyClass` and `BaseClass`. I expect `BaseClass`' properties parceled using `Parcel.Serialization.FIELD` and for `MyClass` it will parcel it using `Parcel.Serialization.BEAN`.

if I use `value = Parcel.Serialization.BEAN`, `analyze = {MyClass.class}`, properties from `BaseClass` will not be parceled.

Please help, thank you

**Comment by johncarl81** [comment]
Not currently.  Maybe this is a shortcoming, but I consider this a pretty exotic case.

**Comment by johncarl81** [comment]
You could accomplish this if you favor composition over inheritance:
```java
@Parcel(Parcel.Serialization.FIELD)
public class One {
    String value;
}

@Parcel(Parcel.Serialization.BEAN)
public class Two {

    One one;
    String value;

    public One getOne() {
        return one;
    }

    public void setOne(One one) {
        this.one = one;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
```
