### ISSUE TITLE
Parcel & Dagger2

### ISSUE THREAD

**Issue by worldsnas** [johncarl81/parceler#324]
I'm using dagger in project and would like to use `@Parcel` on my response models
but whenever I add the annotation above the class, project stops compiling and all the builds fail
compiler errors start with DaggerAppComponent missing(seems dagger won't work properly), and at the bottom of the log it leaves a 

> Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NullPointerException

please tell me how to make them work together 

thank you

**Comment by johncarl81** [comment]
I regularly use Parceler with Dagger and other annotation processors.  Can you give me some more details about your setup, perhaps a demonstration application?

**Comment by worldsnas** [comment]
thank you for your quick response

I have created a demo project with only one activity and model (and basic MVP boilers)

google drive link of the project
[https://drive.google.com/file/d/1cUNp4eUDbc5DffEmddKJQJMJgkhNqIQZ/view?usp=sharing](url)

GitHub repo
[https://github.com/worldsnas/parcelerissue](url)

it throws the same error the moment I add @Parcel (without it everything works fine)

thanks again for looking into it

**Comment by johncarl81** [comment]
I can't seem to build the project, but I can tell you from a cursory look that the `BaseResponse` should not compile with the generic you have defined.  Parceler needs to know the concrete type in order to generate a `Parcelable` wrapper class.  What will work, however, is defining a concrete implementation and not annotating `BaseResponse`:

```java
// not annotated
public class BaseResponse<T> {
...
}
```
```java
@Parcel
public class ConcreteResponse implements BaseResponse<String> {
...
}
```
Does this solve your issue?

**Comment by johncarl81** [comment]
Ah, got it to build and I see the issue:
```
$ ./gradlew clean installDebug

> Task :app:compileDebugJavaWithJavac FAILED
~/parcelerissue/app/src/main/java/com/itparsa/parcelerissue/mvp/App.java:8: error: cannot find symbol
import com.itparsa.parcelerissue.mvp.injection.DaggerAppComponent;
                                              ^
  symbol:   class DaggerAppComponent
  location: package com.itparsa.parcelerissue.mvp.injection
~/parcelerissue/app/src/main/java/com/itparsa/parcelerissue/main/view/impl/MainActivity.java:7: error: cannot find symbol
import com.itparsa.parcelerissue.main.injection.DaggerMainViewComponent;
                                               ^
  symbol:   class DaggerMainViewComponent
  location: package com.itparsa.parcelerissue.main.injection


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NullPointerException

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
        ...
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        ...
        ... 29 more
Caused by: java.lang.NullPointerException
        at org.parceler.transfuse.util.matcher.InheritsMatcher.matches(InheritsMatcher.java:33)
        at org.parceler.transfuse.util.matcher.InheritsMatcher.matches(InheritsMatcher.java:23)
        at org.parceler.internal.Generators.matches(Generators.java:45)
        at org.parceler.internal.ParcelableAnalysis.validateType(ParcelableAnalysis.java:645)
        at org.parceler.internal.ParcelableAnalysis.innerAnalyze(ParcelableAnalysis.java:315)
        at org.parceler.internal.ParcelableAnalysis.analyze(ParcelableAnalysis.java:68)
        ... 54 more
```

Which is caused from the generic type not being defined... `GenericsUtil.getType()` returns `null` for undefined generics.  So, a `null` check here fixes the issue, although maybe `getType()` should return `Object` instead? https://github.com/johncarl81/parceler/pull/325

With this fix, the build still fails but with this error instead:
```
~/parcelerissue/app/src/main/java/com/itparsa/parcelerissue/model/BaseResponse.java:17: error: Parceler: Unable to find read/write generator for type resultModel for com.itparsa.parcelerissue.model.BaseResponse.result
    public resultModel result;
                       ^
```

**Comment by johncarl81** [comment]
This is deployed to maven central under 1.1.10-SNAPSHOT.  I'll be releasing 1.1.10 shortly.

**Comment by worldsnas** [comment]
wow such wonderful follow up and greate attention

thank you so much for fixing it

may I ask when will it be the final release?

also, i tried to use the snapshot but seems to be failing to resolve it

and one more thing, if you fix this issue in the next version will I be able to use my generic class or I still need to build a concrete one?

**Comment by johncarl81** [comment]
It's released now: http://repo1.maven.org/maven2/org/parceler/parceler/1.1.10/

You will still need to use a concrete class, unless you define a custom converter.

**Comment by worldsnas** [comment]
thank you so much
