### ISSUE TITLE
Transient keyword

### ISSUE THREAD

**Issue by Cilenco** [johncarl81/parceler#333]
I have following class which I want to parcel:

```java
@Parcel
public class Application {
    @SerializedName("packageName") protected final String packageName;

    protected transient String name;
    protected transient boolean selected;

    @ParcelConstructor
    public Application(String packageName, String name) {
        this.packageName = packageName;
        this.name = name;
    }

    public String getPackageName() {
        return packageName;
    }

    public String getName() {
        return name;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public boolean isSelected() {
        return selected;
    }
}
```

Since I use GSON also I can not remove the transient (should work according to this [error](https://github.com/johncarl81/parceler/issues/131)) keyword.
When I try to compile this I get following error:

> Error Parceler: No corresponding property found for constructor parameter name

What do I have to change here? Using version 1.1.9

**Comment by johncarl81** [comment]
Right, making your fields `transient` indicates that you don't want them serialized.  Remove the keyword and you should be good to go.
