### ISSUE TITLE
error: Parceler: Only one ParcelConverter may be declared per property

### ISSUE THREAD

**Issue by MCMrARM** [johncarl81/parceler#336]
Hello,
I have an issue with Parceler. I'm trying to use a ParcelPropertyConverter with a Bean serialization strategy and I'm running into issues.

`error: Parceler: Only one ParcelConverter may be declared per property`

My code:
```java
@Parcel(Parcel.Serialization.BEAN)
public static class WithAppConfig<T> {

    private T wrapped;

    private AppConfig config;

    @ParcelConstructor
    public WithAppConfig(@ParcelPropertyConverter(ParcelWrapperConverter.class) T wrapped, AppConfig config) {
        this.wrapped = wrapped;
        this.config = config;
    }

    public AppConfig getConfig() {
        return config;
    }

    @ParcelProperty("wrapped")
    @ParcelPropertyConverter(ParcelWrapperConverter.class)
    public T getWrapped() {
        return wrapped;
    }

}
```

What I've tried:
- adding the `@ParcelPropertyConverter(ParcelWrapperConverter.class)` to the `wrapped` field itself
  * removing it from the other places - same result as if it was removed from those and not added in this field (ends up with the error in the constructor)
  * not removing it from the other places - same error (`error: Parceler: Only one ParcelConverter may be declared per property`)
- leaving it only in the constructor - `NullPointerException` I'm not sure where exactly because Android Studio does not show it in the Gradle Messages window
- leaving it only in the getWrapped() function - `error: Parceler: Unable to find read/write generator for type T for T wrapped`

**Comment by johncarl81** [comment]
I was able to duplicate the NPE on version 1.1.9, but this wasn't an issue on 1.1.10 - I believe we fixed this bug in the latest update (a286d50).

Here's the proper configuration of your class:
```java
@Parcel(Parcel.Serialization.BEAN)
public static class WithAppConfig<T> {

    private T wrapped;

    private AppConfig config;

    @ParcelConstructor
    public WithAppConfig(@ParcelPropertyConverter(ParcelWrapperConverter.class) T wrapped, AppConfig config) {
        this.wrapped = wrapped;
        this.config = config;
    }

    public AppConfig getConfig() {
        return config;
    }

    public T getWrapped() {
        return wrapped;
    }
}
```

**Comment by MCMrARM** [comment]
Hello,
I can confirm I used 1.1.9 instead of 1.1.10 for the annotation processor (I found the reference to 1.1.9 in the README, might want to update it?).

Also, just tested it with 1.1.10, I can confirm the issue is now fixed. Thanks for your help!

**Comment by johncarl81** [comment]
Ah, thanks for the reminder, updated the README and website.
