### ISSUE TITLE
Problems with Realm 5.x

### ISSUE THREAD

**Issue by Maxxan** [johncarl81/parceler#339]
As soon as I updated realm from version 4 to version 5 parceler failed to generate code correctly. I tried to use the `-AparcelerStacktrace` flag, but gradle complains that it doesn't know the '-A'- flag so I probably do something wrong.

So how to use the command line parameter to correctly get a stack trace to write a better bug report or fix the problem? :)

**Comment by johncarl81** [comment]
Can you put together a working example that I can debug?

**Comment by Maxxan** [comment]
Sure! Here is a [link to a project](https://drive.google.com/file/d/0B-f1Ysy8g4meTklobXJhM2hkaDA/view?usp=sharing) that you can debug. Fails when I try to rebuild all, for example.

**Comment by johncarl81** [comment]
Hmm, could you just create a github repo for this instead of a zip @Maxxan?

**Comment by Maxxan** [comment]
Sure [RealmTest](https://github.com/Maxxan/RealmTest)

**Comment by KingWu** [comment]
migrate realm 3.5.0 to 5.1.0. face the generate code error

**Comment by johncarl81** [comment]
@KingWu face -> fixes?

**Comment by johncarl81** [comment]
@Maxxan, im getting the following errors from your project:
```
/mnt/hd1/home/john/dev/RealmTest/app/src/main/java/com/example/realmtest/Person.java:14: error: cannot find symbol
@org.parceler.Parcel(implementations = { PersonRealmProxy.class },
                                         ^
  symbol: class PersonRealmProxy
/mnt/hd1/home/john/dev/RealmTest/app/src/main/java/com/example/realmtest/Dog.java:9: error: cannot find symbol
@org.parceler.Parcel(implementations = { DogRealmProxy.class },
                                         ^
  symbol: class DogRealmProxy
error: Parceler: Code generation did not complete successfully.  For more details add the compiler argument -AparcelerStacktrace
3 errors
```

I think Realm isnt generating the proxy classes in this case.

**Comment by Maxxan** [comment]
I can post an issue in the Realm repository as well, to see where the problem is..

**Comment by Zhuinden** [comment]
Actually, there was just an implementation change in Realm to allow having the same class name in different packages (think two versions of the same class, for example), so now they include the package name as part of the proxy's class name.

Parceler works just fine.

**Comment by Maxxan** [comment]
It worked fine when I changed to the updated proxy names.

**Comment by johncarl81** [comment]
Good to hear @Maxxan 👍

**Comment by gindaa** [comment]
This is an old post ,
im sorry to bring this back up
but how did you enable the -AparcelerStacktrace?

**Comment by Maxxan** [comment]
In build.gradle for the module add this

```
defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [
                        parcelerStacktrace: "true"
                ]
            }
        }
}
```
