### ISSUE TITLE
Direct support of Android collections (ArraySet and ArrayMap)

### ISSUE THREAD

**Issue by MatFl** [johncarl81/parceler#342]
I think it would be a great addition to this library if the Android specific collections would be directly supported like the e.g. ArrayList is.

https://developer.android.com/reference/android/support/v4/util/ArraySet
https://developer.android.com/reference/android/support/v4/util/ArrayMap

Maybe even directly use the new AndroidX support library with the `androidx.collection` package.

**Comment by johncarl81** [comment]
This sounds nice - create a PR?
