### ISSUE TITLE
Support Incremental Annotation Processing in Gradle 4.7+

### ISSUE THREAD

**Issue by masc3d** [johncarl81/parceler#343]
Support Incremental Annotation Processing in Gradle 4.7+
https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing

**Comment by johncarl81** [comment]
Implemented and will be part of the upcoming 1.1.11 release.  Any help testing the change is appreciated.

**Comment by johncarl81** [comment]
Included in 1.1.11 release.
