### ISSUE TITLE
error: Parceler: Unable to find read/write generator for type org.json.JSONObject for com.myapp.rest.model.ApiResponse.userObj

### ISSUE THREAD

**Issue by saravanans-arch** [johncarl81/parceler#346]
************************************************************************************
error: Parceler: Unable to find read/write generator for type org.json.JSONObject for com.myapp.rest.model.ApiResponse.userObj
************************************************************************************
My code:

ApiResponse.java
==================
package com.myapp.rest.model;

import com.myapp.model.User;
import com.google.gson.annotations.SerializedName;

import org.parceler.Parcel;
import org.json.JSONObject;

import java.util.ArrayList;

@Parcel
public class ApiResponse
{
    @SerializedName("user")
    private User user;

    @SerializedName("userObj")
    private JSONObject userObj;

    public User getUser()
    {
        return user;
    }

    public JSONObject getUserObj()
    {
        return userObj;
    }

}

user.java
======
package com.myapp.model;

import com.google.gson.annotations.SerializedName;

import org.json.JSONObject;
import org.json.JSONStringer;
import org.parceler.Parcel;
import com.google.gson.Gson;

@Parcel
public class User
{
    @SerializedName("email")
    private String email;

    @SerializedName("password")
    private String password;

    @SerializedName("userObj")
    private User userObj;

    public User getUserObj()
    {
        return userObj;
    }

    public String getEmail()
    {
        return email;
    }

    public String getPassword()
    {
        return password;
    }
}

UserService.java
==============
import retrofit.Callback;
import retrofit.http.EncodedPath;
import retrofit.http.Path;
import retrofit.http.GET;
import retrofit.http.Query;

public interface UserService
{
    @GET("/domain/login/{email}/{password}")
    public void getUserAPI(@Path("email") String email,
                           @Path("password") String password,
                           Callback<ApiResponse> callback);
}

**Comment by johncarl81** [comment]
Right, Parceler doesn't know what to do with `JSONObject`.  Either you can provide a custom converter, mark as `@Transient` or avoid using `JSONObject`.
