### ISSUE TITLE
Parcel.unwrap() method returns an object with all fields filled with null when setters are not declared. 

### ISSUE THREAD

**Issue by DanielGunna** [johncarl81/parceler#347]
Parcel.unwrap() method returns an object with all fields filled with null when a model class annotated with `@Parcel(Serialization.BEAN)` doesn't have setters declared. Is it possible to establish something like a warning or simply throwing this error in case I forget to declare setters methods?

**Comment by johncarl81** [comment]
Are you talking about a bean annotated with `@Parcel(Serialization.BEAN)` or just with `@Parcel`?

**Comment by DanielGunna** [comment]
@Parcel(Serialization.BEAN), sorry my bad.

**Comment by johncarl81** [comment]
No problem.  An error on non-matching getter/setter pairs in the BEAN configuration would match the constructor parameter / getter error that we issue.  The difference with getter/setter pairs is the setter call is optional after the class construction.  Technically, you can instantiate a class without the given property provided.  Defining getters and setters really instructs whatever tool (in this case Parceler) how to handle your bean.  If the bean has a read only property, it's not de-serializable.

**Pros:**
Matches constructor / getter property pair behavior
Helps avoid issues defining beans properly

**Cons:**
Noisy
non-matching getter/setters have a specific meaning - either they are read only or just update methods.

I don't know... I'm on the fence on this one.  Thoughts?
