### ISSUE TITLE
Parceler's code generation is too slow

### ISSUE THREAD

**Issue by rongi** [johncarl81/parceler#348]
It looks like Parceler doesn't really support incremental annotation processing and regenerates all the code on each build. Incremental builds in my project are 14 second of which 6 are parceler kapt runs. Replacing Parceler with Kotlin's Parcelize fixes this.

Gradle 4.8
Kotlin 1.2.50
Parceler 1.1.11

**Comment by johncarl81** [comment]
Hmm, I was just working on this and found the opposite to be true - Parceler only regenerates classes that are edited.

Care to be a bit more constructive than critical and offer some evidence or dig in and maybe find out why your case isn't behaving properly and offer a fix?

**Comment by rongi** [comment]
Sorry for sounding a little bit too critical. We are moving to Parcelize, I just thought that may be you'll find this report useful. Just kill it if not :)

**Comment by johncarl81** [comment]
I'd like to know why your build isn't doing incremental builds - seriously I just worked on this https://github.com/johncarl81/parceler/pull/345

**Comment by rongi** [comment]
I think the issue is in Kotlin's kapt annotation processor. It looks like it runs it's job "generate stubs" on each incremental build, and it's a heavy job, it takes 8 seconds to complete on my not so big module. Then kaptDebugKotlin task runs for 3 seconds. As a result I have incremental compile times of 17 seconds. After removing kapt compile times drop down to 6 seconds.
