### ISSUE TITLE
How i can send i list RealmObject in to another activity

### ISSUE THREAD

**Issue by vfa-tuantt** [johncarl81/parceler#349]
I'm facing with a problem. 
I wana to send a list List<Master> into another activity.

```
@Table(name = CL_TABLE_NAME)
@Parcel(
        implementations = arrayOf(MasterRealmProxy::class),
        value = Parcel.Serialization.BEAN,
        analyze = arrayOf( Master::class ))
open class Master( 

): RealmObject() {
}
```
I pass list master data to another activity by this way.
```
var listMaster: List<Master>?
var args = Bundle()
args.putParcelable(IntentKey.INTENT_MASTER_DATA, Parcels.wrap(listMaster))
```

But i got this error:
`org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for io.realm.RealmList, verify that your class is configured properly and that the Parcelable class io.realm.RealmList$$Parcelable is generated by Parceler.`

If you know what is problem happening. Please help me. Thank you so much

**Comment by johncarl81** [comment]
`Parcels.wrap()` doesn't support `RealmList` by default.  You can add support by providing a converter:
```java
@ParcelClass(RealmList.class, converter=...)
```
or using an `ArrayList` or one of the other [collection types](https://github.com/johncarl81/parceler#parcel-attribute-types).

**Comment by vfa-tuantt** [comment]
@johncarl81 

> Parcels.wrap() doesn't support RealmList by default. You can add support by providing a converter:
> 
> @ParcelClass(RealmList.class, converter=...)
> or using an ArrayList or one of the other collection types.
Sorry but I'm using with `List<Master>` and I tried to use `ArrayList<Master>` to send data to another activity but that error always shown. . .

**Comment by johncarl81** [comment]
how did you use `ArrayList`?
