### ISSUE TITLE
Parceler to support -> Restrictions on non-SDK interfaces on Android Pie 

### ISSUE THREAD

**Issue by KevinLeigh** [johncarl81/parceler#354]
As of Android Pie, there is restrictions for using non-SDK interfaces. Please see documentation here -> https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces

Will Parceler be updated to fully support Restrictions on non-SDK?

**Comment by johncarl81** [comment]
Sure, what non-SDK interfaces does Parceler use right now?
