### ISSUE TITLE
Using Parceler and Room together

### ISSUE THREAD

**Issue by krishnasajja** [johncarl81/parceler#356]
I have been using Parceler for a long time with no issues. Recently I started using Room in my project and having both the `@Parcel` and Room related annotations is causing it not to generate the '_Impl' classes.

Error: cannot find the implementation for database

Is this a known issue? Or has someone successfully got Room and Parceler to work together on the same class?

**Comment by johncarl81** [comment]
Hmm, I haven't heard of this and don't see any conflicts between the two libraries off hand.  Could you share a minimal example demonstrating the issue?
