### ISSUE TITLE
Icpick like Storing/Restoring

### ISSUE THREAD

**Issue by airblaster** [johncarl81/parceler#36]
How about support for IcePick style storing/restoring of parcelable classes?
https://github.com/frankiesardo/icepick

Because of the extra wrapping step, IcePick is currently incompatible with parceler (if I'm not mistaken)

**Comment by johncarl81** [comment]
Is there any interest in a fork of Icepick with Parceler support?  Im considering releasing it on Maven central: https://github.com/johncarl81/icepick/tree/parceler_support

**Comment by almozavr** [comment]
> Is there any interest in a fork of Icepick with Parceler support?
Would be great

**Comment by ppamorim** [comment]
+1

**Comment by jacobtabak** [comment]
Yes

**Comment by MichaelEvans** [comment]
+1

**Comment by jonathan-caryl** [comment]
+1

**Comment by rockerhieu** [comment]
+1

**Comment by tom91136** [comment]
I decided to roll my own Ickpick. It is written from scratch and works perfectly with Parceler, please take a look [here] (https://github.com/tom91136/Akatsuki). 


One of the more unique feature of my library is that it supports a pluggable compile-time code generation system. The parceler support is done with ONLY the following lines:

    @TransformationTemplate(
    		save = @StatementTemplate("{{bundle}}.putParcelable({{keyName}}, org.parceler.Parcels.wrap({{fieldName}}))"),
    		restore = @StatementTemplate(type = Type.ASSIGNMENT,
    				                     value = "org.parceler.Parcels.unwrap({{bundle}}.getParcelable({{keyName}}))",
    				                     variable = "{{fieldName}}"),
    		filters = {@TypeFilter(type = @TypeConstraint(type = Parcel.class))}
    		)

**Comment by johncarl81** [comment]
Awesome work @tom91136!
