### ISSUE TITLE
Changelog for 1.1.12

### ISSUE THREAD

**Issue by johnjohndoe** [johncarl81/parceler#370]
I noticed that the [changelog](https://github.com/johncarl81/parceler/blob/master/CHANGELOG.adoc) has not been updated from version 1.1.12. I would appreciate if you could do that.

**Comment by johncarl81** [comment]
[Done](https://github.com/johncarl81/parceler/commit/39624b2b71e2f06e1c556e9d9d198afb9a705912), thanks for keeping an eye on this @johnjohndoe.
