### ISSUE TITLE
Parceler fails when used with with Lifecycle-viewmodel 2.2.0

### ISSUE THREAD

**Issue by LNdame** [johncarl81/parceler#382]
## Description
Bumping from androidx.lifecycle:lifecycle-viewmodel:2.0.0 to androidx.lifecycle:lifecycle-viewmodel:2.2.0 casuse the following issue
`Parceler: Unable to find read/write generator for type java.util.Map<java.lang.String, java.lang.Object> for androidx.lifecycle.ViewModel.mBagOfTags`

mBagsofTags is a private field that is in the lifecycle.ViewModel
```private final Map<String, Object> mBagOfTags = new HashMap<>();```

## Resolution attempt
Creating a custom converter  for the field was unfruitful as the field is private  
``` public class MBagsMapParcelConvertor<String, Object> extends HashMapParcelConverter<String, Object> {


    @Override
    public void mapKeyToParcel(String key, Parcel parcel) {
        parcel.writeParcelable(Parcels.wrap(key),0);
    }

    @Override
    public void mapValueToParcel(Object value, Parcel parcel) {
        parcel.writeParcelable(Parcels.wrap(value),0);
    }

    @Override
    public String mapKeyFromParcel(Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable(java.lang.String.class.getClassLoader()));
    }

    @Override
    public Object mapValueFromParcel(Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable(java.lang.Object.class.getClassLoader()));
    }
}
```

**Comment by johncarl81** [comment]
What object are you annotating with `@Parcel`?

**Comment by maraisf** [comment]
Different person, same project :) I have done some digging and I am pretty sure this is our culprit.

```
@Parcel
public class DataManagerCachedDataImpl extends ViewModel
        implements DataManagerCachedData {
```

Do you have some insight into a workaround we could use?

**Comment by johncarl81** [comment]
Hi @maraisf!  Parceler will attempt to serialize everything, including data members of the inherited classes.  I'd recommend avoiding extending things like the `ViewModel` (which probably has a `Map<String, Object> field) if possible.

**Comment by maraisf** [comment]
Thanks for the quick response and guidance! 👍

**Comment by johncarl81** [comment]
Sure @maraisf, does this solve your issue?

**Comment by maraisf** [comment]
Removing the `extends ViewModel` does infact resolve the error above. Thanks.

**Comment by johncarl81** [comment]
Cool.  You could also use the [analyze](https://oss.sonatype.org/service/local/repositories/releases/archive/org/parceler/parceler-api/1.1.13/parceler-api-1.1.13-javadoc.jar/!/org/parceler/Parcel.html#analyze--) parameter include or exclude `ViewModel` from the generated `Parcelable`, but, generally, I'd recommend keeping the type hierarchy limited.
