### ISSUE TITLE
Facing Vulnerabilities  in parceler library

### ISSUE THREAD

**Issue by KaviIDPal** [johncarl81/parceler#383]
While using annotationProcessor there are 5 Vulnerabilities Found in CRITICAL .

Below the library version we are used:
 **implementation 'org.parceler:parceler-api:1.1.13'
 annotationProcessor 'org.parceler:parceler:1.1.13'**

Vulnerabilities ID
parceler-1.1.13.jar (shaded: commons-beanutils:commons-beanutils:1.9.2)
parceler-1.1.13.jar (shaded: commons-collections:commons-collections:3.2.1)

**Comment by johncarl81** [comment]
Fixed: https://github.com/johncarl81/transfuse/commit/c610df75fe6361e0d71b85337bf1e8c8f71e0eb9 Thanks for the heads up!
