### ISSUE TITLE
No ability to suppress reflection required messages

### ISSUE THREAD

**Issue by bbqsrc** [johncarl81/parceler#45]
```
Warning:(25, 24) Parceler: Reflection is required to modify private field: String secret, consider using non-private.
Warning:(25, 24) Parceler: Reflection is required to access private field: String secret, consider using non-private.
```

I am already using `transient` on static fields, but I am using `@Parcel` on a class that I am also using with GSON for serialisation, so I can't add transient to the private fields as that has a different meaning in GSON (it will not serialise the field).

I am using the `private` access level by design, so I want to be able to suppress this warning. Could you advise me how to do this?

**Comment by ibrahim132** [comment]
Please provide an example for how i can use @ParcelProperty(String value)  when i have private filed

**Comment by johncarl81** [comment]
@ibrahim132:
```java
@Parcel
public class PrivateFieldExample{
    @ParcelProperty("value")
    private String exampleValue;
}
```

**Comment by ibrahim132** [comment]
Thank you for speed response, But i'm still have warnings.
My class:
@Parcel
public class AboutUs {

    @SerializedName(APIConstants.ABOUT_US_AR)
    @ParcelProperty(APIConstants.ABOUT_US_AR)
    private String aboutUsAr;

    @SerializedName(APIConstants.ABOUT_US_EN)
    @ParcelProperty(APIConstants.ABOUT_US_EN)
    private String aboutUsEn;

    public AboutUs() {
    }

    public String getAboutUsAr() {
        return aboutUsAr;
    }

    public void setAboutUsAr(String aboutUsAr) {
        this.aboutUsAr = aboutUsAr;
    }

    public String getAboutUsEn() {
        return aboutUsEn;
    }

    public void setAboutUsEn(String aboutUsEn) {
        this.aboutUsEn = aboutUsEn;
    }

    public String getAboutUs() {
        return AppSettings.getInstance(EBIApplication.getInstance())
                .getCurrentLanguage()
                .equals(AppConstants.ARABIC_LANGUAGE_CODE) ?
                getAboutUsAr() : getAboutUsEn();

    }

}

Warning:(22, 20) Parceler: Reflection is required to modify private field: String aboutUsAr, consider using non-private.
Warning:(26, 20) Parceler: Reflection is required to modify private field: String aboutUsEn, consider using non-private.
Warning:(22, 20) Parceler: Reflection is required to access private field: String aboutUsAr, consider using non-private.
Warning:(26, 20) Parceler: Reflection is required to access private field: String aboutUsEn, consider using non-private.

**Comment by johncarl81** [comment]
Oh, that's not what you were asking...

I'd seriously consider making your fields non-private as this will significantly slow down marshaling.  If you can't and you find the warnings annoying, you could add the `-Xlint:-processing` option as suggested above.

**Comment by ibrahim132** [comment]
Sorry, i thought that was for warnings.
I will try to use the Xlint:-processing
Thank you.

**Comment by Aks-4125** [comment]
@johncarl81  I am still not clear about how to ignore this warning. I tried `@SuppressWarnings("parceler")` but still getting warning. I am using parceler version 1.1.9



`private boolean isChecked;`

> Warning:(14, 21) Parceler: Reflection is required to access private field: boolean isChecked, consider using non-private.

**Comment by aniketmane** [comment]
How to avoid warnings for Singleton classes were the constructor is private. Please help.

**Comment by johncarl81** [comment]
You could use a factory method, I guess.

**Comment by johncarl81** [comment]
FYI, Serializing and deserializing a "singleton" will mean it has a copy, and thus not a Singleton anymore.

**Comment by aniketmane** [comment]
Yeah, I was just looking a way to avoid the warnings. Thanks, @johncarl81.
