### ISSUE TITLE
Usage of parceler (@Parcel) with Realm.io (Android)

### ISSUE THREAD

**Issue by somghosh** [johncarl81/parceler#57]
I have the following code which produces the error: `Error:Parceler: Unable to find read/write generator for type io.realm.Realm for io.realm.RealmObject.realm`

It was working all fine without `extends RealmObject` , however I want to use Realm to put to database easily. Is there a way to exlcude the RealmObject fields and just use the basic pojo fields for @Parcel?

    @Parcel
    public class Feed extends RealmObject{
        int id;
        public String text;
        public String time_created;
        String time_modified;
        int comments_count;
        int likes_count;
        String feed_type;
        int obj_id;
        String image;
        String user_name;
        String user_earthmile_points;
        boolean liked;
        boolean commented;
        boolean is_private;
        String url;
        int feed_creator_id;
    
       }

**Comment by ppamorim** [comment]
+1

**Comment by somghosh** [comment]
@johncarl81 I think that would solve the problem. Many thanks

**Comment by ppamorim** [comment]
@somghosh not working with snapshot, analysisLimit doesn't exist.

**Comment by ppamorim** [comment]
@somghosh not working with snapshot, analysisLimit doesn't exist.

**Comment by johncarl81** [comment]
@ppamorim, I've been working on another branch that I pushed out to maven central.  You can still get to this feature by building the `limit_analysis` branch on your own (#59).

**Comment by dracek** [comment]
@ppamorim I've tried 0.2.16-SNAPSHOT with ActiveAndroid 3.1.0-SNAPSHOT (and Retrofit) and it seems working flawless so far.

```java
@Parcel(value = Parcel.Serialization.BEAN, analysisLimit = SMS.class)
@Table(name = "SMS")
public class SMS extends Model {
    @SerializedName("id")
    @Column(name = "smsid", index = true, unique = true, onUniqueConflict = Column.ConflictAction.FAIL)
    String id;
    // etc.
}
```
@johncarl81 many thanks for your work! I really appreciate it!

**Comment by johncarl81** [comment]
@ppamorim, @dracek, @ppamorim Any thoughts on a more specific approach mentioned above:
```java
@Parcel(value = Parcel.Serialization.METHOD, analyze = {One.class, Three.class)
class One extends Two{}
class Two extends Three{}
class Three extends BaseClass{}
```
^ Where only The One and Three class would be analyzed.  This allows much more control and variability to the property with the drawback of being more verbose.

**Comment by johncarl81** [comment]
This is implemented and deployed in version 0.2.16.

**Comment by ppamorim** [comment]
@johncarl81 Doc it.

**Comment by vickychijwani** [comment]
Thanks a lot for fixing this, @johncarl81!

**Comment by vickychijwani** [comment]
To anyone actually looking to use Parceler with Realm, there's a couple more steps needed:

- Add the android-apt plugin to your build.gradle, so that the generated `Parcelable` class is visible to Android Studio.

```groovy
buildscript {
    repositories {
      mavenCentral()
    }
    dependencies {
        // replace with the current version of the Android plugin
        classpath 'com.android.tools.build:gradle:0.14.4'
        // use the latest version, see http://gradleplease.appspot.com/#android-apt
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'
```

- Use `new Feed$$Parcelable(obj)` instead of `Parcels.wrap(obj)`, otherwise your app will crash with `org.parceler.ParcelerRuntimeException: Unable to create ParcelableFactory for io.realm.MyObjRealmProxy`. You can still use `Parcels.unwrap(...)` on the other side.

**Comment by johncarl81** [comment]
@vickychijwani, does it work to specify the class type instead of referencing the generated class:
`Parcels.wrap(MyObj.class, input)`

**Comment by vickychijwani** [comment]
Yes, it works! Can you explain what causes the error if I call the single parameter version of `Parcels.wrap(...)`? Thanks!

**Comment by johncarl81** [comment]
`Parcels.wrap()` looks up your instance against a map of `ParcelableFactory`s by calling `.getClass()`.  The downside of this is it ignores inheritance, so if your class is proxied (like I assume `MyObjRealProxy` is), then Parceler doesn't know what to do.

worth noting, another way to handle this is add yoru proxy class to the implementations parameter:

`@Parcel(implementations={MyObjRealProxy.class})`

This will add your proxy class to the Parcels wrap mappings.

**Comment by johncarl81** [comment]
@ppamorim Documented here:
https://github.com/johncarl81/parceler#advanced-configuration
http://parceler.org/#advanced_configuration

**Comment by Makingweb** [comment]
I'm trying to use Parceler (1.0.2) and Active Android (3.0.1-SNAPSHOT), but there is something wrong!

I have the following code which produces the error: <code>org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for com.mywebsitetest.android.model.Playlist, verify that your class is configured properly and that the Parcelable class com.mywebsitetest.android.model.Playlist$$Parcelable is generated by Parceler. </code>


```java

@Table(name = "Playlists")
@Parcel(value = Parcel.Serialization.BEAN, analyze = Playlist.class)
public class Playlist extends Model {

    @SerializedName("RemoteId")
    @Column(name = "RemoteId")
    private int remoreId;

    @SerializedName("Token")
    @Column(name = "Token", index = true)
    private String token = "defaultToken";

    @SerializedName("User")
    @Column(name = "User", onDelete = Column.ForeignKeyAction.CASCADE)
    private User user;

    @SerializedName("Name")
    @Column(name = "Name")
    private String name;

    @SerializedName("Create")
    @Column(name = "Created")
    private long created;

    @SerializedName("Updated")
    @Column(name = "Updated")
    private long updated;

    public Playlist() {
        super();
    }

....

```

And in the Main.java I have:

```java
...

Parcelable playlistParcelable = Parcels.wrap(playlist);

...
```

I also tried it in this way:

```java
...

Parcelable playlistParcelable = Parcels.wrap(Playlist.class, playlist);

...
```

but still it does not work, someone knows why?

**Comment by johncarl81** [comment]
Can you share your build?

**Comment by Makingweb** [comment]
Sure!

In the gradle console I also have the follow error:
![error](https://cloud.githubusercontent.com/assets/2823810/8815338/0066462e-3018-11e5-838c-9749fac7db89.png)


build.gradle (Module: app)

```
apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.soundblast.android"
        minSdkVersion 18
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'it.neokree:MaterialTabs:0.11'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'

    compile 'com.michaelpardo:activeandroid:3.1.0-SNAPSHOT'

    compile "org.parceler:parceler-api:1.0.2"
    apt "org.parceler:parceler:1.0.2"
}
```

build.gradle (Project)

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        // replace with the current version of the Android plugin
        // use the latest version, see http://gradleplease.appspot.com/#android-apt
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by johncarl81** [comment]
Ah, it looks like there's an error during compilation.  From your screenshot:
```
Unable to find read/write generator for type com.activeandroid.TableInfo for com.activeandroid.Model.mTableInfo
```
Trying your code out on my test bench, it seems to work properly.  What does `User` look like?

**Comment by ppamorim** [comment]
@johncarl81 Same here :(

**Comment by johncarl81** [comment]
@ppamorim, @Makingweb, can you offer any more details around this?

**Comment by evasquezcr** [comment]
@johncarl81 I'm working with Realm and I got this error, 
'Error:Parceler: Unable to find read/write generator for type io.realm.Realm for io.realm.RealmObject.realm
Error:Parceler: Unable to find read/write generator for type io.realm.internal.Row for io.realm.RealmObject.row
Error:Parceler: Unable to find read/write generator for type io.realm.Realm for io.realm.RealmObject.realm
Error:Parceler: Unable to find read/write generator for type io.realm.internal.Row for io.realm.RealmObject.row'

Do you know if I can change something to make it works?

**Comment by johncarl81** [comment]
@evasquezcr, you'll need to specify what classes Parceler should analyze, to avoid analyzing the `RealmObject` base class.  People also have had success by specifying the Realm Proxy object in the implementations configuration.  Example:

```java
@Parcel(implementations = { PersonRealmProxy.class }, 
        value = Parcel.Serialization.BEAN, 
        analyze = { Person.class })
public class Person extends RealmObject {
	// ...
}
```

See https://realm.io/docs/java/latest/#parceler for details.

**Comment by hunain-liaquat** [comment]
HI, 
How we can have refrence to Proxy class ?

**Comment by johncarl81** [comment]
What do you mean @hunain-liaquat?

**Comment by hunain-liaquat** [comment]
Issue resolved, I didn't find reference to BirthdayRealmProxy.class but found in io.realm package after build successfully compiled once.
