### ISSUE TITLE
Getting Parceler to execute on a lib project and the app itself?

### ISSUE THREAD

**Issue by bjornlate** [johncarl81/parceler#63]
I have a project that uses a shared library project. The library is where the majority of the Parcelables live. I've migrated to Parceler, so far so good :)

We also have some code in the app project that I'd like to use Parceler on as well. 
Everything compiles and runs, but it appears that the Parcels aren't being generated for the classes in the App project though:

01-02 11:04:20.060  26765-26765/com.etsy.android.soe.alpha E/AndroidRuntime﹕ FATAL EXCEPTION: main
    org.parceler.ParcelerRuntimeException: Unable to create ParcelableFactory for foo.bar.AClass
            at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:198)
            at org.parceler.Parcels.wrap(Parcels.java:85)
            at org.parceler.Parcels.wrap(Parcels.java:69)
...

I've tried having the provided statement in either gradle files, that seems to determine which project will have Parcels generated... I can't have it in both, I get a dex error.

Any idea what I'm doing wrong?

**Comment by johncarl81** [comment]
That's strange.  Can you verify a `Parcelable` wrapper is generated for your `AClass` in your library?  Like: `AClass$$Parcelable`

**Comment by bjornlate** [comment]
The library Parcelable wrappers are generated, but there are none in the App Project itself,
AClass$$Parcelable doesn't exist.

**Comment by johncarl81** [comment]
What `Parcelable` wrappers are generated?  It sounds like a wrapper for `AClass` isn't generated.

**Comment by bjornlate** [comment]
With POJOS annotated with @Parcel in both the Library Project and the App Project:


1. If I have the compile/provided statements only in the Library's build.gradle, compilation succeeds. $$Parcel wrappers are generated for all the Library POJOs. But none of the POJOs in the App project.
I'll see exceptions like this upon calling Parcels.wrap on App Project POJOS:
    org.parceler.ParcelerRuntimeException: Unable to create ParcelableFactory for   com.android.lib.models.LibPojo


2. If I move the "provided" statement  to the App Project, compilation succeeds. $$Parcel wrappers are only generated for the App project POJOS, but not the Library POJOS. I'll see the same exception above whenever the Parcels.wrap/unwrap is used on a Lib POJO


3. If I add the compile/provided statements to the build.gradle to both the App Project and the library project I get a dex error:

Error:Gradle: Execution failed for task ':dexAlphaDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/sbirksted/development/android-sdk-macosx/build-tools/21.1.1/dx -JXmx2g --dex --no-optimize --output /MyProject/build/intermediates/dex/alpha/debug --input-list=/MyProject/build/intermediates/tmp/dex/alpha/debug/inputList.txt
  Error Code:
  	2
  Output:
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lorg/parceler/Parceler$$Parcels$1;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
  		at com.android.dx.command.dexer.Main.run(Main.java:245)
  		at com.android.dx.command.dexer.Main.main(Main.java:214)
  		at com.android.dx.command.Main.main(Main.java:106)


Not sure if this is something to do with our setup or Parceler.

**Comment by johncarl81** [comment]
Is your library an .aar?  I'm not sure if this is any different than a .jar
dependency in terms of class lookup.  Parceler will resort to a
`getClass()` call if it can't find the parceler factory in the
Parceler$Parcels mapping.

**Comment by bjornlate** [comment]
putting the provided statement in a gradle file seems to trigger annotation processing.

The catch here is the Parceler$$Parcels.java output result needs to be the union of both projects.

Right now its either the classes in the App Project:

    public Parceler$$Parcels() {
        map$$0 .put(ChildOfBaseObject.class, new Parceler$$Parcels.ChildOfBaseObject$$Parcelable$$0());
        map$$0 .put(ChildOfChildOfBaseObject.class, new Parceler$$Parcels.ChildOfChildOfBaseObject$$Parcelable$$0());
    }

Or the classes in the Lib project.

    public Parceler$$Parcels() {
        map$$0 .put(BaseObject.class, new Parceler$$Parcels.BaseObject$$Parcelable$$0());
    }

But what I need is this:

    public Parceler$$Parcels() {
        map$$0 .put(BaseObject.class, new Parceler$$Parcels.BaseObject$$Parcelable$$0());
        map$$0 .put(ChildOfBaseObject.class, new Parceler$$Parcels.ChildOfBaseObject$$Parcelable$$0());
        map$$0 .put(ChildOfChildOfBaseObject.class, new Parceler$$Parcels.ChildOfChildOfBaseObject$$Parcelable$$0());
    }

**Comment by bjornlate** [comment]
I uploaded the test project, if you care to check it out and reproduce the issue

 https://github.com/bjornlate/parceler-library-project-test


The processor could output a file of all the annotated classes it adds to the Parceler$$Parcels constructor.
If the processor is run again in the project it would check for existence of that file, then add put statements for each class listed in the file...

**Comment by johncarl81** [comment]
Great!  I will take a look this evening.

**Comment by johncarl81** [comment]
@bjornlate I was able to make your project work by removing the parceler annotation processor from the library class and simply referencing the `BaseObject` class from the android project via `@ParcelClass(BaseObject.class)`.  I've issued a PR to you with this change so you can review.

**Comment by bjornlate** [comment]
Thanks @johncarl81 I'll check it out

**Comment by johncarl81** [comment]
@bjornlate, did this work for you?

**Comment by johncarl81** [comment]
@bjornlate, feel free to reopen if this is still an issue.

**Comment by TWiStErRob** [comment]
Just for history's sake: there was a change (https://github.com/johncarl81/parceler/commit/235e74596aad1d65c88fb74bcb069d57cb2fc39d) in [Parceler 1.1.2](https://github.com/johncarl81/parceler/blob/master/CHANGELOG.adoc#release-112-2016-04-30) which doesn't generate `Parceler$$Parcels` any more, instead it only uses this logic to resolve the generated code:
```java
private static String buildParcelableImplName(Class clazz) {
    return clazz.getName() + "$$" + "Parcelable";
}
```
