### ISSUE TITLE
Unable to parcels.wrap a compound Pojo (which has a nested pojo also annotated by @Parcel)

### ISSUE THREAD

**Issue by somghosh** [johncarl81/parceler#65]
@Parcel(Parcel.Serialization.METHOD)
	@Data
	public class Reward {

		private int id;
		private RewardPartner rewardPartner;
		private int points;
		private String image;
	}
	
	@Parcel(Parcel.Serialization.METHOD)
	@Data
	public class RewardPartner  {

		private int id;
		private String name;
		private String image;     
	}
	
	// trying to pass a reward via intent
	Intent intent=new Intent(getContext(),RewardDetailActivity_.class);

	
	intent.putExtra("reward", Parcels.wrap(reward));		

where reward is of type Reward, and has a valid rewardPartner inside it. I want the whole the compound object to be passed from one activity to another via Parcelables

**Comment by johncarl81** [comment]
Hmm, Parceler was designed to handle this case specifically.  When I compile your example code, `RewardPartner` is serialized.  Do you have public getters and setters for all the variables you want serialized?

Is `@Data` a lombok annotation?  I'm not sure that Parceler will be compatible with Lombok's technique of adding code (getters and setters) to the existing classes during compile time.  You might try making your fields non-private and change the Serialization technique to FIELD.

**Comment by johncarl81** [comment]
@somghosh, Feel free to reopen if this is still an issue.
