### ISSUE TITLE
Unwrap hierarchy classes

### ISSUE THREAD

**Issue by emartynov** [johncarl81/parceler#67]
My situation:
``` {java}
@Parcel
public class A {}

@Parcal
public class B extends A {}

@Parcel
public class C {
    List<A> list = new ArrayList<A>();

   public C() {
       list.add(new B());
   }
}
```

After unwrapping list will contain instance of ```A``` instead of ```B```.

I didn't find answer in documentation and example. Could you give a tip?

**Comment by johncarl81** [comment]
We try to avoid reflection as much as possible in Parcel, so we do make one assumption here: `List<A>` contains only `A`s, just like the following:
```java
@Parcel
class D {
    A a;
    public D() {
        a = new B();
    }
}
```
Would contain an `A` after a wrap/unwrap cycle.  Is this a showstopper for you @emartynov?  If anything we should add this to the docs.

**Comment by emartynov** [comment]
I see the point. Just checked Android source how they do it and indeed they use reflection to instantiate creator.

This is showstopper for me. So I will probably fall down to standard ```Parcelable``` implementation.

As for documentation it would be enough to state that such cases are not supported. You can close ticket after.

**Comment by johncarl81** [comment]
If you do use `Parcelable`s directly, you should only have to make `A` and `B` `Parcelable`s.  You can stil use `C` as a `@Parcel`.

You could also use a `ParcelConverter` to do the lookup for you:

```java
@RunWith(RobolectricTestRunner.class)
@Config(manifest=Config.NONE)
public class SubclassTest{
    @Parcel public static class A {}
    @Parcel public static class B extends A {}
    @Parcel public static class C {
        @ParcelPropertyConverter(ParcelsLookupConverter.class)
        List<A> list = new ArrayList<A>();

        public C() {
            list.add(new B());
        }
    }

    @Test
    public void testSubclass(){
        C c = new C();

        C unwrapped = Parcels.unwrap(ParcelsTestUtil.wrap(c));

        assertTrue(unwrapped.list.get(0) instanceof B);
    }

    public static class ParcelsLookupConverter implements ParcelConverter<List<A>> {

        @Override
        public void toParcel(List<A> input, android.os.Parcel parcel) {
            if (input == null) {
                parcel.writeInt(-1);
            } else {
                parcel.writeInt(input.size());
                for (A a : input) {
                    parcel.writeParcelable(Parcels.wrap(a), 0);
                }
            }
        }

        @Override
        public List<A> fromParcel(android.os.Parcel parcel) {
            List<A> contents;
            int size = parcel.readInt();
            if (size < 0) {
                contents = null;
            } else {
                contents = new ArrayList<A>();
                for (int i = 0; (i < size); i++) {
                    contents.add((A)Parcels.unwrap(parcel.readParcelable(A.class.getClassLoader())));
                }
            }

            return contents;
        }
    }
}

```
This would be slightly slower as it looks up each entry by calling `.getClass()`, but it shouldn't be too bad.

**Comment by emartynov** [comment]
I'm trying adopted your solution and what I see that ```toParcel``` is called but ```fromParcel``` is never called.

Here is example of my code:
```{java}
public class SomeFragment extends Fragment {
    List<DiaryEntry> entries;

    @Override
    public void onCreateView(..., Bundle savedInstanceState) {
       ....
       if (savedInstanceState != null) 
       {
            entries = Parcels.unwrap( savedInstanceState.getParcelable( LOADED_ENTRIES_KEY ) );
       }
    } 

    @Override
    public void onSaveInstanceState( Bundle outState )
    {
        super.onSaveInstanceState( outState );
        
        if ( entries != null )
        {
            outState.putParcelable( LOADED_ENTRIES_KEY, Parcels.wrap( entries ) );
        }
    }
}

@Parcel
public class DiaryEntry implements Serializable
{
   Schema schema;
}

@Parcel
public class Schema implements Serializable
{
    @ParcelPropertyConverter( ParcelsLookupConverter.class )
    ArrayList<Field> fields;
   ...
}

@Parcel
public class Field implements Serializable {}

@Parcel
public class ComplexField extends Field implements Serializable {}
```

**Comment by WalrusCow** [comment]
I just ran into this issue as well - confused me greatly for a bit, because it was occurring on fields that were transient for GSON deserialization but should be included in a parcel.

@johncarl81 I'd love to put this fact more prominently in the README along with an example of how to use a `ParcelConverter` - would you be open to such a pull request?

@emartynov 
Here is a sample of code that I had, now working
```java
@Parcel
public class Item {
    @ParcelConverter(ItemListParcelConverter.class)
    public List<Item> itemList;
}
@Parcel public class SubItem1 extends Item {}
@Parcel public class SubItem2 extends Item {}

public class ItemListParcelConverter implements ParcelConverter<List<Item>> {
    @Override
    public void toParcel(List<Item> input, Parcel parcel) {
        if (input == null) {
            parcel.writeInt(-1);
        }
        else {
            parcel.writeInt(input.size());
            for (Item item : input) {
                parcel.writeParcelable(Parcels.wrap(item), 0);
            }
        }
    }

    @Override
    public List<Item> fromParcel(Parcel parcel) {
        int size = parcel.readInt();
        if (size < 0) return null;
        List<Item> items = new ArrayList<Item>();
        for (int i = 0; i < size; ++i) {
            items.add((Item) Parcels.unwrap(parcel.readParcelable(Item.class.getClassLoader())));
        }
        return items;
    }
}
```

Now I have used it something like
```java
Item item = new Item();
item.itemList.add(new SubItem2());
item.itemList.add(new SubItem1());
```

After wrap and unwrap by putting a breakpoint I notice that we have the SubItems in the list of appropriate type.

**Comment by johncarl81** [comment]
@WalrusCow Im always open to PRs!  Please feel free to work on this.

I almost think we could add an annotation to indicate that Parceler should wrap/unwrap instead of assuming it is the given type.  something like this:
```java
@Parcel
public class Item {
    @ParcelWrapUnwrap
    public List<Item> itemList;
}
```

Or maybe we could provide a Wrap/Unwrap converter:
```java
@Parcel
public class Item {
    @ParcelListItemConverter(ParcelWrapUnwrapConverter.class) // would use this converter for each element in the this.
    public List<Item> itemList;
    @ParcelConverter(ParcelWrapUnwrapConverter.class)
    public Item itemInstance;
}
```

**Comment by WalrusCow** [comment]
Is `ParcelListItemConverter` an existing annotation?

**Comment by johncarl81** [comment]
Not yet.

**Comment by WalrusCow** [comment]
Another option might be to have something like a `Serialization.DEEP` option to always do `.getClass()` lookups. Then you could specify it like:
```java
@Parcel(Serialization.DEEP)
public class Item {
    // ...
}
```

I don't actually like that option -- it forces a performance hit on every field -- but thought I might as well mention it.

Seems to me like `@ParcelConverter` approach would be the way to go, if only because having `@ParcelWrapUnwrap` would be mutually exclusive with it anyway.  If you agree, I can see about making it happen, but I am a little new to Android/Java so don't hold your breath =)

**Comment by johncarl81** [comment]
What do you think about providing some baseline ParcelConverters?  I think a series of decorator converters would be nice (null-checking, List/Map/Collection) and maybe a set that do with your example do, call to Parcels.wrap/unwrap.

**Comment by johncarl81** [comment]
LOL, I forgot, I already wrote the null decorator one: https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/NullableParcelConverter.java

**Comment by bjdupuis** [comment]
Very confusing addition to the example. 

```java
@Parcel
public class Item {
    @ParcelConverter(ItemListParcelConverter.class)
    public List<Item> itemList;
}
```

`@ParcelConverter` isn't isn't retained as an annotation in the library. Did you mean `@ParcelPropertyConverter`?

**Comment by johncarl81** [comment]
Shoot, you're correct @bjdupuis it should be `@ParcelPropertyConverter`

**Comment by johncarl81** [comment]
(fixed)

**Comment by bjdupuis** [comment]
Excellent, thank you.

**Comment by bjdupuis** [comment]
In the vein of misleading documentation (and mildly to completely off-topic), the `Serialization.BEAN` change never percolated to a released version. It's on `master` but the 0.2.15 version which (appears to be) the latest Maven-distributed version doesn't have it. That's fine, but the documentation shows usage of `Serialization.BEAN`.

**Comment by johncarl81** [comment]
yeah, we need to do a release soon with this change.  Unfortunately, the README reflects the latest SNAPSHOT.

**Comment by johncarl81** [comment]
@WalrusCow, I added the various base Converters tonight, so you coudl write your example with the `ArrayListParcelConverter` as follows:
```java
@Parcel
public class Item {
    @ParcelPropertyConverter(ItemListParcelConverter.class)
    public List<Item> itemList;
}
@Parcel public class SubItem1 extends Item {}
@Parcel public class SubItem2 extends Item {}

public class ItemListParcelConverter extends ArrayListParcelConverter<Item> {

    public void itemToParcel(List<Item> input, Parcel parcel) {
        parcel.writeParcelable(Parcels.wrap(item), 0);
    }

    public Item itemFromParcel(Parcel parcel) {
        Parcels.unwrap(parcel.readParcelable(Item.class.getClassLoader())));
    }
}
```

**Comment by emartynov** [comment]
Thanks guys! It works for me. Should I close ticket?

**Comment by johncarl81** [comment]
Sure, I'm happy with the changes and I think we've addressed this issue.
