### ISSUE TITLE
Parceler and AIDL

### ISSUE THREAD

**Issue by yuriymyronovych** [johncarl81/parceler#70]
I am trying to use parceler for the pojos I need for android aidl. It does not compile though as auto-generated aidl expects Parcelable methods in there.

NOTE - I am not sure whether it is an issue or not, sorry if it was misleading.

**Comment by johncarl81** [comment]
Hmm, not sure what the issue is.  Can you use the generated `Parcelable`s directly?  Care to share some example code?

**Comment by yuriymyronovych** [comment]
Maybe I missed something, but here are the details:

I am implementing Remote android service using AIDL.
RendezvousService.aidl:
package com.example.IPCTest;
interface RendezvousService {
      Rendezvous createRendezvous();
}

Here is Rendezvous.aidl:
package com.example.IPCTest;
parcelable Rendezvous;

Here is Rendezvous.java
@Parcel
public class Rendezvous {
    public String tag;
    public Rendezvous(String tag) {
        this.tag = tag;
    }
}

Now using aidl files android generates the following service code:
case TRANSACTION_createRendezvous:
{
data.enforceInterface(DESCRIPTOR);
com.example.IPCTest.Rendezvous _result = this.createRendezvous();
reply.writeNoException();
if ((_result!=null)) {
reply.writeInt(1);
_result.writeToParcel(reply, android.os.Parcelable.PARCELABLE_WRITE_RETURN_VALUE);
}
else {
reply.writeInt(0);
}
return true;
}


And this fails to compile as there is no method .writeToParcel in the Rendezvous object.
I assume the way your library works that it generates additional stuff on runtime based on Parcel annotation, but on compilation time there is nothing in there, right?

**Comment by yuriymyronovych** [comment]
Can you use the generated Parcelables directly?
Are those generated on runtime or on compile time? If those are generated on compile time I can try to use it...

**Comment by johncarl81** [comment]
Yes, you can use the generated `Parcelable`s directly.  The only downside is it becomes a bit difficult in the IDE to use pre-generated code.

On the filp side, you could use the wrapped instances by the interface `Parcelable`.  I don't have a ton of experience with AIDL, so forgive me if this isn't 100%:
```java
package com.example.IPCTest; 
interface RendezvbrbrousService {
      Parcelable createRendezvous();
}
```

**Comment by johncarl81** [comment]
Let me know if you would like to reopen.

**Comment by yuriymyronovych** [comment]
Hi John, thanks for your comments. Unfortunately you can't use generic Parcelable in AIDL definitions.
I am afraid I have to keep writing parcel able code myself :(

**Comment by johncarl81** [comment]
Can you not reference the generated code?  I believe what you will have to reference is the Rendezvous$$Parcelable class.

**Comment by yuriymyronovych** [comment]
Maybe I can in theory, but than I am enforced to work with Rendezvous$$Parcelable class in my code :(. This is not ideal :(

**Comment by johncarl81** [comment]
Agreed.  You could also copy the generated source into your source tree and turn code generation off (remove `@Parcel`).

**Comment by yuriymyronovych** [comment]
Well, yea true, but… you understand :)

In fact if there is a way to make it work with annotations I am willing to contribute(read implement it ) to this project.

Can you say at which point do you generate $$Parcelable class?
What if instead of generating the new class the parcelable code will be injected in the source class?

If you are interested have a look at a class Rect here - http://developer.android.com/guide/components/aidl.html
This is how android expects parcelable to be fully implemented. In this way it is suitable for any use of parcelable as well as AIDL.

What do you think?

**Comment by johncarl81** [comment]
I see this as a problem at the IDE level.  Java will compile your source successfully using this annotation processor.

Parceler generates the $$Parcelable classes at annotation processor compile phase.

It's possible to inject code into the source classes, but generally frowned upon and not the direction we go with Parcler.

Looking at the IDE issue, are you using Android Studio?  If so, this plugin may help pick up the generated source: https://bitbucket.org/hvisser/android-apt.

**Comment by yuriymyronovych** [comment]
Ok, thanks anyway for your support!
