### ISSUE TITLE
how can i get the thumbnail ?

### ISSUE THREAD

**Issue by mouhsinelonly** [johncarl81/parceler#72]
{
is_image: true,
attachment_meta: {
width: 4288,
height: 2848,
file: "2015/02/Shop-Page-copy1.jpg",
sizes: {
thumbnail: {
file: "Shop-Page-copy1-150x150.jpg"
}
}
}

@Parcel
public class Post {
}

**Comment by johncarl81** [comment]
Not sure what the question is (related: #71)
