### ISSUE TITLE
annotate which field can be serialize?

### ISSUE THREAD

**Issue by jiqimaogou** [johncarl81/parceler#73]
hi
I just want to parcel just on field of my class, how can I do?

or
auto ignore unparcel field.

I am using dbflow, and every bean class extends basemodel, but basemodel has a modeladapter, it can not be parceled.

**Comment by johncarl81** [comment]
Simply mark what fields you don't want included in the `Parcelable` with `@Transient`.  This goes for base classes as well.

**Comment by jiqimaogou** [comment]
thank you.

**Comment by jiqimaogou** [comment]
but baseModel is in other library which can not be modified, how can I exclude super class field in subClass?

**Comment by johncarl81** [comment]
The best solution currently is to write a `ParcelConverter` by hand (See http://parceler.org/#custom_serialization).  We have a similar issue identified here: #58, with a fix in the works here: #62.  Do these describe your problem accurately and do you have any input on the proposed PR?

**Comment by jiqimaogou** [comment]
super class(which is can not be modified)
```
public abstract class BaseModel implements Model {
    private ModelAdapter mModelAdapter;

    public ModelAdapter getModelAdapter() {
        return mModelAdapter;
    }
}
```
subclass
```
public class Model extends BaseModel {
     public string name;
}
```

How can I do exclude BaseModel ```mModelAdapter``` field.

**Comment by johncarl81** [comment]
Annotate `Model`:
```java
@Parcel(converter = ModelConverter.class)
public class Model extends BaseModel {
     public String name;
}
```
And define `ModelConverter`:
```java
public static class ModelConverter implements ParcelConverter<Model>{

    @Override
    public void toParcel(Model input, android.os.Parcel parcel) {
        parcel.writeString(input.name);
    }

    @Override
    public Model fromParcel(android.os.Parcel parcel) {
        Model model = new Model();
        model.name = parcel.readString();
        return model;
    }
}
```
(Until #62 is finished)

**Comment by bryant1410** [comment]
I think a better approach is to make the model inherit this class instead of `BaseModel`:

```java
@ParcelClass(value = ModelAdapter.class, annotation = @Parcel(converter = ModelAdapterConverter.class))
public abstract class ParcelableBaseModel extends BaseModel {

}
```

And having this:

```java
public class ModelAdapterConverter implements ParcelConverter<ModelAdapter> {
    @Override
    public void toParcel(ModelAdapter input, Parcel parcel) {

    }

    @Override
    public ModelAdapter fromParcel(Parcel parcel) {
        return null;
    }
}
```

Otherwise, it would be nice if `BaseModel` could have it field as `transient`.

**Comment by khafan** [comment]
@bryant1410 I'm getting "an enclosing instance that contains blahblah.ModelAdapterConverter is required" error in an auto generated dbflow class in. Error lines are marked with a "//HERE" comment in front of them.
```java
public class ModelAdapter$$Parcelable
    implements Parcelable, ParcelWrapper<ModelAdapter>
{

    private ModelAdapter modelAdapter$$0;
    @SuppressWarnings("UnusedDeclaration")
    public final static ModelAdapter$$Parcelable.Creator$$0 CREATOR = new ModelAdapter$$Parcelable.Creator$$0();

    public ModelAdapter$$Parcelable(android.os.Parcel parcel$$0) {
        modelAdapter$$0 = new com.shaya.poinila.android.data.database.PoinilaDataBase.ModelAdapterConverter().fromParcel(parcel$$0); // HERE!
    }
    public ModelAdapter$$Parcelable(ModelAdapter modelAdapter$$1) {
        modelAdapter$$0 = modelAdapter$$1;
    }
    @Override
    public void writeToParcel(android.os.Parcel parcel$$1, int flags) {
        new com.shaya.poinila.android.data.database.PoinilaDataBase.ModelAdapterConverter().toParcel(modelAdapter$$0, parcel$$1);  // HERE!
    }

    @Override
    public int describeContents() {
        return  0;
    }

    @Override
    public ModelAdapter getParcel() {
        return modelAdapter$$0;
    }

    public final static class Creator$$0 implements Creator<ModelAdapter$$Parcelable> {
        @Override
        public ModelAdapter$$Parcelable createFromParcel(android.os.Parcel parcel$$2) {
            return new ModelAdapter$$Parcelable(parcel$$2);
        }

        @Override
        public ModelAdapter$$Parcelable[] newArray(int size) {
            return new ModelAdapter$$Parcelable[size] ;
        }
    }
}
```
Any idea how to resolve this?

**Comment by bryant1410** [comment]
[DBFlow 3.0.0-beta1](https://github.com/Raizlabs/DBFlow/tree/3.0.0-beta1) `BaseModel` is now `Parcelable`. You can just use this version.

**Comment by khafan** [comment]
@bryant1410 Tnx but I'm not very sure about using a beta version.
Did your way really work for you? That seems far better than writing lots of boilerplate parcelConverter code

**Comment by bryant1410** [comment]
@khafan I haven't used it. The other option that comes to my mind is to fork the last stable version and make `BaseModel` `Parcelable`. Just apply [this change](https://github.com/Raizlabs/DBFlow/commit/dba2cf766df7cd35d7943bb4ac3bc5f87fdf278e)

**Comment by johncarl81** [comment]
@bryant1410, I'm not seeing `BaseModel` implementing `Parcelable`, but with that change you linked it does mark fields with `transient` that Parceler should respect and would make the given class extending `BaseModel` compatible with Parceler out of the box (without a converter as you and I mentioned).

**Comment by bryant1410** [comment]
Yeah! Sorry! I meant that, to make it work with Parceler out of the box

**Comment by johncarl81** [comment]
:+1:

**Comment by johncarl81** [comment]
@khafan, we do have another option if you want to ignore the base class entirely, if that is what you want.  You can use the `analyze` field to avoid certain classes in the inheritance hierarchy:
```java
@Parcel(analyze=Model.class)  // Will not analyze BaseModel
public class Model extends BaseModel {
     public String name;
}
```


http://parceler.org/#skipping_analysis

**Comment by bryant1410** [comment]
@johncarl81 good tip!

**Comment by khafan** [comment]
@johncarl81 Awesome! Completely satisfy my conditions. Will try that :+1:
