### ISSUE TITLE
Possibility for @ParcelPackage annotation?

### ISSUE THREAD

**Issue by justincpollard** [johncarl81/parceler#75]
Hi John,

Today I was attempting to annotate one of our classes with `@Parcel` and came to a state where Parceler was throwing `org.parceler.ParcelerRuntimeException: Unable to create ParcelableFactory for ...` exceptions. @dbachelder looked into the issue and theorized that every `@Parcel` annotated class needs an entry point from which Parceler can reach it. The `@ParcelClasses` annotation seems to be one (maybe the only one?) of these entry points.

After adding the exception triggering class(es) to our `@ParcelClasses`, the problem appears to be solved, but I'm wondering if there might be a more comprehensive, less ad-hoc way to specify the classes that we want Parceler to traverse. Is there a way you could create an `@ParcelPackage` annotation that would server to specify an entire package in which Parceler should look for @Parcel classes?

Thanks!

**Comment by dbachelder** [comment]
worth noting that the Parcel classes in question are in a library submodule not in the app being built.

**Comment by johncarl81** [comment]
To clarify, if you annotated your classes in a library you would have to have the parceler-api as a dependency, is the regular parcel annotation processor and dependency and run against the library during its compile?  `Parcels.wrap()`/`unwrap()` should be able to pick up generated `Parcelable` classes in a library as a fall-through case, even though Parceler generates a dictionary lookup of the generated classes (see [this](https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/Parcels.java#L212) if you're interested).

As for scanning an entire package, it would be more succinct.  I'd have to think about the feature a bit to consider the drawbacks.

Honestly, what instantly came to mind is a secondary processor to listen during the compiler phase and generate the verbose `@ParcelClasses` based on a package input for then Parceler to pick up.  Something like this:

1.  Annotate `@PackageProcess("com.package.blah", ParcelEventhingInPackage.class)` somewhere in project.
2.  PackageProcess then uses `ParcelEverythingInPackage` (a plugin) to generate `@ParcelClasses(...)` for everything in `com.package.blah`
3.  Parceler runs in a subsequent round, picks up the `@ParcelClasses` and does what it normally does.

Maybe I'm getting too creative though :-)

**Comment by dbachelder** [comment]
We are finding that if we run the processor against the library we can end up seeing duplicate PackageHelpers... one in the library and one in the app.. we just started hitting that problem today.. so our solution was to not run the processor on the library anymore. Seems to work fine now, as long as the application is annotated as Justin specified above.

**Comment by johncarl81** [comment]
Shoot, that would happen if you use the same package between a library and libarary-using codebases.  You may also see duplicate `Parceler$$Parcels` classes (#24).  I wish there was a better solution for this.

On that note, it's probably out of the realm of possibilities to scan for all classes in a given package outside of the codebase under compilation because of the annotation processor technique Parceler uses.  That being said, it would not be impossible, libraries like [Reflections](https://github.com/ronmamo/reflections) are able to do this with a higher amount of startup runtime overhead.

**Comment by johncarl81** [comment]
Hmm, maybe the `PackageHelper`s should be per-class class-namespaced instead of per-package not-namespaced.

**Comment by johncarl81** [comment]
And it looks like the are per-class.  You must be running into an issue of overlapping PackageHelpers in this case anyways.

**Comment by johncarl81** [comment]
I like this idea in principle, but I think it has some critical drawbacks.  For one, it won't index library classed under the given package, at least using the Annotation Processing technique.  This may seem very misleading and add to the library problems that Paceler faces.  Also, it's edging into generating Parcelable classes for classes that don't necessarily need to be Parcelable.  I'd rather keep it explicit.

If I'm missing anything please correct me, but for now I think I'm going to pass on this feature.  Thanks for the input though @justincpollard!

**Comment by justincpollard** [comment]
Thanks for considering the change!
