### ISSUE TITLE
TransactionTooLargeException

### ISSUE THREAD

**Issue by nemanja-kovacevic** [johncarl81/parceler#76]
Hi guys, not really an issue with Parceler per se but you might find it to be an interesting read or at least tell me if I'm using it wrong. I'm hitting the transaction buffer limit much more easily when using Parcelable/Parceler than with plain java serialization. More info here http://nemanjakovacevic.net/blog/english/2015/03/24/yet-another-post-on-serializable-vs-parcelable/

P.S. 
I love the lib, great work guys!

**Comment by johncarl81** [comment]
Great article and analysis.  I was not aware of these upper bounds.

+1 for _"do not trust blindly everything you read on the internet and make some trials on your own real life scenario."_

By the way, I wrote a little performance testing application along the lines of what you mentioned that illuminates performance differences between the different serialization options.  Here's the results I came up with:

Name | Time to Serialize
--------|---------
Parceler | 404935.1442ns
Parcelable| 430859.1484ns
Parceler with AutoValue | 489583.3968ns
AutoParcel | 1037421.0286ns
Gson | 1533837.9367ns
Serializable | 3059908.4384ns
And the example:
https://github.com/johncarl81/parceler/tree/master/examples/performance
Yes, in certain configurations, Parceler writes Parcelables that will be faster than traditional Parcelable classes, especially when dealing with collections and `writeValue`

Looking at your test project, there may be some work we can do to cram more objects into a Parceler generated Parcelable.  In your example, the vast majority of storage is filled up with a flag indicating if the given `ArrayList` entry is null or not:
```java
for (net.nemanjakovacevic.parcelexperiment.EmptyObject emptyObject$$2 : ((java.util.ArrayList<net.nemanjakovacevic.parcelexperiment.EmptyObject> ) package$$0 .mList)) {
    if (emptyObject$$2 == null) {
        parcel$$10 .writeInt(-1);
    } else {
        parcel$$10 .writeInt(1);
        writenet_nemanjakovacevic_parcelexperiment_EmptyObject(emptyObject$$2, parcel$$10, flags);
    }
}
```
If we could store a single bit instead we may be able to increase the size of this case by 32x.

**Comment by nemanja-kovacevic** [comment]
Not really sure how you could write a single bit but even if you just use writeByte instead of writeInt you'll get 4x less space used for that part of the format.

My real issue, the one I've was running into TTLE with, is that I was trying to move a graph of objects with Parceler. Imagine there is a description field on your Developer class that can be a fairly large string, and that Skill class also has a list of Developers, let's say experts for the Skill, and those have their own skills (no circular references though). The thing is that the Parceler will marshall and demarshall copies of Developer objects thus creating copies of the whole sub graph. That why I think I'm seeing serialization being faster than Parceler in my real life scenario.

Also serializable seem to use a different way of dealing with strings. I'm not very good when it comes to encodings and all that jazz but I can move twice as large String with serializable than with Parcelable, so that might be another area where Parceler can improve.

**Comment by johncarl81** [comment]
Really these are deficiencies with the native `Parcelable` implementation from Android.  I'm not sure what Parceler could do to make this better.  Why are you not storing these large strings on the file system or database instead?

Of note, `writeByte` uses `writeInt` internally (https://github.com/android/platform_frameworks_base/blob/master/core/java/android/os/Parcel.java#L589).  

To use bits you would have to use a `byte[]` and bitwise operations.  I imagine I could store a `byte[]` that encodes each bit to 0 or 1 based on if the corresponding collection entry is null or not.

**Comment by nemanja-kovacevic** [comment]
Yeah, you're right about the writing bytes thing.

The thing is those strings are nothing crazy, a simple paragraph of text. But they are being recreated many times because the references are not preserved. That's the problem, the duplication of every string. So I just reverted to serialization for this particular case and everything is cool.

**Comment by johncarl81** [comment]
Ah, I see.  Would reimplementing the graph serialization like mentioned here #66 aid in this issue?  This would preserve the structure of the graph better as well as only serialize the individual instances once.

**Comment by nemanja-kovacevic** [comment]
That would solve my issue I think, even though I don't have circular references in this particular graph.

**Comment by johncarl81** [comment]
Im assuming you have diamond references, like this:
A -> B -> E
A -> C -> E
A -> D -> E
This would duplicate E 3 times.

**Comment by nemanja-kovacevic** [comment]
something like that, and there is a whole graph on E position so that makes thing worse

**Comment by johncarl81** [comment]
I think I have a reasonable solution here: #154. Would love feedback before merging and releasing.
