### ISSUE TITLE
Add documentation for proguard rules

### ISSUE THREAD

**Issue by emartynov** [johncarl81/parceler#77]
Library could be shipped with own rules since gradle supports merging rules from proguard.cfg from libraries. But this will require to pack it as aar library.

**Comment by johncarl81** [comment]
Could we accomplish this with the existing Maven build?  I assume we would just need to add this to the parceler-api module.

**Comment by emartynov** [comment]
Building ```aar``` is supported by android maven plugin. But adding the proguard rules is probably by gradle only. Probably should wait for next android maven plugin release

**Comment by johncarl81** [comment]
Would you like to put together a PR in anticipation of the next Maven plugin release @emartynov ?

**Comment by emartynov** [comment]
Sure thing! 

As soon as PR merged we could start using SNAPSHOT and try it out. Even better we just take fork from requester and use local SNAPSHOT.

But documentation is still must be provided for people who are using older android gradle plugins

**Comment by johncarl81** [comment]
The documentation is fully editable via git (both the README in this repo and we [website](http://parceler.org/): https://github.com/johncarl81/parceler-site

**Comment by emartynov** [comment]
Do I understand correctly that for website I should generate adoc from asciidoc?

**Comment by johncarl81** [comment]
Jekyll and Travis will generate it automatically, but if you want to run it locally just run `jekyll serve` (See https://github.com/asciidoctor/jekyll-asciidoc-quickstart)

**Comment by emartynov** [comment]
So I need to do same edits in both places. Clear! Probably could be automated

**Comment by johncarl81** [comment]
Agreed, but they are slightly different.

**Comment by funkthemonk** [comment]
I also had to add
-dontwarn org.parceler.**
-dontwarn javax_.lang.model.util.**

**Comment by johncarl81** [comment]
@funkthemonk, what (generated I suppose) classes under javax.lang.model.util are producing warnings?
