### ISSUE TITLE
ViewPager + Fragment = unable to marshal value

### ISSUE THREAD

**Issue by mbmc** [johncarl81/parceler#81]
Hi,

I have a `ViewPager` which creates `Fragments` and sets object in the `Bundle`
```
public class ViewPagerAdapter extends FragmentStatePagerAdapter {
    public Fragment getItem(int position) {
        return MyFragment.newInstance(model);
    }
}

public class MyFragment extends Fragment {
        public static MyFragment newInstance(Model model) {
        MyFragment fragment = new MyFragment();
        fragment.setArguments(Parcels.wrap(model);
        return fragment;
    }
}
```

When the `Activity` containing the `ViewPager` goes to the background:
```
ActivityManagerProxy.activityStopped
FragmentManagerState.writeToParcel
FragmentState.writeToParcel
```
the `Fragment` tries to marshal its data, then it throws `java.lang.RuntimeException: Parcel: unable to marshal value com.Model@xxx` because `Model` doesn't implement `Parcelable`. I could avoid the problem by passing its id instead, and retrieving it from a cache.

**Comment by johncarl81** [comment]
It sounds like a `Parcelable` isn't being generated for `Model`.  Can you verify that a `$$Parcelable` class exists?

**Comment by mbmc** [comment]
Just saw your last comment on https://github.com/johncarl81/parceler/issues/80. That fixes the problem. Thanks!
