### ISSUE TITLE
Using "provided" instead of "apt" doesn't work when using in conjunction with a project that uses "apt"

### ISSUE THREAD

**Issue by AlexBravo** [johncarl81/parceler#87]
I recently upgraded my project from Dagger 1 to Dagger 2.
After the upgrade I noticed that $$Parcelable files are not generated anymore.

After looking for a reason I found that I have to use either "apt" or "provided" in both Dagger2 and Parceler.
apt is needed by Dagger2, so I had to switch for using "apt" in Parceler.

I'm not sure if this is bug in Parceler, but I would like to have a compile time notification when $$Parcelable files are not generated instead of a runtime crash.

**Comment by johncarl81** [comment]
Hmm, why does Dagger 2 require apt?
Do you know what is blocking the Parceler annotation processor from running when mixing provided and apt scopes?  I was under the impression the reason to use apt was for Android Studio to pick up the generated sources.

**Comment by DHuckaby** [comment]
Dagger 2 requires it because you reference generated classes directly so apt is needed so android studio can see the generated classes correctly.

**Comment by johncarl81** [comment]
Ok, makes sense.  Any idea if and why apt and provided scopes are incompatible @DHuckaby?

**Comment by DHuckaby** [comment]
No idea, I use Dagger 2 with Lombok with also generates files. To get them working together I had to declare lombok as both provided and apt. It duplicates the dependency declaration but it works. I recommend for @AlexBravo to give that shot.

**Comment by johncarl81** [comment]
@hvisser, care to comment on this one?  Is there any way we can raise an error if a processor doesn't run?

**Comment by hvisser** [comment]
(Sorry I missed this in my inbox)
The reason why this probably doesn't work is that `apt` sets up the annotation processing path. 

Without `android-apt` any processor in the compile path (both `compile` and `provided`) would work, since that's the default way that `javac` finds a processor. 

There's no way to warn if the processor isn't run since the Parceler processor is simply never invoked by `javac`. 

It generally makes more sense to use `apt` if you use `provided` since it has the same effect + putting the generated classes in the source path, which aids debugging.

**Comment by hvisser** [comment]
By the way, _technically speaking_ `android-apt` isn't required by Dagger 2. Code will compile fine without it from the command line and Android Studio, but editing code in Android Studio won't work because it doesn't "see" the generated code without `android-apt`.

**Comment by johncarl81** [comment]
Awesome, thanks for the detailed explanation @hvisser :+1: 

@AlexBravo good to close?

**Comment by AlexBravo** [comment]
> There's no way to warn if the processor isn't run since the Parceler processor is simply never invoked by javac.
Is there a way to make runtime crashing more predictable at least?

**Comment by AlexBravo** [comment]
Thanks for all the explanations, btw.

**Comment by johncarl81** [comment]
> Is there a way to make runtime crashing more predictable at least?

I'm open to suggestions, but probably not.
