### ISSUE TITLE
 org.parceler.ParcelerRuntimeException: Unable to create ParcelableFactory 

### ISSUE THREAD

**Issue by ppamorim** [johncarl81/parceler#88]
I don't know why happens this problem.
Can you review my code, I really think this is correct. wtf...

https://github.com/ppamorim/Amazing-MVP/blob/master/amazingMVP/src/main/java/com/amazing_mvp/domain/model/Genre.java

**Comment by johncarl81** [comment]
Hmm, not sure.  Maybe proguard is removing the generated classes?

**Comment by ppamorim** [comment]
proguard is disabled.

**Comment by johncarl81** [comment]
Looking at your Genre class, I don't think you need the `BEAN` configuration as you have also configured the fields to be parcel properties.

**Comment by ppamorim** [comment]
WIth or without BEAN. It still not working.

**Comment by ppamorim** [comment]
@johncarl81 I've added a test class and guess it! Still giving error.

**Comment by ppamorim** [comment]
@johncarl81 I've found the problem.
 Please remove the "provided" from readme and add "apt". "provided" never works with me.

**Comment by johncarl81** [comment]
Relevant discussion on provided vs apt: #87.  Provided should work.
