### ISSUE TITLE
Using Parceler in two different modules causes DexException

### ISSUE THREAD

**Issue by itsmortoncornelius** [johncarl81/parceler#89]
When using Parceler in two different modules I get the following exception:

    com.android.dex.DexException: Multiple dex files define Lorg/parceler/Parceler$$Parcels$1;

My build.gradle files look like this:
 
    compile "org.parceler:parceler-api:${parcelerVersion}"
    apt "org.parceler:parceler:${parcelerVersion}"

and apt is configured like this:

    // apply apt plugin from global gradle file
    apply plugin: 'android-apt'

    // Tell apt where to find sources
    apt {
        arguments {
            androidManifestFile variant.outputs[0].processResources.manifestFile
            resourcePackageName 'de.company.android.application'
        }
    }

**Comment by itsmortoncornelius** [comment]
I also tried "provided" instead of "apt"

**Comment by ultraon** [comment]
+1
And my suggestion is set package name of Parceler$$Parcels dynamically: 
- from module name 
or 
- have counter for Parceler$$Parcels (e.g. Parceler$$Parcels0, Parceler$$Parcels1, Parceler$$Parcels2...).

**Comment by johncarl81** [comment]
I added a bit about this recently to the README: https://github.com/johncarl81/parceler#avoiding-parcels-indexing.  The strategies I suggest are setting `parcelsIndex=false` or using `@ParcelClass` outside of the library.

The alternative strategy (to the two already proposed) would be to namespace the file through some sort of configuration local to the library compilation.

**Comment by ultraon** [comment]
@johncarl81 I have next structure of project:
- modul1 (contains business logic POJO models);
- modul2 (contains mock business logic POJO models extended from models from module1);
- application (uses models from module1 and module2);

When i put @Parcel(parcelsIndex = false) for all models in module1 and module2 Parceler$$Parcels class generated for both modules -> result MultiDex exception. May be it's a bug or please clarify how exectly shoul i use "parcelsIndex = false" for all models in library modules and where be placed generated Parceler$$Parcels in this case?
Keep in mind i use models in 3rd module "application"

**Comment by johncarl81** [comment]
Hmm, can you look at the `Parceler$$Parcels` generated class in your libraries?  If they don't contain `map.put()` calls then that would be a bug.

**Comment by ultraon** [comment]
@johncarl81 It contains following in module1:
```
public class Parceler$$Parcels
    implements Repository<org.parceler.Parcels.ParcelableFactory>
{
...
//copy-past only constructor
    public Parceler$$Parcels() {
        map$$0 .put(FaqItemImpl.class, new Parceler$$Parcels.FaqItemImpl$$Parcelable$$0());
    }
...
}
```
and following in module2:
```
public class Parceler$$Parcels
    implements Repository<org.parceler.Parcels.ParcelableFactory> {
...
    public Parceler$$Parcels() {
        map$$0 .put(MockFaqItemImpl.class, new Parceler$$Parcels.MockFaqItemImpl$$Parcelable$$0());
    }
...
}
```

And this to classes Parceler$$Parcels make com.android.dex.DexException: Multiple dex files define Lorg/parceler/Parceler$$Parcels$1;

**Comment by johncarl81** [comment]
Did you mark `FaqItemImpl` and `MockFaqItemImpl` as `parcelsIndex = false` and recompile your library artifacts?

**Comment by ultraon** [comment]
@johncarl81 yes, I wrote about it message before. Could you tell me what is correct behavior when I use parcelsIndex = Whether to generate Parceler$$Parcels file? (If yes, where is his correct location between modul1, modul2, application modul)?

**Comment by ultraon** [comment]
Also I tried to use @ParcelClasses and it worked correctly, only one Parceler$$Parcels was generated in application modul, but I don't understand in this case how can I use field converters ?

**Comment by itsmortoncornelius** [comment]
so if I understand correctly, there is an issue with the "parcelsIndex=false" approach but @ParcelClass is working?

**Comment by ultraon** [comment]
@johncarl81 so is it bug with attr "parcelsIndex=false"?

**Comment by johncarl81** [comment]
Hmmm, it seems to be.
If I remember correctly, you should be able to still annotate your bean with `@ParcelPropertyConverter` and reference the bean with `@ParcelClass` to pick it up in the root module.

**Comment by ultraon** [comment]
O, it's great if it will :-) 
@johncarl81 Are you planning to fix bug with ```"parcelsIndex=false"```?

**Comment by johncarl81** [comment]
Of course.  However, as always, a PR would be appreciated.

**Comment by johncarl81** [comment]
FYI, just fixed this.  Seems it was an issue deep in the transfuse core dealing with primitive types in annotations.  The current 0.2.17-SNAPSHOT contains the fix.

**Comment by ultraon** [comment]
@johncarl81 Thank you very much! :-) I'm waiting for release 0.2.17

**Comment by itsmortoncornelius** [comment]
Is there a possibility to already use the snapshot?

**Comment by johncarl81** [comment]
Yeah, use the snapshot repo:
```groovy
repositories {
    mavenCentral()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
}
```
and, of course, update the Parceler dependency:
```groovy
    apt 'org.androidtransfuse:parceler:0.2.17-SNAPSHOT'
    compile 'org.androidtransfuse:parceler-api:0.2.17-SNAPSHOT'
```

**Comment by itsmortoncornelius** [comment]
Thank you
