### ISSUE TITLE
Wrap Collections.unmodifiableList(myParcelableList) invokes error

### ISSUE THREAD

**Issue by ultraon** [johncarl81/parceler#90]
Hi, i tried to use Parcel lib with following case:
```
public class Item {
    protected String title;

//setters stuff
...

    public String getTitle() {
        return title;
    }
}
```
Then in the other place of my code i use following declaration of this class: 
```
@ParcelClass(Item.class)
```
After that i do following:
```
List<Item> items = Collections.unmodifiableList(getItems()); //getItems() returns ArrayList<Item>
Parcelable parcelItems = Parcel.wrap(items); 
```

And in result i get error:
"org.parceler.ParcelerRuntimeException: Unable to create ParcelableFactory for java.util.Collections$UnmodifiableRandomAccessList
at org.parceler.Parcels$ParcelCodeRepository.get(Parcels.java:198)
            at org.parceler.Parcels.wrap(Parcels.java:85)
            at org.parceler.Parcels.wrap(Parcels.java:69)
..."

Could anybody help me with this case?

**Comment by johncarl81** [comment]
Parceler needs a little help here knowing what time to use.  Try this:
```java
Parcelable parcelItems = parcel.wrap(List.class, items);
```

**Comment by ultraon** [comment]
thank you!
