### ISSUE TITLE
suppress warnings

### ISSUE THREAD

**Issue by dbachelder** [johncarl81/parceler#93]
When casting serializable, add `@SuppressWarnings("unchecked")`

```
NavItem$$Parcelable.java:45: warning: [unchecked] unchecked conversion
        navItem$$1 .contentFragment = ((Class) parcel$$309 .readSerializable());
                                       ^
```

or maybe just on the whole generated class.

**Comment by johncarl81** [comment]
Not a bad idea... here's the spot you'd add the code generation in for the entire class: https://github.com/johncarl81/parceler/blob/master/parceler/src/main/java/org/parceler/internal/ParcelableGenerator.java#L86

Or we could scope this to the method I guess in these spots:  
https://github.com/johncarl81/parceler/blob/master/parceler/src/main/java/org/parceler/internal/generator/ParcelReadWriteGenerator.java#L61
https://github.com/johncarl81/parceler/blob/master/parceler/src/main/java/org/parceler/internal/generator/ParcelReadWriteGenerator.java#L85

And here's a similar example of adding an annotation for reference: https://github.com/johncarl81/parceler/blob/master/parceler/src/main/java/org/parceler/internal/ParcelableGenerator.java#L144
