### ISSUE TITLE
Not work in pure java sub project

### ISSUE THREAD

**Issue by kejunxia** [johncarl81/parceler#94]
It seems like the lib doesn't work with sub pure java project and get error 
"Unable to create ParcelableFactory"

I am using AndroidStudio and gradle. Project structure is like 
--
  --AndroidApp
  --JavaProject

AndroidApp project is depending on JavaProject and all `@Parcel` objects are defined in JavaProject. Both project declared Parceler and Parceler-API dependencies.

I checked the objects with `@Parcel` in AndroidApp project work great!

Any thoughts?

**Comment by johncarl81** [comment]
You need to either include the parceler annotation processor as a compile time (provided or apt) dependency of the library sub-project or call out the classes you want a generated Parcelable for using the `@ParcelClass` in your root Android project.

**Comment by kejunxia** [comment]
Thanks for the quick reply. Solution 2 works perfect. 

However I could not get solution one work properly in the sub jvm project
1. compile scope works but increases apk size
2. provided seems not generating code
3. is this project the one you are referencing for apt? It requires android-library plugin
https://bitbucket.org/hvisser/android-apt

**Comment by johncarl81** [comment]
yes, that's the project for apt scope.
