### ISSUE TITLE
List<CustomObj> and @Parcel(Parcel.Serialization.BEAN) does not work with some class names

### ISSUE THREAD

**Issue by jeffdcamp** [johncarl81/parceler#96]
`@Parcel(Parcel.Serialization.BEAN)` will give the following warning, if a class has a "wrong" name (see Example code below):
``
"warning: Parceler: Reflection is required to modify private field: String uri, consider using non-private."
``

**RESULT:**
Because of this warning all of the fields defined in "OtherItem" will use reflection. ("Item" class seems to be fine)

**EXPECTED RESULT:**
No warning and no reflection in generated code (for both "Item" and "OtherItem")

**WORKAROUND:**
- If I rename/refactor the class `OtherItem` to `SubItem` then everything works as expected (no warning and no reflection).  This is very random on what class names work and which ones don't (most class names don't seem to work)
- Don't use "Parcel.Serialization.BEAN" and make all variables public. (not desired workaround)

**OTHER DETAILS:**
- Android Studio Gradle project
- Dependencies
    - compile 'org.parceler:parceler-api:1.0.0'
    - provided 'org.parceler:parceler:1.0.0'

**Example code:**
```java
@Parcel(Parcel.Serialization.BEAN)
public class Item {
    private List<OtherItem> otherItemList;

    public List<OtherItem> getOtherItemList() {
        return otherItemList;
    }

    public void setOtherItemList(List<OtherItem> otherItemList) {
        this.otherItemList = otherItemList;
    }
}
```

```java
@Parcel(Parcel.Serialization.BEAN)
public class OtherItem {
    private String uri;
    public String getUri() {
        return uri;
    }
    public void setUri(String uri) {
        this.uri = uri;
    }
}
```

**Comment by johncarl81** [comment]
Ah, that's interesting.  It looks like the serialization type isn't being picked up with `@Parcel` annotated beans in collections.  The way this is related to the name of the class is likely due to the order of when each class is processed.

Here's the fix: 71cd99e3952bd5023e9a20811a62994df33da0a8

**Comment by jeffdcamp** [comment]
Awesome!  Thanks for the quick response and the quick fix!

I just verified that your fix, fixes this issue (we look forward 1.0.1 and to start using parceler)

**Comment by johncarl81** [comment]
1.0.1 was just released to maven central with this bug fix.

**Comment by LaurieScheepers** [comment]
Excellent thanks
