### ISSUE TITLE
Changelog request

### ISSUE THREAD

**Issue by johnjohndoe** [johncarl81/parceler#97]
Please consider providing a textual **changelog** so it is easier for users to see what changes from version to version.

* [Example changelog of devise](https://github.com/plataformatec/devise/blob/v3.1.1/CHANGELOG.md)
* [Example changelog of cancan](https://github.com/ryanb/cancan/blob/1.6.10/CHANGELOG.rdoc)
* [Example changelog of angular.js](https://github.com/angular/angular.js/blob/v1.1.5/CHANGELOG.md)
* [GitHub offers release notes](https://github.com/jeffkreeftmeijer/fuubar/releases/new)
* [GitHub release notes example of better_errors](https://github.com/charliesome/better_errors/releases)
* [Umweltzone](https://github.com/johnjohndoe/Umweltzone/blob/master/CHANGELOG.md)

**Comment by johncarl81** [comment]
What do you think about annotating the tags instead: https://github.com/johncarl81/parceler/tags ?

**Comment by johnjohndoe** [comment]
It is a matter of taste. I personally like to stay independent of the tool (GitHub) I use. It will be hard to take the changelog aka. release notes with you when you move the repository to another place. They will even be missing if you clone the repository to your local machine in order to work offline. In the end it is your decision (as long as they are public).

**Comment by StErMi** [comment]
I would really love to have a changelog. For istance I would like to track all the changes and backward incompatible things in the 1.0.4 version.

**Comment by jonathan-caryl** [comment]
A changelog would be really helpful.

**Comment by johncarl81** [comment]
Ok, I finally went ahead and added a `CHANGELOG.adoc`.  Thoughts?

**Comment by jonathan-caryl** [comment]
👍🏻
