### ISSUE TITLE
After proguard, parcel list object causes crash.

### ISSUE THREAD

**Issue by 7unzhou** [johncarl81/parceler#98]
```
android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called  CREATOR on class org.parceler.NonParcelRepository$ListParcelable
```

**Comment by johncarl81** [comment]
Can you put a Proguard rule in to keep the `org.parceler.NonParcelRepository$ListParcelable`?

**Comment by 7unzhou** [comment]
Thanks you.After add proguard rule ,the problem has solve.

**Comment by johncarl81** [comment]
@7unzhou, can you share your Proguard configuration?  We're putting together some recommendations and I'd like to compare.
